### ISSUE TITLE
Not an issue - parallel development of projects for the same goal

### ISSUE THREAD

**Issue by Aterfax** [ct-Open-Source/tuya-convert#1]
Hi fellas, looks like you've developed an alternate project in parallel with [TuyOTA](https://github.com/SynAckFin/TuyOTA) by SynAckFin and [MockTuyaCloud](https://github.com/kueblc/mocktuyacloud) by kueblc.

A few people have been having discussion in [here](https://github.com/codetheweb/tuyapi/issues/49) about it with respect to several devices and getting the Tasmota firmware loaded.

Figured you guys might be interested in what others have been doing along the same lines.

Would be nice if a shared list of supported devices could be contributed to :)

**Comment by kueblc** [comment]
Added related works section to `README`. Create a PR to add any more!
