### ISSUE TITLE
Successfully flashed Merkury 11w Color+white

### ISSUE THREAD

**Issue by ForSquirel** [ct-Open-Source/tuya-convert#102]
Managed to get this flashed but it could not get it flashed as directed. Don't know if its on my end or just whats required but had to do the reset on the light after the ```start_flash script```.

Using the MagicHome module does allow for it to be used in the Tasmota web interface and gives brightness control.

Have not figured out how to do colors though.

**Comment by kueblc** [comment]
We [just added support](https://github.com/arendst/Sonoff-Tasmota/pull/4991) for this LED driver. You can compile the latest development branch and set your module type to `SYF05` and GPIO13 to `SM16716 PWR` for color support.

**Comment by maikthulhu** [comment]
I've uploaded a template for these Merkury bulbs at [User Created Templates](https://github.com/arendst/Sonoff-Tasmota/wiki/User-created-templates)

**Comment by ForSquirel** [comment]
building and flashing latest dev branch allows for bulb to work as expected.
