### ISSUE TITLE
Sucessfully Flashed MartinJerry Smart Switch 

### ISSUE THREAD

**Issue by jluzonpr** [ct-Open-Source/tuya-convert#103]
https://www.amazon.com/gp/product/B07C235D9G

```
GPIO 5 Led1
GPIO 12 Relay1
GPIO 13 Button1
```

Gonna post all of this since it might be useful.

```
ChipID: ca883b
SdkVersion: 1.5.3(aec24ac9)
BootVersion: 4
BootMode: 1
FlashMode: 1M QIO @ 40MHz
FlashChipId: 1440c8
FlashChipRealSize: 1048576
FlashChipSize: 1048576
FlashChipMode: 0
system_upgrade_userbin_check: user2 0x81000
```

**Comment by erwill2** [comment]
I noticed a red light and another button under the main. Can these also be setup?

**Comment by jluzonpr** [comment]
@erwill2 I could definitely do some digging to find the red light but not sure what this other button would be. Could you explain more?

**Comment by kueblc** [comment]
Thanks for the report @jluzonpr please feel free to add your findings to the wiki for visibility
