### ISSUE TITLE
Sonoff B1 possible?

### ISSUE THREAD

**Issue by red-hood** [ct-Open-Source/tuya-convert#104]
Hi,
does someone know if the Sonoff B1 is actually based on tuya and would work with these scripts? The official app to be used with this bulb is WELink, not Smart Life, so I am not sure if it uses tuya or not. Any help appreciated.

**Comment by mobidarabbit** [comment]
I dont think it works. Sonoff is a non tuya brand and closed all ota "bugs" in his firmware.

**Comment by red-hood** [comment]
Interesting, I always thought Sonoff would use tuya. I guess that this means soldering then.
