### ISSUE TITLE
Successfully Flashed MartinJerry mini Smart Plug

### ISSUE THREAD

**Issue by mikepruett3** [ct-Open-Source/tuya-convert#105]
https://www.amazon.com/MartinJerry-Compatible-Devices-required-installation/dp/B071Z94F4F

```
GPIO  4 Led1i (56)
GPIO 12 Relay1 (21)
GPIO 13 Button1 (17)
```

I have tons of these in my house, and I have been able to flash 10 of them so far without an issue!

**Comment by kueblc** [comment]
Thanks for the report @mikepruett3 please feel free to add your findings to the wiki for visibility
