### ISSUE TITLE
Ubuntu 22.04 TPLink USB & Qualcom Laptop AP not visbile by other devices

### ISSUE THREAD

**Issue by DSDV** [ct-Open-Source/tuya-convert#1052]
### Before opening a new issue, please read the following

**Are you reporting a successful flash?**
_Please add it to the wiki instead!_
no
**Do you have a question about configuring your newly flashed device?**
_Please ask in your alternative firmware's support channel instead!_
no
**Did you have issues getting a device to flash?**
_Please be sure to include your device **name, model, and firmware version** as well as your **logs**!_
i have not yet gotten to the device nor logs
**Please remember to close your issue when the problem has been addressed!**
yes i will

**Comment by cjj25** [comment]
Your WiFi chipset might not support all the features.
Are you using the docker version or running the scripts directly? What's the output of `iwconfig`

**Comment by DSDV** [comment]
that might be the problem :/ sad to see that internal and external card did not work. 

Soldering iron solved the problem :D
