### ISSUE TITLE
Firmware is too new but version is older

### ISSUE THREAD

**Issue by TrustedFloppa** [ct-Open-Source/tuya-convert#1074]
Hello recently I found Gosund SP111 and it had firmware 1.0.2![Screenshot_2022-12-07-22-59-01-160_com.tuya.smart.jpg](https://user-images.githubusercontent.com/85476585/206306133-3559621c-06f2-4f25-bf98-633c00ec5188.jpg) and tuya-convert returns with firmware too new

**Comment by kueblc** [comment]
Hi @TrustedFloppa 

If the tooling reports that the firmware is too new, it is too new. There's nothing else we can do.

**Comment by TrustedFloppa** [comment]
I flashed the same plug with 1.0.5 and it worked, I guess I will flash using serial
