### ISSUE TITLE
SP111 with ip 10.42.42.34-38

### ISSUE THREAD

**Issue by skupu** [ct-Open-Source/tuya-convert#1104]
Unfortunetely after the device connects vtrust it gets another ip.
I modified the script, but port 80 is closed, so I even don't know if there is another chance of flashing OTA.

SP111 firmware 1.0.6, MCU 1.0.6

Official support claims this is not compatible with tasmota...

Anyone has any suggestions?

**Comment by TrustedFloppa** [comment]
1.0.6 is patched, the only way is to serial flash wich is easy.

![image](https://github.com/ct-Open-Source/tuya-convert/assets/85476585/f0d521f9-ab48-4e9b-b0b2-dc281d71837b)
