### ISSUE TITLE
Should old Blitzwolf BW-SHP4 UK work?

### ISSUE THREAD

**Issue by divadiow** [ct-Open-Source/tuya-convert#1118]
Blitzwolf app has never had any updates for it. Still says v1. I've had it a few years. Kinda hoped it was an old enough ESP firmware to be OTA flashed. Doesn't even get to making a backup stage.

[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/13369611/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/13369612/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/13369613/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/13369614/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/13369615/smarthack-wifi.log)

**Comment by divadiow** [comment]
scratch that. saw success in other posts if using Pi Buster instead of Bullseye. tuya-convert worked and the SHP4 is running Tasmota now. Had to use the Gosund SP1 v23 module though

**Comment by kueblc** [comment]
:+1:
