### ISSUE TITLE
Successfully flashed Woox R4028 Smart Power Strip EU Type 16 A 3 Ports

### ISSUE THREAD

**Issue by BoBiene** [ct-Open-Source/tuya-convert#12]
No issue at all.

I have successfully flashed the Woox R4028 Smart Power Strip EU Type 16 A 3 Ports (https://www.amazon.de/dp/B07GFNL67Z/).

> VTRUST-FLASH 1.0
(c) VTRUST GMBH https://www.vtrust.de/35c3/

>READ FLASH: http://10.42.42.42/get?read=HEX-ADDRESS
ChipID: d69d9d
MAC: DC:4F:22:D6:9D:9D
SdkVersion: 1.5.3(aec24ac9)
BootVersion: 4
BootMode: 1
FlashMode: 1M DOUT @ 40MHz
FlashChipId: 144051
FlashChipRealSize: 1048576
FlashChipSize: 1048576
FlashChipMode: 3
system_upgrade_userbin_check: user2 0x81000

My tasmota config is 
https://cdn.pbrd.co/images/HXZlVnH.png

**Comment by merlinschumacher** [comment]
Thanks for your addition!
