### ISSUE TITLE
Tuya smart relay 

### ISSUE THREAD

**Issue by epicurean70** [ct-Open-Source/tuya-convert#122]
Has anyone  done a Tuya Convert with this relay?

https://www.aliexpress.com/item/Tuya-Smart-Life-WiFi-Light-Switch-Alexa-Echo-Google-Home-Voice-Control-10A-Remote-Control-Light/32956975062.html?spm=2114.12010108.1000013.1.1b404342M4MUcR&gps-id=pcDetailBottomMoreThisSeller&scm=1007.13339.90158.0&scm_id=1007.13339.90158.0&scm-url=1007.13339.90158.0&pvid=a1e6c39f-a6a6-4020-9b6b-cbb53bc65325

Just wondering how to figure out the settings even if it can be done

**Comment by kueblc** [comment]
Please see Sonoff-Tasmota for configuration assistance, this is just the project for flashing a Tuya device OTA
