### ISSUE TITLE
Red flashing LED

### ISSUE THREAD

**Issue by sobo85** [ct-Open-Source/tuya-convert#125]
Hi

I flashed my Gosund SP1 with Tasmota. After flashing i've connected to the "sonof xxxx" wifi and filled my ssid and password. After reboot automatic of the SP1 it can't connect to wifi because of wrong password (fritzbox told me). Can i reset the wifi setting? The buttom of the SP1 doesn't work.

**Comment by AS137430** [comment]
[https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-entered-the-wrong-wi-fi-password-and-i-have-no-button-to-reset-config](Tasmota Wiki)

**Comment by sobo85** [comment]
1 device still flashing red :/

**Comment by kueblc** [comment]
@sobo85 This is the issue tracker for tuya-convert. Please see Sonoff-Tasmota for support with their firmware. Thanks and good luck!
