### ISSUE TITLE
Successfully flashed Bomcosy E27 smart led bulb

### ISSUE THREAD

**Issue by dipl-ingo** [ct-Open-Source/tuya-convert#126]
Manufacturer: Bling lighting technologies Co. Ltd.
Tel: +86-75527498886

7W / 600lm

flashmode: 1M QIO @ 40MHz

**Comment by kueblc** [comment]
Thanks for your contribution, did you add it to the wiki?

**Comment by macronom** [comment]
Today I had no success flashing a newly purchased Bomcosy bulb (E27 smart LED Bulb).
