### ISSUE TITLE
Successfully flashed EXTSUD 10W E27 RGB Dimmable WiFi Smart Led

### ISSUE THREAD

**Issue by double1968** [ct-Open-Source/tuya-convert#129]
Successfully flashed EXTSUD 10W E27 RGB Dimmable WiFi Smart Led
[https://www.amazon.it/gp/product/B07FKQ7N9Q/ref=ppx_yo_dt_b_asin_title_o08_s00?ie=UTF8&psc=1](https://www.amazon.it/gp/product/B07FKQ7N9Q/ref=ppx_yo_dt_b_asin_title_o08_s00?ie=UTF8&psc=1)
You can add compatibility list.
Tasmota module type AiLight 27 work fine 

wiki compatible list:
|[EXTSUD](https://www.amazon.it/gp/product/B07FKQ7N9Q/ref=ppx_yo_dt_b_asin_title_o08_s00?ie=UTF8&psc=1)|E27|10W RGB Dimmerabile WiFi|?|?|AiLight 27 Profile|?|?

**Comment by kueblc** [comment]
Thanks for the contribution!

**Comment by Keltere** [comment]
@double1968 sorry to bother but what template did you use on tasmota?

**Comment by Keltere** [comment]
I can confirm that even the e14 version it's working with AiLight 27 module type

**Comment by BlackRedM** [comment]
any one have the template/profile? i have this one: 

https://www.amazon.de/gp/product/B07D6ZKR6Q/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1
