### ISSUE TITLE
Successfully flashed Jisusu SP111 WiFi plug

### ISSUE THREAD

**Issue by DerHolgi** [ct-Open-Source/tuya-convert#137]
With the help from @kueblc I was able to successfully flash the Jisusu SP111 WiFi plug.
https://www.amazon.de/dp/B07MR167HS
See my issue #136 for details.

With best regards.

**Comment by kueblc** [comment]
Thanks for the report @DerHolgi glad it worked out. Could you add your findings to the wiki?
