### ISSUE TITLE
Succesfully Flashed Kogan smart plug

### ISSUE THREAD

**Issue by Alfiegerner** [ct-Open-Source/tuya-convert#142]
Kogan provide cheap smartplugs and bulbs in Australia and New zealand.

READ FLASH: http://10.42.42.42/get?read=HEX-ADDRESS
ChipID: 50c491
MAC: 80:7D:3A:50:C4:91
SdkVersion: 1.5.3(aec24ac9)
BootVersion: 4
BootMode: 1
FlashMode: 1M QIO @ 40MHz
FlashChipId: 1440c8
FlashChipRealSize: 1048576
FlashChipSize: 1048576
FlashChipMode: 0
system_upgrade_userbin_check: user2 0x81000

I haven't tried the energy draw, (not interested) but switch working fine using:

sonoff generic,
GPIO0 - Button 1
GPIO13 - Led1
GPIO14 - Relay 1

**Comment by kueblc** [comment]
Thanks for the contribution, please feel free to add it to the wiki for increased visibility
