### ISSUE TITLE
install_prereq.sh fails

### ISSUE THREAD

**Issue by FransM** [ct-Open-Source/tuya-convert#151]
ubuntu 18.04.2 LTS

install_prereq.sh fails with:

Processing triggers for systemd (237-3ubuntu10.15) ...
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 7, in <module>
    from pip._internal import main
ModuleNotFoundError: No module named 'pip._internal'

I fixed this with
python3 -m pip install --user --upgrade pip

and reran the install_prereq script

**Comment by kueblc** [comment]
Should be resolved by #196, once we get it cleaned up and merged
