### ISSUE TITLE
Luminea WLAN LED Bulb ZX-2831-675

### ISSUE THREAD

**Issue by 22MarioZ** [ct-Open-Source/tuya-convert#156]
I'm trying to convert the mention WiFi LED bulb (is listed as compatible devices) but I have no success.

The script come to "Waiting for the upgraded device to appear" and I get a lot of ........

Some how the device cannot be find.

When the bulb in paring mode (flashing on regular basis (switch on/switch off) I can see the bulb AP. IS this OK?

I used the latest version of tuya-convert.

**Comment by kueblc** [comment]
The device needs to be in EZ Config mode, not AP Config mode. It should blink quickly and no AP should appear from the device.

**Comment by 22MarioZ** [comment]
Thank you. Managed to convert. To help others: to put the bulb in EZ Config mode the switch on/off needs to be really quick (5 time at least).
