### ISSUE TITLE
Successfully flashed Gosund WP3 outlet

### ISSUE THREAD

**Issue by dhami220** [ct-Open-Source/tuya-convert#17]
No issues.

Initially tried with old RPI (v 1.2?), script displayed some error message related to arm processor.

Switched to latest RPI B+, flashed tasmota without any issues.

At the end, had to remove my wifi router password to see sonoff. 

Link to the device: https://www.amazon.com/Assistant-Required-Enabled-Control-Gosund/dp/B072ZX8RTZ

**Comment by merlinschumacher** [comment]
Thanks for your feedback!

**Comment by ragenhe** [comment]
@dhami220 - Can you share the details of your module configuration please?  Danke!
