### ISSUE TITLE
Gosund sp111

### ISSUE THREAD

**Issue by moneybag** [ct-Open-Source/tuya-convert#18]
Backup wird gemacht
ip 10.42.42.42  wird zugewiesen

wird aber nicht geflashed

ping 10.42.42.42 ist ok

curl http://10.42.42.42/flash2
device is already booting from userspace 2 (0x81000)

 curl http://10.42.42.42/flashURL?url=http://10.42.42.1/files/thirdparty.bin
Device should flash http://10.42.42.1/files/thirdparty.bin and restart

passiert nix

 curl http://10.42.42.42/flash3 

auch nicht

any ideas?

**Comment by kurim** [comment]
Ggf. mehrfach flash3 machen, ich brauchte auch grad 3 versuche bis das Device sich hat flashen lassen
Wichtig, wann hast du den git clone gemacht, denn gestern abend fehlte die sonoff-basic.bin im paket

**Comment by moneybag** [comment]
noch mal fürs protokoll:
Die gosund hat die IP 10.42.42.42 ?

**Comment by moneybag** [comment]
alles neu aufgesetzt heute morgen

100x mal probiert

curl http://10.42.42.42/flashURL?url=http://10.42.42.1/files/thirdparty.bin
Device should flash http://10.42.42.1/files/thirdparty.bin and restart

da passiert nix, kein fortschrittsbalken, keine meldung

WPS klappt auch nicht, AP wird auch nicht aufgemacht

**Comment by kurim** [comment]
Welche Plattform nutzt du?
Raspberry 3b+? mit Kali?
Wenn ja das hat bei mir auch nicht geklappt, nimm das image 2018-11-13-raspbian-stretch-lite.img
Damit hat es letztlich geklappt

**Comment by moneybag** [comment]
raspberry 3b jessy
aber warum wird ein backup erfolgreich gemacht? Ist doch unlogisch

**Comment by nanobyte84** [comment]
@moneybag schau nach ob sonoff-basic.bin da ist mit

> ls -l files

Außerdem kannst du in einem zweiten Terminal sehen ob die firmware geladen wird mit

> screen -x  smarthack-web

**falsch:** [W 190124 00:04:26 web:2162] **404** GET /files/thirdparty.bin (10.42.42.42) 0.78ms
**richtig:** [I 190124 00:08:03 web:2162] **200** GET /files/thirdparty.bin (10.42.42.42) 7249.08ms

**Comment by moneybag** [comment]
Last login: Sat Jan 26 17:38:01 2019
root@iobroker:~# cd tuya-convert/
root@iobroker:~/tuya-convert# ls -l files
insgesamt 1824
lrwxrwxrwx 1 root root     33 Jan 26 09:59 1.bin -> esp8266-ota-flash-convert_upg.bin
-rw-r--r-- 1 root root 254212 Jan 26 09:59 esp8266-ota-flash-convert.ino-0x81000.bin
-rw-r--r-- 1 root root 508475 Jan 26 09:59 esp8266-ota-flash-convert_upg.bin
-rw-r--r-- 1 root root 546032 Jan 26 10:14 sonoff-basic.bin
-rw-r--r-- 1 root root 546032 Jan 26 10:14 tasmotapriv.bin
lrwxrwxrwx 1 root root     16 Jan 26 09:59 thirdparty.bin -> sonoff-basic.bin
lrwxrwxrwx 1 root root     41 Jan 26 09:59 user2.bin -> esp8266-ota-flash-convert.ino-0x81000.bin
root@iobroker:~/tuya-convert# mc


root@iobroker:~/tuya-convert/scripts# cat smarthack-web.log 
Listening on port 80
[I 190127 09:35:32 web:2162] 200 GET /files/thirdparty.bin (10.42.42.42) 220.88ms
[I 190127 09:35:32 web:2162] 200 GET /files/thirdparty.bin (10.42.42.42) 63.69ms
[I 190127 09:35:39 web:2162] 200 GET /files/thirdparty.bin (10.42.42.42) 7079.96ms


passiert nix 10min gewartet, das müsste doch die verbindung abbrechen und das esp web hoochkommen

**Comment by moneybag** [comment]
Läuft jetzt, mehrfach versucht

**Comment by kurim** [comment]
@cljk, ich hab nun 6 SP111 geflashed ging bei allen problemfrei, einzig bei einem hatte ich mich selber ausgesperrt weil hinter dem AP Namen ein "Leerzeichen" war das mochte es gar nicht, den musste ich manuell via pin flashen.
