### ISSUE TITLE
Monoprice stitch doesn't take OTA

### ISSUE THREAD

**Issue by precision** [ct-Open-Source/tuya-convert#184]
I tried to use tuya-convert on a RasPi 3B+ to OTA flash the [Monoprice Stitch](https://www.monoprice.com/product?p_id=35557) light switch, however the switch never responds to smartconfig.

I ended up opening it up and soldering on some wires.  I thought you may be interested in taking a look at the firmware which is available [here](https://drive.google.com/open?id=1QYhni1n9OAmp9aPy5dhdx5UM0LKH9O0z).

**Comment by kueblc** [comment]
Thanks for your firmware backup, excellent!

**Comment by kueblc** [comment]
Happy to share that support for HTTPS firmware is in the works #279
