### ISSUE TITLE
Dnsmasq conflict with systemd-resolved on Lubuntu 18.04

### ISSUE THREAD

**Issue by fred9176** [ct-Open-Source/tuya-convert#187]
Hi,

When launching start_flash.sh on Lubuntu 18.04, I have an error in the log file :
Dnsmasq cannot strat because address is already in use.

And effectively, the port 53 is already used by systemd-resolved.

To solve this problem, I had to edit scripts/setup.asp and add the following line to /etc/dnsmasq.conf, juste after interface=$WLAN 👍
bind-interfaces
listen-address=10.42.42.1

This allowes Dnsmasq to start on a different IP than systemd-resolved.

Fred

**Comment by kueblc** [comment]
Great solution, thanks! I'll implement this when I have time, or if you'd like to make a pull request I'll merge it.

**Comment by ridale** [comment]
Tested this on Ubuntu 18.04 and flashed a tuya switch without any other modifications.
This also closes #152 
The only other issue on Ubuntu 18.04 is that there is no remove_ap.sh script to remove the unmanaged line from NetworkManager.conf to re-enable wifi. If I get time I'll write a teardown script or update the stop_flash script to return the system to its initial state.

**Comment by fsaris** [comment]
Tnx for this fix. 

After adding those 2 lines I was able to flash my NEO Coolcam plugs without any further issues on my Ubuntu 18.04 system.

**Comment by poerlemans** [comment]
Some clarification might be helpful.
The file ~/tuya-convert/scripts/setup_ap.sh has to be modified.
After the comment "# Interface to bind to " you will find the description given in the first post.
With a Lubuntu setup I flashed one Avatar smart plug after modification of setup_ap.sh-file.

**Comment by jcollie** [comment]
You can also add the following to `/etc/systemd/resolved.conf` to prevent `systemd-resolved` from listening on port 53.

    DNSStubListener=no

**Comment by Test-Automation-Engineer** [comment]
> Tested this on Ubuntu 18.04 and flashed a tuya switch without any other modifications.
> This also closes #152 and #157
> The only other issue on Ubuntu 18.04 is that NetworkManager.conf is not being restored by setup-ap.sh to re-enable wifi, i will check to see if the iptable entries are being removed as well.

I'm having the same issue with Ubuntu 18.04. Reboot doesn't restore my wifi-settings. Do you have a solution? Thanks

**Comment by kueblc** [comment]
@Test-Automation-Engineer should hopefully be fixed in #225

**Comment by fsaris** [comment]
Check of you have a file `etc/NetworkManager/NetworkManager.conf.backup` if not remove/backup `etc/NetworkManager/NetworkManager.conf` and restart network manager again.

That did the trick for me, default there was no conf file for me

**Comment by Test-Automation-Engineer** [comment]
That worked after rebooting the networkmanager service. Thank you!

**Comment by kueblc** [comment]
See #225

**Comment by kueblc** [comment]
If anyone is able to test #225 we can get this fix merged

**Comment by DonStefano** [comment]
I was able to flash 4 Teckin SP22 with the above described changes to setup_ap.sh. Also I had to copy back the backup of the NetworkManager configuration file.

**Comment by kueblc** [comment]
Closing as resolved by #225. Please provide feedback there. Thanks!
