### ISSUE TITLE
Esicoo Wi-Fi Smart Plug Outlet..no success

### ISSUE THREAD

**Issue by jesusvalverde** [ct-Open-Source/tuya-convert#189]
Try with the Esicoo Wi-Fi Smart Plug Outlet  [https://www.amazon.com/dp/B07DYMS1L3?pldnSite=1] . Seems to me a standar Tuya Outlet but no luck for me...Anyone ?

**Comment by kueblc** [comment]
_Please be sure to include your device **name, model, and firmware version** as well as your **logs**!_

**Comment by jesusvalverde** [comment]
Esicoo Wi-Fi Smart Plug Outlet [http://www.esicoo.com/index.php?route=product/product&path=60&product_id=94] 
firmware version :1.0.2 [Last Version]

[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/3129652/smarthack-web.log)
[smarthack-smartconfig.log](https://github.com/ct-Open-Source/tuya-convert/files/3129653/smarthack-smartconfig.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/3129654/smarthack-wifi.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/3129651/smarthack-mqtt.log)

**Comment by kueblc** [comment]
Can you confirm that the device is in pairing mode before running the script?

**Comment by jesusvalverde** [comment]
Yes ...The pulg makes a Wifi network named SmartLife-XXXX

**Comment by kueblc** [comment]
That's AP mode (blinking slowly), you need EZ config mode (blinking fast).

**Comment by jesusvalverde** [comment]
Also done that...Gonna done both modes and seend Logs.

**Comment by kueblc** [comment]
No need to try AP mode, it won't work

**Comment by jesusvalverde** [comment]
[smarthack-smartconfig.log](https://github.com/ct-Open-Source/tuya-convert/files/3132388/smarthack-smartconfig.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/3132389/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/3132390/smarthack-wifi.log)

No luck...
-Android phone as "men in the middle"
-Pi3b+ [wifi and cable]
-Plug on EZ mode blinking like 2 times/sec

The same config worked with other plug [Diferent brand]

**Comment by kueblc** [comment]
I see two devices in your WiFi log, is one of those the device you are trying to flash?

**Comment by jesusvalverde** [comment]
ec:fa:bc:22:5e:1a is the one  [Mac number match the app]

Found a model number under YX-WS01 for the Esicoo Wi-Fi Smart Plug Outlet

**Comment by kueblc** [comment]
Given the fact that you've been able to flash a different plug, and that the pairing process completed successfully (device connected to wifi) it looks like this device firmware has been patched and unfortunately will not work with tuya-convert.

**Comment by jesusvalverde** [comment]
Ok...too bad, but at least we can and the YX-WS01 Esicoo Wi-Fi Smart Plug Outlet as not compatible Over the Air.

**Comment by dachshund-digital** [comment]
I just got some of these Esicoo plugs and they do NOT establish a SmartLife AP, but provide some weird name.  Moreover, although the appears to be ESP based, they can't use the typical tuya smart app, but only seem to work with the 'cloud intelligence' app.  One more thing, the setup with the CI app, is inconsistent.  Where I can get a tuya smart plug to connect 90% on the first try, these new plugs I can't get more than 2 of the 4 to connect at all, and that took many retries.

**Comment by geoffoxholm** [comment]
I'm having the same experience as @dachshund-digital and @jesusvalverde - this device seems to have a firmware that does not allow EZ Config mode. Commenting here in hopes of saving others some time.

**Comment by dachshund-digital** [comment]
Or... the IC has changed to RealTek not ESP based, which I have also seen.  Either way the PSK issue, or IC variant issues, have broken tuya-convert.

**Comment by kueblc** [comment]
I have started work on support for AP config mode, please see #966 and feel free to leave feedback. @dachshund-digital @geoffoxholm

**Comment by dachshund-digital** [comment]
This is still specific to the ESP based devices right?  Or will it work on the none ESP based devices?  Will AP mode side setup the PSK issue?
