### ISSUE TITLE
OTA Flash not work for Fcmila Gu10 RGBW

### ISSUE THREAD

**Issue by fpries** [ct-Open-Source/tuya-convert#200]
Hello together,

the issue from my side, the device has the IP 10.42.42.**12** and did not get the ip 10.42.42.**42**, what maybe the result that the script can't  find the device and makes without stopping dot after dot …...

But step by step:

1. What i buy on JOOM "Belive-Gu10-RGBW-WiFi bulb".
http://www.joom.com/de/products/5cb7c9ea28fc710101dd83cd

2. What i got was the following "Fcmila Smart Spotlight".
![20190521_181454](https://user-images.githubusercontent.com/46075419/58118671-a5cd0880-7c01-11e9-9b58-4fac3fb90304.jpg)
  picture_1: the package box
![20190521_181527](https://user-images.githubusercontent.com/46075419/58118670-a5347200-7c01-11e9-8471-71decb256491.jpg)
  picture_2: the package box - socket Gu10 - 220V - multicolor
![20190521_181506](https://user-images.githubusercontent.com/46075419/58118672-a6659f00-7c01-11e9-954b-402601406d4d.jpg)
  picture_3: the package box - China lable
![20190521_181641](https://user-images.githubusercontent.com/46075419/58118814-f2b0df00-7c01-11e9-9f76-5d4bad8ac3af.jpg)
  picture_4: device - smart bulb RGBW 6W
![20190521_182721](https://user-images.githubusercontent.com/46075419/58118815-f2b0df00-7c01-11e9-8f8e-47fecd4cc719.jpg)
  picture_5: device - LED board - FL-M4 V2.4
![20190521_182733](https://user-images.githubusercontent.com/46075419/58118817-f3497580-7c01-11e9-9b8b-09293a860e30.jpg)
  picture_6: device - supply board
![20190521_182750](https://user-images.githubusercontent.com/46075419/58118818-f3497580-7c01-11e9-98d5-b6abbdddc6ed.jpg)
  picture_7: device - overview
![20190521_181620](https://user-images.githubusercontent.com/46075419/58118820-f3e20c00-7c01-11e9-966f-99b8b9028178.jpg)
  picture_8: assimilation mit supply

3. I tried to flash the device with a Raspberry Pi 3B+. 
    device is in quick flashing mode 
![20190521_rpi_3b_plus_tuya_convert](https://user-images.githubusercontent.com/46075419/58118880-14aa6180-7c02-11e9-9cab-343c6bdd91d1.JPG)
  picture_9: rpi_tuya_convert

4. I could collect the following log details:
4.a file mqtt.log
[20190521_smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/3203839/20190521_smarthack-mqtt.log)
4.b file smartconfig.log
[20190521_smarthack-smartconfig.log](https://github.com/ct-Open-Source/tuya-convert/files/3203844/20190521_smarthack-smartconfig.log)
4.c file web.log
[20190521_smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/3203850/20190521_smarthack-web.log)
4.d file WiFi.log
[20190521_smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/3203851/20190521_smarthack-wifi.log)

5. WirelessNetworkMonitor
![20190521_fcmila-ESP_2E8E2A_WirelessNetworkMonitor](https://user-images.githubusercontent.com/46075419/58119125-94d0c700-7c02-11e9-88a2-4cc00922974a.JPG)
  picture_10: WN-Monitor

This showes that the device get IP 10.42.42.**12**

6. SmartLife-8E2A as a Access Point 
    device in slow flashing mode  
![20190521_fcmila-ESP_2E8E2A-AP-Mode](https://user-images.githubusercontent.com/46075419/58124087-a9668c80-7c0d-11e9-9074-f58ca1e86ef4.JPG)
  picture_11: device in AP-Mode

I hope i give the right infos, someone can help to understood, what is going wrong and what could be the next steps ... 

best regards,
fpries

**Comment by probonopd** [comment]
Have you connected the light bulb to the app/the internet before flashing?

**Comment by fpries** [comment]
i did not use a smartlife app before, should i?

**Comment by probonopd** [comment]
No. Beware. Connecting the bulb to the app or to the internet will likely update its firmware and make it unflashable.

**Comment by dicko72** [comment]
Any update flashing these fcmila bulbs. I have the same issue.

**Comment by fpries** [comment]
Hello dicko72:

No, Sorry. At the moment it looks like that no one can help us with this bulbs.

The only thing i can report, that i try to do this:   
(https://community.openhab.org/t/step-by-step-guide-for-adding-tuya-bulbs-wi-fi-smart-led-smart-life-app-to-oh2-using-tuya-mqtt-js-by-agentk/59371)
But in that case, i do not get/find the tuya local key.

**Comment by kueblc** [comment]
> the issue from my side, the device has the IP 10.42.42.**12** and did not get the ip 10.42.42.**42**, what maybe the result that the script can't find the device and makes without stopping dot after dot …...

This means your device is not running the intermediate firmware; which as others stated is likely due to your firmware being patched. If you successfully install the intermediate firmware, the device will take `10.42.42.42`. In the meantime, stay tuned until we can release a workaround.
