### ISSUE TITLE
Is flash2 mandatory before flash3?

### ISSUE THREAD

**Issue by raghur** [ct-Open-Source/tuya-convert#203]
So I picked up a Wipro smart bulb (generic tuya ofcourse) and set up tuya convert on a Rpi2 with a ComFast usb dongle. It flashed the bulb successfully
```
curl: Saved to filename 'firmware-931a49.bin'
======================================================
Getting Info from IoT-device
VTRUST-FLASH 1.1
(c) VTRUST GMBH https://www.vtrust.de/35c3/
READ FLASH: http://10.42.42.42/backup
ChipID: 931a49
MAC: 84:0D:8E:93:1A:49
BootVersion: 4
BootMode: normal
FlashMode: 1M QIO @ 40MHz
FlashChipId: 1440c8
FlashChipRealSize: 1024K
Active Userspace: user2 0x81000

======================================================
Please make sure to note the correct SPI flash mode!
Installing an alternative firmware with the wrong flash mode will leave the ESP unable to boot!

Next steps:
1. To go back to the orginal software
   # curl http://10.42.42.42/undo

2. Be sure the conversion software runs in user2
   # curl http://10.42.42.42/flash2

3. Flash a third party firmware to the device
BE SURE THE FIRMWARE FITS THE DEVICE AND USES THE CORRECT FLASH MODE!
MAXIMUM SIZE IS 512KB
put or link it to ./files/thirdparty.bin
A basic build of Sonoff-Tasmota v6.5.0 is already included in this repository.
   # curl http://10.42.42.42/flash3
Alternatively let the device download and flash a file via HTTP:
   # curl http://10.42.42.42/flash3?url=http://10.42.42.1/files/thirdparty.bin
```

After this, I downloaded sonoff.bin 6.5.0, linked it to thirdparty.bin and ran `curl http://10.42.42.42/flash3`. This seemed to succeed since I got hte message that device will reboot after flash. Note that I did not do flash2 - the way I read it, it seemed optional - but apparently not. Post this, I saw the bulb advertise a `sonoff` ssid and saw the config page where I entered the AP and password. Once I hit save, things went south - now the bulb just blinks on and off on boot and there's no SSID and neither can I see it connecting to the vtrust-flash AP.
Rerunning ./start_flash also does not help... it just keeps waiting and does not take a flash. I cannot ping 10.42.42.42 either.

SHort of opening up the bulb and accessing serial pin header, is there anyway to unbrick this?

Also, if indeed `flash2` is a mandatory prep step for installing thirdparty fw, then can I suggest that the post install docs be clearer - like:
```
2. Install a third party firmware like Tasmota

2a. Prep - install flash2 to <purpose & benefit/use>. Also clarify if it's a one time activity or needs to be done each time.
2b. Flash - procedure for /flash3
```

**Comment by kueblc** [comment]
If you need to run `flash2` first, `flash3` will tell you this. There is no harm in running `flash2` if it's not needed, it won't do anything.

Since you successfully flashed Sonoff Tasmota, the issues you are now facing are with that. It sounds to me like you may have accidentally entered the wrong WiFi credentials. See the wiki or refer to Sonoff Tasmota for additional support.
