### ISSUE TITLE
Gosund WP3 Wiring for Flashing?

### ISSUE THREAD

**Issue by cheechie** [ct-Open-Source/tuya-convert#207]
Does anyone know what the wiring should be for the gosund WP3.  Do I have to hold GPIOZero to ground when I plug in the usbflasher to get this into programing mode?

![15592313290971](https://user-images.githubusercontent.com/49294767/58645279-0aa6f380-82d1-11e9-8dc8-d72779f69c64.jpg)
![15592313290650](https://user-images.githubusercontent.com/49294767/58645281-0aa6f380-82d1-11e9-81bc-fe09111c5a83.jpg)

**Comment by fyrmangeoff** [comment]
I just got some of these from Amazon. Was trying to OTA flash them not having any luck.  How did you get them apart?

**Comment by cheechie** [comment]
I just used some plumbers pliers and squeezed around the edge to put the seal loose.  I put some thin cardboard in between the pliers and the switch to not damage it.  It came apart really clean.  

![15593088014791](https://user-images.githubusercontent.com/49294767/58708367-94b09400-8385-11e9-8980-e7fadb9e92b4.jpg)

**Comment by 0xBiscuit** [comment]
Yes. I pulled the v5 firmware this way today. I had to remove the chip. You'll find a tx and rx pin along with 3v and ground. You need to pull the IO0 pin low in order to read or flash the firmware.

**Comment by cheechie** [comment]
I connected to the pins and flashed it with esphome.  It functions correctly.

**Comment by kueblc** [comment]
Glad to hear it; thanks @0xBiscuit for your input

**Comment by kymnyth** [comment]
Anybody care to share photos and instructions for flashing?  New to this and flashed some shelly's and did some TUYAConvert flashes but this will be my first attempt at soldering on connections for flashing.

**Comment by cheechie** [comment]
After opening it with the pliers like described above.  I used a small saw to cut across the bottom of the plug to remove a portion of the underside.  That gave me access to the pins to solder to.  Then after it was programmed, I used glue (crazy glue and epoxy) to seal it back up and close the gap from the saw.  I did not take pictures of the process. 

![wp3](https://user-images.githubusercontent.com/49294767/59852506-f177ec80-933c-11e9-8203-efd35fe88558.jpg)

**Comment by aage21** [comment]
Do you have any pics of the pins soldered?

**Comment by cheechie** [comment]
No I do not.  Sorry

**Comment by funkybluemonkey3** [comment]
So which side corresponds to the points that need to be soldered, top or bottom? 
<img width="458" alt="Annotation 2020-06-27 144016" src="https://user-images.githubusercontent.com/56159999/85930714-44577e80-b884-11ea-8796-8a83af22a292.png">

**Comment by cheechie** [comment]
> So which side corresponds to the points that need to be soldered, top or bottom?
> <img alt="Annotation 2020-06-27 144016" width="458" src="https://user-images.githubusercontent.com/56159999/85930714-44577e80-b884-11ea-8796-8a83af22a292.png">

I honestly don't remember. I think I used a multimeter to check for continuity to make sure I was connecting to the proper pins.

**Comment by kiprock** [comment]
Hey @cheechie did you have to pull the entire chip out? I connected to the pins and supplied voltage +3 from my pi but esptool won't connect to it. Thanks in advance for your response!!!

**Comment by cheechie** [comment]
> Hey @cheechie did you have to pull the entire chip out? I connected to the pins and supplied voltage +3 from my pi but esptool won't connect to it. Thanks in advance for your response!!!

I didn't pull the chip out.  I believe i solder to the pins.

**Comment by kiprock** [comment]
Thanks! Did you power it externally or from the host plug?

**Comment by cheechie** [comment]
> Thanks! Did you power it externally or from the host plug?

I powered with the programmer. Not the 120v

**Comment by kiprock** [comment]
For anyone else in this situation, I flashed mine using a pi and esptool. I had to use the host power (120V) instead of the 3v from the pi. I did not have to remove the chip. Thanks @cheechie for responding to my questions!

**Comment by Scope666** [comment]
Does anybody know what the pins are for this version?  I think it's a v2 but not positive.  It's definitely flashable because I've had both Tasmota and ESP Home on it.

<img width="707" alt="image" src="https://github.com/ct-Open-Source/tuya-convert/assets/31927547/bd2cf59a-5a3a-497c-964f-173c7400135f">

**Comment by SSzretter** [comment]
> Does anybody know what the pins are for this version? I think it's a v2 but not positive. It's definitely flashable because I've had both Tasmota and ESPHome on it. There's no labels at all on the daughter board and there's no exposed IO0 either. I made the mistake of trying to flash back from ESPHome to Tasmota via OTA. Said it was successful, but appears to be bricked. (No AP mode appearing)
> 
> <img alt="image" width="707" src="https://private-user-images.githubusercontent.com/31927547/328055941-bd2cf59a-5a3a-497c-964f-173c7400135f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQyNDY5NTMsIm5iZiI6MTc2NDI0NjY1MywicGF0aCI6Ii8zMTkyNzU0Ny8zMjgwNTU5NDEtYmQyY2Y1OWEtNWEzYS00OTdjLTk2NGYtMTczYzc0MDAxMzVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTI3VDEyMzA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhOWZhMjYxZmQ2ZDlmM2I4ZWRkY2ZmNTU1MDc3MjhjM2MzODk1M2Y0YWViY2IxODFmNzA5YTViY2RiMTVmNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QpsLZT7MZEI7bvVFbCOfHFk84B8ODZ3826DW385-8mQ"> <img alt="image" width="720" src="https://private-user-images.githubusercontent.com/31927547/328056059-070c6490-bf78-4f96-a3c9-43383a9361f3.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQyNDY5NTMsIm5iZiI6MTc2NDI0NjY1MywicGF0aCI6Ii8zMTkyNzU0Ny8zMjgwNTYwNTktMDcwYzY0OTAtYmY3OC00Zjk2LWEzYzktNDMzODNhOTM2MWYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTI3VDEyMzA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ZjQ4ZDRlNWI3MTQ2NmZmNTYxMjNlZDI2YzZhMDY1YzY2Y2JiODkwYzBlOThlOGNlYzgxNWJkNzczNDU2ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VV_1JISxrm__1IBlZxhA1C2i-iRc2Wqq4zRAN0GL8Bs"> <img alt="image" width="730" src="https://private-user-images.githubusercontent.com/31927547/328056094-7a0022b2-2d76-41ee-9329-336d4720c493.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQyNDY5NTMsIm5iZiI6MTc2NDI0NjY1MywicGF0aCI6Ii8zMTkyNzU0Ny8zMjgwNTYwOTQtN2EwMDIyYjItMmQ3Ni00MWVlLTkzMjktMzM2ZDQ3MjBjNDkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTI3VDEyMzA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyNWQ3YTlmMDZkZmY5YjFhNWMzNjVlMzNlZGY2ZTc0MDNhYzQ2ZTZhOWJiMGI2YzhlMWFhZGQzM2JmMmQ0OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FSYQvGcX4wAqNQafxl-tsa3ivHByVBeQO2yz_kYcqjQ">

Scope666 - I have the same type as this - did you ever figure out the type, pinout and if it can be flashed?

**Comment by Scope666** [comment]
> > Does anybody know what the pins are for this version? I think it's a v2 but not positive. It's definitely flashable because I've had both Tasmota and ESPHome on it. There's no labels at all on the daughter board and there's no exposed IO0 either. I made the mistake of trying to flash back from ESPHome to Tasmota via OTA. Said it was successful, but appears to be bricked. (No AP mode appearing)
> > 
> 
> Scope666 - I have the same type as this - did you ever figure out the type, pinout and if it can be flashed?

No, I'm still sitting on it, waiting for a rainy day if the pinouts every get published.
