### ISSUE TITLE
How to restore Raspberry Pi original wlan0 configuration?  Or backout SoftAP configuration?

### ISSUE THREAD

**Issue by dachshund-digital** [ct-Open-Source/tuya-convert#219]
How to restore Raspberry Pi original wlan0 configuration? Or backout SoftAP configuration?

**Comment by CaptClaude** [comment]
It was my experience that simply rebooting the Pi after running the flash scripts reverted it back to it's normal self. I may be wrong, but I don't think that the changes wrought by tuya-convert are permanent.

**Comment by kueblc** [comment]
Try rebooting as @CaptClaude suggested, otherwise you may wish to do a clean install on your SD card.
