### ISSUE TITLE
BN-LINK BNC-60/U133TJ-2P Power Monitoring Plug

### ISSUE THREAD

**Issue by darwin10** [ct-Open-Source/tuya-convert#224]
### Before opening a new issue, please read the following

**Are you reporting a successful flash?**
No firmware block

BN-LINK BNC-60 just purchased but appears to come with updated firmware (tuya convert ......, device blinks and goes solid but never finishes). The device is difficult to serial flash because the rx/tx lines need to be removed from the board connections (maybe the energy mon runs over those lines)

**Comment by kueblc** [comment]
Happy to share that support for HTTPS firmware is in the works #279
