### ISSUE TITLE
Could this be made to work with ArchLinux?

### ISSUE THREAD

**Issue by markg85** [ct-Open-Source/tuya-convert#233]
Hi,

I'm trying to give this a spin om some tuya switch, but i'm having trouble getting the scripts to work.

The current setup is very much tailored towards kali linux which makes it a bit cumbersome to use on a different distribution.

Also, it blindly expects networkmanager (which i don't use) and is changing actual settings in them. It does make backup files, but you should **not** do that! If you do, you should advise to run this on a live image or perhaps a docker container to not screw up host configuration.

Cheers,
Mark

**Edit:**
It's not even working on Ubuntu... Guess one debian based system (kali) isn't the other.

**Comment by kueblc** [comment]
> Also, it blindly expects networkmanager (which i don't use) and is changing actual settings in them. It does make backup files, but you should **not** do that! If you do, you should advise to run this on a live image or perhaps a docker container to not screw up host configuration.

It is already advised to use on a blank Raspberry Pi for this very reason.

You can try the `create-ap` fork, which is what I use on Ubuntu.

`git clone -b create-ap https://github.com/kueblc/tuya-convert.git`

**Comment by kueblc** [comment]
Closing as it has been addressed. Feel free to open a new issue if you have any other concerns. You may also want to look at #172 where @yoarch discusses `tuya-convert` on Arch.
