### ISSUE TITLE
BLITZWOLF SHP3

### ISSUE THREAD

**Issue by droidforever** [ct-Open-Source/tuya-convert#234]
I flashed Tuya-convert then Tasmota to a SHP3 Blitzwolf plug.  The flash went smoothly and I can toggle the unit on the Tasmota page.  But the unit, though showing "ON",  has no power.  Nothing I plug into it will work in either plug.  Did I flash this prematurely?  Is a working Tasmota flash not available for this plug?  If not, could I flash this with Espurna Sonoff dual? Thank you in advance for your answer.

**Comment by kueblc** [comment]
### Before opening a new issue, please read the following

**Do you have a question about configuring your newly flashed device?**
_Please ask in your alternative firmware's support channel instead!_
