### ISSUE TITLE
Support TLS/https and find a flaw in latest firmware to hack it

### ISSUE THREAD

**Issue by gstammw** [ct-Open-Source/tuya-convert#235]
Hello,

I'm aware that the current implementation uses a design flaw and the lack of TLS (https aka SSL-connection) in the device's firmware.
As new devices use an updated firmware that tries to connect to the cloud using https, tuya-convert in its current implementation cannot be used. This leads to the need for TLS support.
I'm sure that a nasty hacker can find a flaw in their implementation. Maybe we can fake a certificate or crack the one used by the vendor using an collision attack or something like that.
While it is unlikely that one will find a solution shorthand, the day will come...

Regards

**Comment by kueblc** [comment]
Duplicate of #223, #232
