### ISSUE TITLE
WiFi dimmer

### ISSUE THREAD

**Issue by thepuncake** [ct-Open-Source/tuya-convert#237]
I got this recently, couldn't get it to flash, something happened though as it will now refuse to go to pairing mode no matter what I try. This is the link: https://rover.ebay.com/rover/0/0/0?mpre=https%3A%2F%2Fwww.ebay.co.uk%2Fulk%2Fitm%2F223374832778
Got stuck at the loading dots for recognizing device. Any light shed would be amazing. Thanks!

**Comment by kueblc** [comment]
Please follow the template when opening a new issue.
