### ISSUE TITLE
Wifi Bulbs (CW, CW) Flashing Not Completed

### ISSUE THREAD

**Issue by Hollako** [ct-Open-Source/tuya-convert#238]
**Did you have issues getting a device to flash?**
Yes it's Wifi Smart Bulb CW and WW colors and the bulb stops blinking and it takes an IP address (not 10.42.42.42, but something else within the same range) then i only see dots without any progress on Putty (Picture Below). and the port 80 is not opened in the bulbs. Bulbs Firmware version is 1.2.0 and here is below the logs files.
[smarthack-smartconfig.log](https://github.com/ct-Open-Source/tuya-convert/files/3410496/smarthack-smartconfig.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/3410497/smarthack-mqtt.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/3410498/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/3410499/smarthack-wifi.log)

![Tuya Convert](https://user-images.githubusercontent.com/17670778/61526652-7b41d500-aa23-11e9-8ca6-8eaa15fce47e.png)

Thank you in advance !!

**Comment by kueblc** [comment]
Unfortunately the most likely culprit in this case is incompatible Tuya firmware.
