### ISSUE TITLE
NX-SM200 incompatible

### ISSUE THREAD

**Issue by Osmodia666** [ct-Open-Source/tuya-convert#239]
Hi, 
I commented the issue #67 with the problem, that the device doesn't get the specified IP address 10.42.42.42, it gets 10.42.42.16. 
Also, I did not connect a phone to the vtrust wifi, because if I do, the NX-SM200 can't connect. It only connects if I dont connect a android phone.

I edited the start_flash.sh and replaced every 10.42.42.42 with 10.42.42.16, but I get an error connection refused, so it doesn't work.

![2019-07-20 21 20 01](https://user-images.githubusercontent.com/36590357/61588974-427d3980-aba4-11e9-9b57-1b74874649b4.jpg)
![2019-07-20 21 19 58](https://user-images.githubusercontent.com/36590357/61588975-427d3980-aba4-11e9-8baa-501b6bd2be58.jpg)
![2019-07-20 21 19 54](https://user-images.githubusercontent.com/36590357/61588976-427d3980-aba4-11e9-8616-6b5411c4808c.jpg)

**Comment by kueblc** [comment]
If you did not get the address 10.42.42.42 that means the device did not flash, it is still running the Tuya firmware. Don't edit the IP in the scripts.

**Comment by kueblc** [comment]
Please follow the template when opening a new issue, we'll need to see your logs to help find the issue. Without looking the most likely is that you are running an incompatible firmware that can't be flashed OTA.

**Comment by enkol** [comment]
For me tuya-convert worked perfectly with two OxaOxe NX-SM200 plugs today.

**Comment by kueblc** [comment]
Great, thanks for confirming @enkol!
