### ISSUE TITLE
WiFi network never appears

### ISSUE THREAD

**Issue by jptrsn** [ct-Open-Source/tuya-convert#24]
I'm trying to use this project, but I get stuck at the step where I need to connect to the vtrust-flash network. Using a couple different phones and a couple different computers, I'm never able to see the network listed.

I've tried running tuya-convert on an rPi 3 as well as an old netbook running Ubuntu. Never see the wifi network appear on any device when I'm scanning.

**Comment by qingz2004** [comment]
I'm using Raspberry Pi 3 B+. I can't see the access pointer either.
Got the following messages.
![screenshot_3](https://user-images.githubusercontent.com/34905120/51796112-d4d6ee80-21ba-11e9-90c6-4881fda37c25.jpg)
![screenshot_4](https://user-images.githubusercontent.com/34905120/51796113-d7d1df00-21ba-11e9-8fa6-eed1f825c661.jpg)

**Comment by drushbrook** [comment]
When did you last do a git pull?

**Comment by qingz2004** [comment]
I did it today.
I will try the previous version.

**Comment by nanobyte84** [comment]
Make git pull again and it should work...Am 27.01.2019 04:15 schrieb ptrsnja <notifications@github.com>:I'm trying to use this project, but I get stuck at the step where I need to connect to the vtrust-flash network. Using a couple different phones and a couple different computers, I'm never able to see the network listed.
I've tried running tuya-convert on an rPi 3 as well as an old netbook running Ubuntu. Never see the wifi network appear on any device when I'm scanning.

**Comment by qingz2004** [comment]
The new script works now.
Thanks!

**Comment by drushbrook** [comment]
Have you tried WPA PSK?

**Comment by nanobyte84** [comment]
When you cannot enter the WIFI you probably need to use a different (usb) wifi adapter.
Which Hardware are you using?

**Comment by botak13** [comment]
I use an Lenovo Laptop with Linux Mint and an onboard Wifi Adapter.
After I have entered the Wifi Passwort my Phone tries to get an IP Adress from vtrust-flash but it doesnt work. When I use Static IP the Phone connects but I still cant flash my Device.

**Comment by qingz2004** [comment]
I was using Raspberry Pi 3 B+ build in WiFi adapter. It showed the access point, but could not connect to it.
After I added a Netgear USB WiFi adapter and change the config to wlan1, it worked.
Thanks!

**Comment by botak13** [comment]
hmm I dont have an usb WiFi Adapter to test.
What is the difference to an Onboard WiFi?

**Comment by jptrsn** [comment]
The latest version did not work, but checking out the commit before -Logfile option worked for me.

**Comment by kurim** [comment]
It did work with PI 3B+ (I only get it work with raspbian not with Kali!)
I've just remove everything from my SD Card to have a clear setup:

Raspberry Pi 3B+ & Raspbian Stretch (2018-11-13-raspbian-stretch-lite.img)
Do pre-setup because ssh is disabled by default you need to enable it first

> sudo apt update && apt update -y
> sudo apt install git
> git clone https://github.com/ct-Open-Source/tuya-convert
> cd tuya-convert
> ./install_prereq.sh
> ./start_flash.sh

Wifi was come up and is working fine.
![img_8780](https://user-images.githubusercontent.com/1880220/51858345-cdd3eb80-2334-11e9-92b4-c0688dd4adab.png) ![img_8781](https://user-images.githubusercontent.com/1880220/51858349-cf9daf00-2334-11e9-99e9-ea3ab06b243d.png)


Since I currently dont have any device to flash it stand still here:
![1](https://user-images.githubusercontent.com/1880220/51858490-25725700-2335-11e9-8e1a-3bfded030aea.JPG)

**Comment by Zefau** [comment]
Unfortunately, WiFi does not show up for me. I'm on the same system as kurim (Raspberry Pi 3B+ & Raspbian Stretch using 2018-11-13-raspbian-stretch-lite.img).

**Comment by kurim** [comment]
Thats strange.
It might not necessary but did you setup your wifi region? (raspi-config)

**Comment by Zefau** [comment]
Apparently I had the WiFi setup to connect to my home WiFi, which is why the scripts couldn't use it. I deleted the WiFi settings and the script works now.
Thanks

**Comment by geertvercamer** [comment]
started from scratch, didn't setup wifi, the network doesn't show. Reboot, nothing, set WiFi country, reboot, nothing...
Pi2B + usb wifi adapter

**Comment by Vendo232** [comment]
same on my end, I`m using HP laptop with built in WLAN and USB WLAN ( wlan1).
edited config.txt , tried fresh Kali, ubuntu, Mint install

can`t make the AP appear.

**Comment by plazomat** [comment]
How many places do you change the WLAN# and which files? Same issue here, Mint fresh install on IBM laptop.

**Comment by Vendo232** [comment]
> How many places do you change the WLAN# and which files? Same issue here, Mint fresh install on IBM laptop.

what worked for me was renaming WLAN0 from the random name Linux OS will assigned to WIFI module to wlan0 ( use command ifconfig)

I used this command

$ sudo nano /etc/default/grub
Look for GRUB_CMDLINE_LINUX and add the following net.ifnames=0 biosdevname=0.
From:
GRUB_CMDLINE_LINUX=""
To:
GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"
Generate a new grub file using the following command.
$ sudo grub-mkconfig -o /boot/grub/grub.cfg
Restart PC

**Comment by kueblc** [comment]
You can modify the interface in `config.txt`. I definitely do NOT recommend modifying your GRUB configuration for this.

**Comment by Vendo232** [comment]
> You can modify the interface in `config.txt`. I definitely do NOT recommend modifying your GRUB configuration for this.

I think if you setup a machine to one and only purpose ( flash TUYA devices ) the modification of GRUB should not be an issue. Besides you can revert the modification once you are done with flashing.

**Comment by plazomat** [comment]
Thanks - I will try with the just the config.txt modify to whatever ifconfig tells me the adapter is.

**Comment by plazomat** [comment]
If that don't work go after the GRUB file, right now the machine is only to flash tuya, it was a paperweight until tuya-convert..

**Comment by jptrsn** [comment]
Closing issue as my install worked. Please open a new issue for problems you encounter.

**Comment by ashfaaaa** [comment]
anyone found a fix for this issue? tried with both internal and external wifi adapter but vtrust-flash does not  show

**Comment by kueblc** [comment]
@ashfaaaa Please open a new issue with your logs and details about your problem and hardware
