### ISSUE TITLE
Binary dumps for Teckin 1.0.7 firmware

### ISSUE THREAD

**Issue by pquan** [ct-Open-Source/tuya-convert#243]
## Teckin SP22 (and SP23) 1.0.7 firmware attached below

Short story, I have a few SP22 devices in my home, and I'm buying more, so I'm a little afraid of the time when a new batch will come with a new firmware that cannot be used to convert to tasmota any more.

I updated one of my teckins to 1.0.7 and confirmed it is not flashable (as per https://github.com/ct-Open-Source/tuya-convert/issues/197)

In the hope that this will be useful for further analysis, I pried open the switch and after some solder-fu I downloaded the image of the last official update (attached below). Sorry about the size (1Mbyte) but I had no time to investigate further the real size of the flash.

After a few more minutes I uploaded tasmota the serial way and glued back the subject ;)

I hope somebody will be up to the task of finding a work-around. Good luck!

[teckin-fw-107.zip](https://github.com/ct-Open-Source/tuya-convert/files/3436331/teckin-fw-107.zip)

**Comment by kueblc** [comment]
Thank you @pquan, your efforts are very much appreciated! We'll add this to our collection of firmware samples.
