### ISSUE TITLE
Can't flash ZooZee SA101

### ISSUE THREAD

**Issue by jsunwalters** [ct-Open-Source/tuya-convert#246]
I am trying to flash a ZooZee SA101 I just got from Amazon.  I have had no issues getting the plug to connect to the vtrust-flash AP that is created on my Raspberry pi.  My first attempts though got stuck with the ....... waiting for the plug to answer a ping.  I discovered from /var/log/syslog that the ip address the plug is getting from dnsmasq is 10.42.42.26 and the start_flash.sh script assumes 10.42.42.42.  Looking at dnsmasq.conf I don't see how the plug would ever get 10.42.42.42 but I digress.  I modified start_flash.sh to use 10.42.42.26 and moved on.  I am also able  to connect my phone to vtrust-flash no problem.

Now when the start_flash.sh script tries to backup the existing firmware by calling curl http://10.42.42.26/backup it errors out with " curl: (7) Failed to connect to 10.42.42.26 port 80: Connection refused".  Trying to connect to anything port 80 gets that same error message.

************* log files *********************
cat *-mqtt.log
1564612844: mosquitto version 1.5.7 starting
1564612844: Using default config.
1564612844: Opening ipv4 listen socket on port 1883.
1564612844: Opening ipv6 listen socket on port 1883.

cat *-smartconfig.log
Put Device in Learn Mode! Sending SmartConfig Packets now
Sending SSID                  vtrust-flash
Sending wifiPassword          flashmeifyoucan
SmartConfig in progress
..........
SmartConfig complete.

cat *-web.log
Listening on port 80

cat *-wifi.log
Backing up NetworkManager.cfg...
Restarting NetworkManager...
Backing up /etc/dnsmasq.conf...
Writing dnsmasq config file...
Creating new /etc/dnsmasq.conf...
Writing hostapd config file...
Configuring AP interface...
Applying iptables rules...
Starting DNSMASQ server...
Starting AP on wlan0 in screen terminal...
Configuration file: /etc/hostapd/hostapd.conf
wlan0: Could not connect to kernel driver
Using interface wlan0 with hwaddr b8:27:eb:b9:a7:23 and ssid "vtrust-flash"
wlan0: interface state UNINITIALIZED->ENABLED
wlan0: AP-ENABLED
wlan0: STA 3c:71:bf:3f:c1:00 IEEE 802.11: associated
wlan0: AP-STA-CONNECTED 3c:71:bf:3f:c1:00 ( this is the ZooZee plug)
wlan0: STA 3c:71:bf:3f:c1:00 RADIUS: starting accounting session 2143DD30DEC39E91
wlan0: STA 3c:71:bf:3f:c1:00 WPA: pairwise key handshake completed (RSN)
wlan0: STA 8c:45:00:83:c7:d3 IEEE 802.11: associated
wlan0: AP-STA-CONNECTED 8c:45:00:83:c7:d3 (this is my smartphone)
wlan0: STA 8c:45:00:83:c7:d3 RADIUS: starting accounting session F26985DB85906DD2
wlan0: STA 8c:45:00:83:c7:d3 WPA: pairwise key handshake completed (RSN)

**Comment by kueblc** [comment]
Duplicate #245
