### ISSUE TITLE
VM Setup on MacOS

### ISSUE THREAD

**Issue by mkormendy** [ct-Open-Source/tuya-convert#257]
I have a macbook and I am unsure how to configure the VM on VirtualBox and the network settings on the macbook so I can allow the internal wifi adapter on the host macbook to act as the guest's wifi adapter.

Is this even possible?

**Comment by kueblc** [comment]
Should be possible, but I'm not the right person to answer this. Feel free to close this issue if this has been resolved.

**Comment by mkormendy** [comment]
Not resolved. I ended up pulling out an old Toshiba laptop and installed Kali on it.
