### ISSUE TITLE
Vtrust-Recovery

### ISSUE THREAD

**Issue by Mitimin94** [ct-Open-Source/tuya-convert#265]
Hallo,

habe alles so gemacht wie in der Anleitung jetzt hab ich aber folgendes problem:
die Wlan Birne hat sich verbunden mit dem tool hat auch irgendwas runtergeladen scheinbar,
aber jetzt öffnet die birne den wifi ap vtrust-recovery, habe das Problem natürlich auch gegoogelt aber bin leider zu keinem Ergebniss gekommen was mir wirklich weiter geholfen hat, deswegen jetzt auch die die letzte möglichkeit sich an euch zu wenden der ersteller der ganzen Sache

Mit freundlichen Grüßen Alexander Weber

**Comment by kueblc** [comment]
Seeing `vtrust-recovery` means that the intermediate firmware flashed successfully, but was unable to connect to `vtrust-flash`. Simply restart the device while `start_flash.sh` is still running and it should continue with the backup, after which you can continue on to flash custom firmware.

**Comment by kueblc** [comment]
Let us know if you have any more trouble
