### ISSUE TITLE
Lohas LH-ZN123-2-2700

### ISSUE THREAD

**Issue by EverythingSmartHome** [ct-Open-Source/tuya-convert#268]
Just another for information post, this time for the Lohas LH-ZN123-2-2700 E14 bulbs. These are single colour 2700k dimmable bulbs. 2 bulbs in the same box, one was on the latest firmware and not compatible with Tuya-Convert, one was on an older firmware and did work with Tuya-Convert. Soldering was easy, all pins on top side.

They use an MY9291 LED driver inside:
Data pin: GPIO13
Clock Pin: GPIO15

Output is on channel 0.

Hope this helps, took me a fair while to figure out the pinout!

**Comment by kueblc** [comment]
Thanks for your contribution, please add it to the wiki for others to find
