### ISSUE TITLE
Teckin SP22 - new Wifi module?

### ISSUE THREAD

**Issue by sknoche** [ct-Open-Source/tuya-convert#269]
Hi, 
after receiving a new batch of Teckin SP22 and failing to proceed with an OTA update, I opened one of the devices to flash them wired...

I was expecting to find a TYWE2S and connect DI0 to GND to enter flashing mode, 

Check for reference:
- https://github.com/arendst/Sonoff-Tasmota/wiki/CE-Smart-Home---LA-WF3-Wifi-Plug-(TYWE2S)

Instead I stumbled upon this chip:
![image](https://user-images.githubusercontent.com/1659609/64894917-4fd21400-d67b-11e9-9b33-8df31bf3b170.png)
![image](https://user-images.githubusercontent.com/1659609/64894928-59f41280-d67b-11e9-8e1b-9d7c9ba5e29d.png)

Does anyone know, which chip it is and if it's possible to flash them at all?

**Comment by kueblc** [comment]
I see `TYWE2S` silk screened off to the side in those images, I assume you saw these too. From the top picture it does look like it could still be the right chip. From left to right I see what looks like flash memory, ESP8266, and a crystal. Have you tried hooking up to it?

**Comment by sknoche** [comment]
I did, soldered TX, RX, 3v and GND... 
But I failed to locate IO0 to get into flashing mode.

**Comment by GeorgeIoak** [comment]
This document should help you locate IO0, https://fccid.io/2ANDL-TYWE2S/User-Manual/Users-Manual-3596121.pdf

**Comment by sknoche** [comment]
Thanks for the reference, but the schematics indicate a position of IO0 on the blank side of the chip (with the SP22 sticker attached).

![image](https://user-images.githubusercontent.com/1659609/64924523-d440a600-d7e5-11e9-8e1a-e7144fcb22b6.png)

I have absolutely no idea, how to proceed 😞

**Comment by kueblc** [comment]
Do you have better pictures to share?

**Comment by GeorgeIoak** [comment]
You have to solder a wire onto the IO0 test pad. Tx and Rx are not test points but pins on the module which might be a little difficult to access unless you can get the bottom side of the PCB that this is soldered into (the green PCB in your picture)
![2019-09-15 11 56 52](https://user-images.githubusercontent.com/1467145/64926396-a80b3200-d7b1-11e9-83cf-43ab728138b0.jpg)

Here's how I did it on a Gosund WP3. I was able to access Tx/Rx at a different spot on the board since I could get to the back side of the TYWE2S unless I removed it from the board

**Comment by sknoche** [comment]
![image](https://user-images.githubusercontent.com/1659609/64983582-21de1100-d8c1-11e9-9fff-a5fc573464e0.png)

This is a closer look at the backside of the "not-really-a-TYWE2S" :p

**Comment by GeorgeIoak** [comment]
Well the front side has full access to the ESP chip so you'll have to look at the pinout of the [ESP8285](https://www.espressif.com/sites/default/files/documentation/0a-esp8285_datasheet_en.pdf) which shows GPIO0 on pin15 and work from there

**Comment by sknoche** [comment]
I guess I'll not be able to solder these fine smd pinouts, I'll have to give it a pass :(. My soldering irons tip isn't even small enough to just touch a single pin 😂

**Comment by DonStefano** [comment]
This might be the new [WR2 WiFi Module](https://docs.tuya.com/docDetail?code=K8uhkbx75kg7y) which does not have an ESP chip.

**Comment by sknoche** [comment]
I can confirm it's not an ESP, but it seems to be the [WR3](https://docs.tuya.com/docDetail?code=K8uhkbxc5bqj7) instead of WR2, so I guess there is no way to flash tasmota :/...

So, I guess the newer versions of all Tuya devices will become more or less "unconvertable".

**Comment by sknoche** [comment]
Maybe I'll just get a couple of TYWE2S and change the module itself 😮

**Comment by meingraham** [comment]
@DonStefano can you double-check whether yours indeed is WR2?

**Comment by sknoche** [comment]
On mine the folowing details are (difficult to read though) printed:

W302
I119WR1 or T119WR1d
G113A6

**Comment by DonStefano** [comment]
I did not open it because I want to return it in case it does not work with Tasmota.

**Comment by meingraham** [comment]
Well, regardless of whether its a WR2 or WR3, it won't work with Tasmota. Only ESP82xx based Tuya modules work with Tasmota.

**Comment by kueblc** [comment]
Unfortunately if this is the case there's not much we can do. Thanks for sharing and documenting.

**Comment by henfri** [comment]
See https://github.com/ct-Open-Source/tuya-convert/issues/285#issuecomment-558850571

**Comment by omidjozani** [comment]
It's W302 wifi chip from Realtec and can not be flashed by Tasmota

**Comment by arannothc** [comment]
I bought 4x SP22 recently, they contain a RTL8710

![foto_no_exif (1)](https://user-images.githubusercontent.com/26854748/96466824-8a1cc600-122a-11eb-8adc-e91cf3d6d04c.jpg)
![foto_no_exif](https://user-images.githubusercontent.com/26854748/96466816-87ba6c00-122a-11eb-8377-08b0bb29f1d1.jpg)

I will come up with some solution to use Tasmota in theese Plugs... (Custom Chip or Re-Writing Tasmota to theese Chips) 

https://github.com/pvvx/RtlDuino

**Comment by formatBCE** [comment]
Any updates on this? Decided to flash all my Teckin sockets, and appears they all have new chip 👎

**Comment by Blackest-Nighthawk** [comment]
Sorry for re- opening this theme.

I found just one solution for this problem,
I bought some TYWE2S modules from AliExpress and here you can see the result.

![IMG_20221116_181604](https://user-images.githubusercontent.com/84148199/202255969-7fafdc38-c810-4225-bb62-e2e455c159cb.jpg)
![IMG_20221116_181553](https://user-images.githubusercontent.com/84148199/202256049-98d56609-d764-456e-84f1-4ff41dd56407.jpg)
![IMG_20221116_181705](https://user-images.githubusercontent.com/84148199/202256123-a4fbf4bb-3cd4-4617-9a41-78fe09117369.jpg)

For this you have to modify the bottom of the case a little bit.

![IMG_20221116_181832](https://user-images.githubusercontent.com/84148199/202256344-ed638d33-6188-44c4-bdeb-e44cada56584.jpg)

and this ist the adaption plan.
I can draw it clear if anyone is interested of this.

![IMG_20221116_184526](https://user-images.githubusercontent.com/84148199/202256951-c22b054b-a915-43d9-86ae-37e60a1d1236.jpg)

All in all not so beauty, I know but it works.
So you need around 30 - 45 min. for this swap.

**Comment by techman83** [comment]
@Blackest-Nighthawk - That looks like a TYWE2L pinout, are both sets of pins common? If so, I've been retro-fitting esp32-c3 chips into a bunch of my devices via these -> https://templates.blakadder.com/DT-ESP-C05.html

Close to drop in, generally all I've needed to do is a bit of a sand of the ends if the slot is a bit tight length wise.

**Comment by Blackest-Nighthawk** [comment]
@techman83 - I bought 12 peaces of SP-22. 4 peaces was with original TYWE2S, other 4 peaces was with the RTL8710 but with the pinout of TYWE2S. This was easy, I just put the new TYWE2S module into the device.
The last 4 peaces was with the completely different pin layout of the RTL8710 board. This is what  you can see on my photos.
So this was the easiest way for me.
The ESP-32 is very nice and powerful. I used this often for other projects.
Maybe you can poste the changed pin configuration for tasmaota. This is perhaps interesting for other user.
