### ISSUE TITLE
NEW Wi-Fi Module - Not Flashing

### ISSUE THREAD

**Issue by v-rejected** [ct-Open-Source/tuya-convert#270]
During the flashing the Device registers but after the registration everything stops.
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/3612942/smarthack-wifi.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/3612943/smarthack-mqtt.log)
[smarthack-smartconfig.log](https://github.com/ct-Open-Source/tuya-convert/files/3612944/smarthack-smartconfig.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/3612945/smarthack-web.log)
![69582340_506704873238233_1924668398315241472_n](https://user-images.githubusercontent.com/51052999/64911339-37b8ce00-d729-11e9-89f7-a2fe85047557.jpg)

**Comment by kueblc** [comment]
Unfortunately this device is running an unsupported firmware

**Comment by v-rejected** [comment]
Is it possible that this firmware will become supported in the future? What would be required of me that this firmware would become supported?
