### ISSUE TITLE
TreatLife Smart Switch 

### ISSUE THREAD

**Issue by skitzo2000** [ct-Open-Source/tuya-convert#271]
Recently purchased on of these on Amazon:  https://www.amazon.com/Treatlife-Smart-Light-Switch-Assistant/dp/B07R7PCCT9/

It exhibited the same symptoms reported by others, initial connect then disconnect without actually flashing.

I wanted to contribute, So I cracked mine open and soldered it to do a serial read using esptools.  And two quick questions:

A)  Did I do the dump right?
B)  Is there any other info you guys need before I commence with flashing to tasmota?

ESPtools output and file below:

`skitzo2000@skitzo-buntu:~$ ~/.local/bin/esptool.py read_flash 0x00000 0x400000 backup.img
esptool.py v2.7
Found 1 serial ports
Serial port /dev/ttyACM0
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: bc:dd:c2:40:08:b2
Uploading stub...
Running stub...
Stub running...
4194304 (100 %)
4194304 (100 %)
Read 4194304 bytes at 0x0 in 376.7 seconds (89.1 kbit/s)...
`
[backup.zip](https://github.com/ct-Open-Source/tuya-convert/files/3622168/backup.zip)

For additional details I also ran flash_id

`skitzo2000@skitzo-buntu:~$ ~/.local/bin/esptool.py flash_id
esptool.py v2.7
Found 1 serial ports
Serial port /dev/ttyACM0
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: bc:dd:c2:40:08:b2
Uploading stub...
Running stub...
Stub running...
Manufacturer: c8
Device: 4015
Detected flash size: 2MB
Hard resetting via RTS pin...
`

**Comment by kueblc** [comment]
Hi @skitzo2000, thanks for donating your firmware backup! It looks fine to me.

If you haven't seen yet, we're very close to officially supporting the new firmware update mechanism #273. Sorry you were just a day or two early!
