### ISSUE TITLE
Testing indicates Strech & Buster behave differently...

### ISSUE THREAD

**Issue by SirRedZ** [ct-Open-Source/tuya-convert#282]
I wanted to share my observations thus far regarding Tuya Convert (2) vs. Original (1) version.

This testing is also observed on the RPI platform, all things equal except the Stretch vs. Buster OS provided on the RPI site. My focus is using Proxmox; but I consider both sets of results identical at this point.

I have flashed dozens, maybe hundreds of times. I have at least 10 different devices (v1) and minimal (v2) only devices at this point. I feel I have a very good understanding of the process, not so much the technical side - moreso the what is supposed to happen and if it doesn't how to proceed.

My testing with the ```new-api``` brand of Tuya Convert has indicated with Proxmox Host O/S, 5.XX and Tuya 1.0 devices work best when operating under Debian Stretch. They are very consistent and simply work (using the new-api TC2 script)

On the other hand, ProxMox v 6.XX, and TC v2 devices insist on Buster template to be pulled.
Even when I tested using my ProMox v6.X environment, pulling Stretch template was far better at converting TC v1 devices, and pulling the Buster template, was far more successful for TC v2 devices. I have no idea how to explain this observation, but I wanted to share for all the people having difficulties- this *MAY* be a variable somehow that could be overlooked and preventing a successful Flash.

When I refer to template, I am referring to the ProxMox LXC container template of Stretch or Buster.

If anyone is using ProxMox, feel free to visit my gitHub (Master branch is Buster, Debian-stretch Branch is Stretch.

Please let me know your results. It takes a lot of data to prove/disprove theories, and make sure we have the correct information isolated. I have posted this only with the intention of learning, helping and further supporting this project.

https://github.com/SirRedZ/ProxMox-Tuya-Convert-2.0-Container 

[-=SrZ=-]

**Comment by kueblc** [comment]
Did you resolve this?

I made some changes in #225 would you be willing to test if this works cross platform?
