### ISSUE TITLE
Unable to install tuya convert

### ISSUE THREAD

**Issue by joyan14** [ct-Open-Source/tuya-convert#299]
Issue: unable to pass install_prereq.sh script:
message: "./install_prereq.sh: line 8: -H: command not found "

I went inside the file:
#!/bin/bash

set -e

apt-get update
apt-get upgrade -y
apt-get install -y dnsmasq hostapd screen curl python-pip python3-pip python-setuptools python3-setuptools python3-wheel python-dev python3-dev mosquit$
-H pip3 install paho-mqtt tornado git+https://github.com/M4dmartig4n/sslpsk.git pycrypto
-H pip2 install git+https://github.com/M4dmartig4n/sslpsk.git pycrypto

echo "Ready to start upgrade"
I passed line 8 by taking the -H out but i can't get through line 9. It seems like it got something to do with the pycrpto. I even tried to update python still did nothing.

Please help.
Thank you.

**Comment by kueblc** [comment]
Looks like this script has been edited to remove all the `sudo` commands, and the `-H` flag belonged to that `sudo`.
