### ISSUE TITLE
Tuya-Convert: WiFi doesn't appear

### ISSUE THREAD

**Issue by carl2298** [ct-Open-Source/tuya-convert#301]
I want to flash one of these chinese power strips with the help of tuya-convert but the WiFi doesn't appear. Because I don't have a Raspberry Pi I tried it with the Windows subsystem Ubuntu. And I'm using a USB-WiFi-Stick on my computer but normally that should work. Can anyone help me solve this issue? Or did anyone tried it with a subsystem and had success?

**Comment by scy0846** [comment]
try this. It worked for me

`git clone -b fix-net-inf https://github.com/kueblc/tuya-convert.git`

**Comment by carl2298** [comment]
Thank you. But it's still not working.

**Comment by scy0846** [comment]
Try using the development branch. It worked well for another issue I was
having but there may be a fix in it that will help you

**Comment by WaaZaa666** [comment]
I tried using WSL Ubuntu to no avail. I now have a Kali live USB, which I run to do the flashing..

**Comment by kueblc** [comment]
@carl2298 did you resolve this? Have you tried the `development` branch?

**Comment by carlzech** [comment]
I'm now trying it with a Raspberry Pi and a new WiFi-Stick. The WiFi does apppear but everytime I try to connect to the WiFi with my Smartphone the tool shows a lot of new lines and then the Raspberry Pi hang up. And I have to restart it because it's not responding to anything. I thought I made a mistake anywhere so I tried everthing again but I still have the same issue. The last two lines before it hang up: "Kernel panic - not syncing: Fatal exception in interrupt //// ---[ end Kernel panic - not syncing: Fatal exception in interrupt ]---" 
Can anyone help me with that?

**Comment by CaffeinatedFunctionality** [comment]
Did you use the development branch though? It may help

⁣Sent from BlueMail ​

**Comment by carlzech** [comment]
How do I use the development branch?

**Comment by cedricgrothues** [comment]
git clone -b development https://github.com/ct-Open-Source/tuya-convert/

**Comment by carlzech** [comment]
I now tried it with the development branch but it's still not working. Same problem... I'm using a Raspberry Pi 1 may this be a problem?

**Comment by carlzech** [comment]
I now tried it with the development branch but it's still not working. Same problem... I'm using a Raspberry Pi 1 could that be a problem?

**Comment by ivooovi** [comment]
I have the same problem although in the past it worked fine. But what I do is before running the ./start_flash command I do : sudo killall wpa_supplicant
This resolved it for me

**Comment by kueblc** [comment]
Please post your logs

**Comment by kueblc** [comment]
Closing while we wait for author to respond

**Comment by Bobofet682** [comment]
I have the same issue like carlzech.
After WLAN connect -> Kernel Panic and raspberry shows a lot of new lines and then the Raspberry hang up. The Raspberry wont responding to anything. No Keyboard input, no ping, no ssh, nothing.

What I have tested:
As well Developement as Master Branch.
New installed and Updated (and upgraded) Raspbian Buster Lite.
3 different USB WLAN Sticks tested.
Raspberry 2 Model B V1.1 (As well tested with Raspberry 1 Modell B+)

sudo killall wpa_supplicant does not fix the Problem

What can i do to help fixing the problem?

**Comment by carlzech** [comment]
Sorry for not responding so long. I was busy and didn't had the time to test anything. I now tried what @Bobofet682 said in the linked issue but it's still not working. Same issue as before...
