### ISSUE TITLE
RBG strip action

### ISSUE THREAD

**Issue by maffemuis** [ct-Open-Source/tuya-convert#304]
I have the RGB led strip from the Action.
And I can not firmware this true the tuya-convert 
So I solder it and get the firmware for you. I have more strips and need to do this true the air. Can you check the firmware why its not possible?

Firmware:

[RBGstrip_action_backup_01(1).zip](https://github.com/ct-Open-Source/tuya-convert/files/3707647/RBGstrip_action_backup_01.1.zip)

**Comment by maffemuis** [comment]
@Janghou If you are A girl I give you a Kiss :)
I make a new images with buster litle and Now its possible to flash!! Strange but i;m happy!!!! #bedankt

**Comment by kueblc** [comment]
Glad you have figured it out
