### ISSUE TITLE
Teckin sp22 tuyaconvert problem .................................

### ISSUE THREAD

**Issue by roberdlv** [ct-Open-Source/tuya-convert#310]
Hello friends, first of all congratulate on this great community.

Two days ago I bought 4 Teckin SP22 plugs on Amazon, I am trying to convert you https without success, I put the pairing mode (blue fast blinking) and I only get on the screen ............. ..........................

Say I have looked in the smart life app and version appears
Device: Teckin SP22
WIFI Firmware v1.0.1
MCU Firmware v1.0.1

Does this mean that I have a device from You or Realtek? Any way to know unopened? Any alternative to solve my problem? Or do I have to return to Amazon / Teckin? Thanks in advance, I put some images so you can see my screen as it is. Sorry for my English since I am from Spain and I use some translator.
![photo_2019-10-10_19-19-43](https://user-images.githubusercontent.com/56409767/66596747-b7598180-eb9d-11e9-9dc5-9d30b7881424.jpg)
![photo_2019-10-09_22-01-24](https://user-images.githubusercontent.com/56409767/66596748-b7598180-eb9d-11e9-95f4-997e3abbfdb8.jpg)
![photo_2019-10-10_18-29-29](https://user-images.githubusercontent.com/56409767/66596750-b7598180-eb9d-11e9-9e9d-d840fc0acba8.jpg)

Also say that when I press enter on the command line and teckin sp22 is flashing blue, it immediately turns off after entering and remains off.

If I do the same process but blinking purple / red, immediately after pressing enter on the command line then relay sounds and teckin sp22 goes off.

Logs:

[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/3714149/smarthack-wifi.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/3714150/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/3714151/smarthack-psk.log)
[smarthack-smartconfig.log](https://github.com/ct-Open-Source/tuya-convert/files/3714152/smarthack-smartconfig.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/3714153/smarthack-web.log)

Thanks for your time
@kueblc thanks

**Comment by kueblc** [comment]
Unfortunately this device is using a Realtek chip instead of ESP82xx, so you will not be able to run custom firmware, whether by `tuya-convert` or direct wire.

Also your `tuya-convert` is out of date, so if you have other devices to flash I recommend updating first.

**Comment by roberdlv** [comment]
oh, thanks ... how can you tell what realtek has? and how can i update yours convert? thank you!

Finally there is the same problem with the sp21? or these would be correct to buy and be able to make yours convert and not realtek. Thanks again @kueblc

**Comment by kueblc** [comment]
You can tell because it calls `/d.json` not `/gw.json` in your web log.

I do not know what the status of the SP21 is.

**Comment by kueblc** [comment]
To update, assuming you installed with `git`, do `git pull`.

If you did not install with `git`, you should.
`git clone https://github.com/ct-Open-Source/tuya-convert.git`

**Comment by roberdlv** [comment]
Thanks friend, I think I'm going to ask for Blitzwolf shp2 or shp8.  what do you think?

**Comment by roberdlv** [comment]
I tried to flash yours convert a hyleton 314 switch, I started putting ......... online commands and LED indicator plug is off, now the switch does not work, LED stays off and a Wi-Fi appears that puts vtrus recovery, which  have i done wrong?  How do I recover?

@kueblc

**Comment by kueblc** [comment]
Check "Troubleshooting" wiki page

**Comment by kueblc** [comment]
You need to configure the device, you can seek help for that from Sonoff-Tasmota

**Comment by roberdlv** [comment]
Sorry i can't understand, I put Wi-Fi configuration and Wi-Fi pass and now I am not able to enter the plug configuration again, the LED and button do not work and I cannot put ap mode.

@kueblc

**Comment by kueblc** [comment]
LEDs and button will do nothing until you configure it.

Check your router to see if the device has connected. Then you'll need to go to that IP address to finish configuration. I can't provide support for that, you'll need to seek help from Tasmota.

If it hasn't, you may have entered the wrong password. There is support for that in the wiki.

**Comment by roberdlv** [comment]
ok, this is solved, it was the router assigned mac with random ip.  I'm missing the part of running led and button I have only seen hyleton 313 I have set the same configuration but those gpios do not work

@kueblc thanks!!

**Comment by roberdlv** [comment]
The only problem I have now with the hyleton 314 after moving to Tasmota is that it does not work LED or button on manual off ... I have put the GPOI that puts on the page:

https://github.com/ct-Open-Source/tuya-convert/wiki/Compatible-devices-(HTTP-firmware)


Hyleton 314 | EU | wifi smart plug | HLT-314 | GPIO0 = LED2i, GPIO2 = LED1i,GPIO13 = Button1,GPIO15 = Relay1
-- | -- | -- | -- | --




But it doesn't solve the problem, I don't know what to do, if with ESPhome it would be solved or is there any other configuration? Thanks in advance.

thanks for all @kueblc

**Comment by roberdlv** [comment]
Is it possible to get correct GPOIS for HYLETON 314 EU? the ones on the page seem to be incorrect nothing works when you put them in and it is automatically restored to factory values ​​after ... Thanks

**Comment by kueblc** [comment]
@roberdlv yes it is possible to find the correct GPIO, but you need to seek support from Tasmota. I am a volunteer maintaining `tuya-convert` on my own time, I can not help with unrelated matters.

**Comment by roberdlv** [comment]
Thanks friend, I already managed to fix it GPIO was wrong.


I put the configuration that I managed to make work for if someone has HYLETON 314 can also solve their problem.

Thanks for everything.
![hyletonv1](https://user-images.githubusercontent.com/56409767/66719864-66dc6100-edf5-11e9-98fe-1b2f9089e1a6.jpg)
