### ISSUE TITLE
Actual list of flashable devices?

### ISSUE THREAD

**Issue by giddel** [ct-Open-Source/tuya-convert#311]
After I'd to send back my Teckin SP22 plugs I'm still looking for flashable plugs. On the Tasmota Wiki is my SP22 still listed - even it does no work anymore.
So I'm wondering if there is an actual  list with flashable devices based of the experience you made with the new development here. 
I don't want to by  new plugs to send them back again after unsuccessful flash sessions again.

**Comment by kueblc** [comment]
You can check the community maintained [compatible device list](https://github.com/ct-Open-Source/tuya-convert/wiki/Compatible-devices-(HTTPS-firmware)) on the wiki. We do not have any other list.
