### ISSUE TITLE
merkury mi-bw942-999w smart wifi dimmable bulb

### ISSUE THREAD

**Issue by or78rXxZ** [ct-Open-Source/tuya-convert#312]
### Before opening a new issue, please read the following

**Are you reporting a successful flash?**
_Please add it to the wiki instead!_

**Do you have a question about configuring your newly flashed device?**
_Please ask in your alternative firmware's support channel instead!_

**Did you have issues getting a device to flash?**
_Please be sure to include your device **name, model, and firmware version** as well as your **logs**!_

**Please remember to close your issue when the problem has been addressed!**

i used your scripts and followed the directions and flashed tasmota to this device without a hitch
thanks for all your work
i configured the network and connected to the web interface
i set the module as generic (18)
i tried gpios 2, 4, 5, 12, 13, 14, 15, 16 as pwm1 and relay1
in all cases the bulb would not switch on
someone at the tasmota site suggested i upgrade to the latest development firmware
i loaded the latest minimal firmware and it bricked the device
i decided to give up a take a look inside
the esp module has a part number tylc6e-kg
i searched and found no info for this
i just thought i would pass along this info in case anyone was interested

**Comment by kueblc** [comment]
I have this bulb and set GPIO5 as PWM1. Wonder what went wrong for you.

Closing as not a tuya-convert issue, but thanks for the report anyway.
