### ISSUE TITLE
To be discussed: Do we really need a whole system-upgrade in install_prereq.sh?

### ISSUE THREAD

**Issue by Cyber1000** [ct-Open-Source/tuya-convert#315]
Hi,

Just for discussion:
I'm unsure if it's a good idea to execute "sudo apt-get upgrade -y" within install_prereq.sh. Not everyone wants a full system upgrade just to install tuya-convert. Some users won't even look into this file and just excute it, which may lead to long execution time.

I would only state in the readme, that you should have a more or less uptodate system.

Thanks!

**Comment by kueblc** [comment]
This is a fair point, one I've considered myself. The fear is that out-of-date systems will lead to more frivolous bug reports. We can try it without for some time and see if it leads to an increase in issues. Thanks for your feedback.
