### ISSUE TITLE
1.bin source

### ISSUE THREAD

**Issue by kueblc** [ct-Open-Source/tuya-convert#32]
The ability to back up and undo is fantastic, great work. Do you plan on open sourcing 1.bin?

**Comment by merlinschumacher** [comment]
Any comment from @nanobyte84

**Comment by merlinschumacher** [comment]
The source has been published:
https://github.com/vtrust-de/esp8266-ota-flash-convert

**Comment by kueblc** [comment]
Excellent! Thank you so much!
