### ISSUE TITLE
Unable to flash Teckin SP21 with new Firmware 1.0.3

### ISSUE THREAD

**Issue by medicus07** [ct-Open-Source/tuya-convert#321]
Hi folks,

I used a new sd card with a fresh install of raspbian buster lite...
Everything worked fine, installation, script, vrtrust wifi... connected my iPhone. But I got no connection to the device.
Any idea? 
Are the change of #279 "Support for devices using the new TLS SDK" included in my Tuya-convert installation?

Thanks

[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/3745549/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/3745550/smarthack-psk.log)
[smarthack-smartconfig.log](https://github.com/ct-Open-Source/tuya-convert/files/3745551/smarthack-smartconfig.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/3745552/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/3745553/smarthack-wifi.log)

**Comment by kueblc** [comment]
In your web log
```
WARNING: it appears this device does not use an ESP82xx and therefore cannot install ESP based firmware
```

Unfortunately you won't be able to run ESP firmware on this device. See #269
