### ISSUE TITLE
Teckin SB50 just won't connect

### ISSUE THREAD

**Issue by tatsumara** [ct-Open-Source/tuya-convert#322]
I just can't get the SB50 to connect, at all.
I've been trying for hours now, sifting through every mention of this script i could find, with no success.
Hotspot is working, although for some reason the vtrust-flash network has a connection to the internet.

I'm using the script on an RPi 3B+ running DietPi.

Name: LED Smart Bulb
Device: Teckin SB50
Version: 1.0.5

[smarthack-smartconfig.log](https://github.com/ct-Open-Source/tuya-convert/files/3745698/smarthack-smartconfig.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/3745699/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/3745700/smarthack-wifi.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/3745701/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/3745702/smarthack-psk.log)

EDIT:
I can't confirm this, but the script seems to have killed another of the same bulb, my mistake may have been putting them both into pairing mode.

**Comment by kueblc** [comment]
Have you tried the `development` branch?

**Comment by tatsumara** [comment]
Development branch shows a lot more activity, but ends with"Device did not appear with the intermediate firmware".

**Comment by tatsumara** [comment]
Scratch all that, for some reason it has already flashed the Sonoff firmware and is working like expected!

**Comment by kueblc** [comment]
Happy to hear it!
