### ISSUE TITLE
New Teckin SP23 says device not supported

### ISSUE THREAD

**Issue by mikemod** [ct-Open-Source/tuya-convert#327]
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/3751100/smarthack-web.log)

Just bought new Teckin SP23 from Amazon, getting error that it does not use an ESP82xx when trying to run start_flash.sh

**Comment by kueblc** [comment]
Correct. We can't flash ESP firmware to a different microcontroller.
