### ISSUE TITLE
Does flash3 fully erase flash chip in current master build

### ISSUE THREAD

**Issue by magichew** [ct-Open-Source/tuya-convert#334]
Hi

I was reading https://github.com/ct-Open-Source/tuya-convert/issues/173#issuecomment-486824011 and there was a custom build posted up that would erase the full flash chip before flashing custom firmware.

I was wondering has that change been put in the latest master build or was it never added in?

**Comment by kueblc** [comment]
No @magichew, it was determined that the build erasing the entire flash while in `userspace 2` would crash and brick the device, so it was not integrated.

@Jason2866 is talking about Tasmota, not the intermediate firmware.

We could look at erasing the system param section, if it's causing trouble.
