### ISSUE TITLE
succesfully flashed BlitzWolf® BW-SHP6

### ISSUE THREAD

**Issue by Dunkelschunkel** [ct-Open-Source/tuya-convert#34]
Successfully flashed BlitzWolf® BW-SHP6 . Internally same as BlitzWolf® BW-SHP2 and Gosund-SP1. Espurna has working binaries. for  BW-SHP2 which can be flashed to the BW-SHP6.
Currently I have 4 BW-SHP6 working.

**Comment by merlinschumacher** [comment]
Thanks for your feedback!
