### ISSUE TITLE
How reliable is the warning "this device does not use an ESP82xx"

### ISSUE THREAD

**Issue by redge76** [ct-Open-Source/tuya-convert#341]
Hi,

I just bougth 2 Zoozee SE131 ( https://blakadder.github.io/templates/zoozee_SE131.html )
I get the message "WARNING: it appears this device does not use an ESP82xx and therefore cannot install ESP based firmware" in smarthack-web.log.
How reliable is this warning ? If it's100%, I wont try to open my smartplus and I'll send it back. (the cover is glued so I'll be somewhat destructive)
It looks that the WR3 has claimed another device.

**Comment by kueblc** [comment]
That warning is produced when the `gwId` is not included in an API call, it seems to be a pretty reliable indication but I can't guarantee it.

Fortunately for the manufacturer and rather unfortunately for us, the WR3 seems to be pinout compatible and the Tuya SDK supports both, so they can switch over fairly quickly. It seems like this is Tuya's response to their broken security, don't fix it, just replace it.

I would assume it is a WR3 and send it back personally, but if you do decide to open it please let us know what you find inside.
