### ISSUE TITLE
Safe to update Tasmota to 6.7 via the built-in updater?

### ISSUE THREAD

**Issue by blautob** [ct-Open-Source/tuya-convert#352]
Just wondering if it is safe to update Tasmota to 6.7 via the built-in updater.
I flashed several devices and ran the curl http://10.42.42.42/flash3 command only.

**Comment by kueblc** [comment]
`tuya-convert` doesn't have a built in updater, I believe this is a Tasmota question. I don't see why it wouldn't work though.

**Comment by blautob** [comment]
Thanks. I was just wondering if i need to keep something in mind due to available sizes of the space on the device...
