### ISSUE TITLE
Warning : Unable to flash Teckin SP27

### ISSUE THREAD

**Issue by danmed** [ct-Open-Source/tuya-convert#364]
Trying to flash these new out of the box Teckin SP27 plugs (UK) they seem to connect to vtrust, the LED goes solid but then nothing happens.

Looking in the web logs

"WARNING: it appears this device does not use an ESP82xx and therefore cannot install ESP based firmware"

Just PSA more than anything else :(

**Comment by kueblc** [comment]
Thanks for reporting @danmed, best to add this to [the wiki](https://github.com/ct-Open-Source/tuya-convert/wiki/Compatible-devices-(HTTPS-firmware))
