### ISSUE TITLE
install_prereq.sh fails without git

### ISSUE THREAD

**Issue by R0Wi** [ct-Open-Source/tuya-convert#367]
I forgot to install git by mistake which leads to an error when executing `install_prereq.sh`.

```
Collecting git+https://github.com/M4dmartig4n/sslpsk.git
  Cloning https://github.com/M4dmartig4n/sslpsk.git to /tmp/pip-y3xpo6p8-build
  Error [Errno 2] No such file or directory: 'git' while executing command git clone -q https://github.com/M4dmartig4n/sslpsk.git /tmp/pip-y3xpo6p8-build
Cannot find command 'git'

```

**Comment by kueblc** [comment]
You need `git` to install `tuya-convert` as described in the README

**Comment by R0Wi** [comment]
Ok but what's wrong with adding it to the script?

**Comment by kueblc** [comment]
If you're following [the installation instructions from the README](https://github.com/ct-Open-Source/tuya-convert#installation) you shouldn't be getting this error

**Comment by R0Wi** [comment]
@kueblc i also noticed that in my debian distro the  `iw`-command was missing. So would it be good to add this package too?

**Comment by kueblc** [comment]
Interesting, I thought this was a standard utility. What system are you running?

**Comment by R0Wi** [comment]
Well i'm running OSMC on my raspberry pi  and i was too lazy to load a standard raspbian just for flashing tasmota :-) OSMC is currently based on Debian 9 but seems to lack the `iw`-package.
