### ISSUE TITLE
Wireless interface isn't named "wlan0"

### ISSUE THREAD

**Issue by SteveDinn** [ct-Open-Source/tuya-convert#37]
Never mind.. I'm dumb. Just look in config.txt!

-----

I'm attempting to run this script on a Linux Mint 18.3 laptop. It doesn't have a "wlan0" wireless interface. Instead, it's called "wlp2s0". The scripts seem to be inferring or assuming that my interface is "wlan0". I've tried hacking a few scripts to set the $WLAN variable, but I still get this when attempting to actually flash.
```
======================================================
Starting pairing procedure in screen
Cannot find device "wlan0"
```

With my hacked-in variable, the log file looks much better and references the correct interface, but it still won't flash. Where does the script come up with "wlan0"? I can't find out where it gets this name from.

**Comment by merlinschumacher** [comment]
Edit config.txt and change it accordingly.

**Comment by SteveDinn** [comment]
Hah. Thanks. I was grepping through *.sh and *.py.

**Comment by merlinschumacher** [comment]
Maybe we should make that clearer in the description.
