### ISSUE TITLE
Teckin SP10 v.1.0.3 - From Amazon.ca - Not using ESP82XX

### ISSUE THREAD

**Issue by Zethirdone** [ct-Open-Source/tuya-convert#370]
Not sure if I should report this here since I don't hope on a fix...

Just bought a pack of two Teckin SP10 from amazon and they appear to not be using ESP82XX.

I got this warning from my logfile:
WARNING: it appears this device does not use an ESP82xx and therefore cannot install ESP based firmware

Can't confirm from opening it because I will return it.

Going back to shopping..

thank you

**Comment by kueblc** [comment]
Thanks for reporting, please add it to [the wiki](https://github.com/ct-Open-Source/tuya-convert/wiki/Compatible-devices-(HTTPS-firmware))
