### ISSUE TITLE
Bricked SP22 by interrupting after flash2

### ISSUE THREAD

**Issue by willamowius** [ct-Open-Source/tuya-convert#374]
I bricked an SP22 by interrupting the flashing process after

`# curl http://10.42.42.42/flash2
`

The device was rebooted before doing `flash3`. Now the LED doesn't blink, when after pressing the button a long time.

Is there a way to revive the device ?

**Comment by kueblc** [comment]
Check [Troubleshooting](https://github.com/ct-Open-Source/tuya-convert/wiki/Troubleshooting) "appears bricked"

**Comment by willamowius** [comment]
Recovered. Thanks!
