### ISSUE TITLE
WLAN Bad password

### ISSUE THREAD

**Issue by moneybag** [ct-Open-Source/tuya-convert#38]
i checked with 2 different devices, newest git.
changed ssid, password in the config.txt
client device (iphone, notebook) says : bad password
using kali-linux to flash

**Comment by kurim** [comment]
Hello,
what did you use as a host device?

**Comment by moneybag** [comment]
Rasp 3b+

**Comment by smarthomecoder** [comment]
I had the same problem. Try to connect rasp3b+ only via Ethernet. That worked for me.

**Comment by kurim** [comment]
Ok how about this way on RPI 3b+:
https://github.com/ct-Open-Source/tuya-convert/issues/24#issuecomment-458252537

May be it is important if you are working headless that you have connect LAN to your Router and leave wifi not set

**Comment by moneybag** [comment]
an additional WLAN USB adapter was the solution. It worked!
thx
