### ISSUE TITLE
Add unplugging devices to instructions 

### ISSUE THREAD

**Issue by Stooovie** [ct-Open-Source/tuya-convert#385]
Hello,

I propose adding to instructions that it's necessary to unplug any devices from the device that is being flashed. Seems obvious but it's easy to forget, especially if there are other warnings in the instructions. 

In my case, with default Tasmota firmware end, after setting the correct profile (Digoo DG-SP202) and clicking Save, the device rebooted and right after hearing the two relays, it blew the fuse in the fuse box and apparently also in itself. The device is now dead.

Thanks.

**Comment by kueblc** [comment]
Done. Sorry to hear about your blown fuses! Better luck next time
