### ISSUE TITLE
SP22 | not flashable anymore ?

### ISSUE THREAD

**Issue by Snotmann** [ct-Open-Source/tuya-convert#391]
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/3843142/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/3843143/smarthack-psk.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/3843144/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/3843145/smarthack-wifi.log)

The device is connected to my raspberry fine on vtrust-flash wifi so far.
The device got ? (10.42.42.32) auf 68:57:2d:3b:f3:f6 [ether] auf wlan0 as IP.

But in flashing tool I got :

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 10.42.42.32 port 80: connection refused.

Is this happen to a newer firmware ? Version is 1.0.1 as the app told me.
I never got the devices connected to the internet so far or android app

Snot

**Comment by kueblc** [comment]
Unfortunately this device does not use an ESP82xx chip so you won't be able to install Tasmota, Espurna, etc. From your web log:
```
WARNING: it appears this device does not use an ESP82xx and therefore cannot install ESP based firmware
```
See #269
