### ISSUE TITLE
Unable to flash Maxcio power plug

### ISSUE THREAD

**Issue by giacomofabbri** [ct-Open-Source/tuya-convert#392]
**Did you have issues getting a device to flash?**
_Please be sure to include your device **name, model, and firmware version** as well as your **logs**!_
Maxcio power plug 16A Here's the link:[Amazon](https://www.amazon.it/Maxcio-Intelligente-Compatibile-Telecomando-Condividere/dp/B07VS1472C/ref=pd_sbs_60_3/261-3153510-0722447?_encoding=UTF8&pd_rd_i=B07VS1472C&pd_rd_r=d57442b8-c093-4d27-a101-7e91d68ad281&pd_rd_w=nTGp8&pd_rd_wg=UyBVl&pf_rd_p=fbcaa110-7762-4ba4-93f0-28dd164e130c&pf_rd_r=CDFGVT39TXCB1HM8JN96&psc=1&refRID=CDFGVT39TXCB1HM8JN96)
**Please remember to close your issue when the problem has been addressed!**
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/3843587/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/3843588/smarthack-psk.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/3843589/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/3843590/smarthack-wifi.log)

Here's some photos 
![IMG_0328](https://user-images.githubusercontent.com/17236751/68806838-faa88380-0666-11ea-8710-84eb0c371534.jpg)
![IMG_0329](https://user-images.githubusercontent.com/17236751/68806839-faa88380-0666-11ea-921d-fb662e13d730.jpg)
![IMG_0330](https://user-images.githubusercontent.com/17236751/68806840-faa88380-0666-11ea-8bd1-690ec69036ad.jpg)
![IMG_0331](https://user-images.githubusercontent.com/17236751/68806841-fb411a00-0666-11ea-98e7-e445b739b2c6.jpg)

Let me know if you need anything, I would love to Tasmotize this device, thanks!

**Comment by kueblc** [comment]
From your web log:
```
WARNING: it appears this device does not use an ESP82xx and therefore cannot install ESP based firmware
```
Unfortunately you won't be able to install Tasmota on this device.
