### ISSUE TITLE
Cannot flash SCW NF101 switch

### ISSUE THREAD

**Issue by eku** [ct-Open-Source/tuya-convert#399]
**Did you have issues getting a device to flash?**

I was not able to flash a [SCW NF101 switch](https://de.aliexpress.com/i/32963170549.htmll). It reacts on the Smart Wifi sequence, stopps flashing the LED and connects to the AP. That's all. Nothing more in the logs.

MAC is ```68:57:2d:13:12:be```.

![IMG_20190711_062355](https://user-images.githubusercontent.com/418685/69008337-91b45a80-0949-11ea-890c-275686b90a01.jpg)
![IMG_20191117_142412_HHT](https://user-images.githubusercontent.com/418685/69008349-ac86cf00-0949-11ea-85ac-658020301f4b.jpg)
![IMG_20191117_143536_HHT](https://user-images.githubusercontent.com/418685/69008357-bc9eae80-0949-11ea-93b2-36b92b992073.jpg)
![IMG_20191117_143549_HHT](https://user-images.githubusercontent.com/418685/69008364-c7f1da00-0949-11ea-9871-a5f17a6eec5d.jpg)

**Comment by kueblc** [comment]
Need more information. Can't help without your logs.

**Comment by eku** [comment]
@kueblc as I wrote no logs at all beside the lines from starting the tuya-convert components.

**Comment by kueblc** [comment]
Sorry I can't help much if I have nothing to go on. Try to make sure all the services started properly.

Are you sure this device contains an ESP82xx? I don't see one in the pictures you shared. I don't recognize the chip in the second picture.

**Comment by kueblc** [comment]
[From the MAC address](https://aruljohn.com/mac/68572D) it does not look like an Espressif device, so we can't install ESP firmware.

**Comment by eku** [comment]
Then I guess that's a bad buy. Thank you for your support.

**Comment by kueblc** [comment]
You're welcome, sorry it didn't work out. Hope you can exchange these for something more hackable!
