### ISSUE TITLE
Question on versions of tasmota versions included with latest tuya-convert

### ISSUE THREAD

**Issue by proludiojon** [ct-Open-Source/tuya-convert#410]
I noticed last night when I redid my Raspberry pi that tuya-convert is Currently including a Tasmota v7.0.0.3.  And you can update to a current version when completed.  According to the Tasmota site, the current released version is 6.7.1, and the 7.x is the develop branch.

Is this switch done because tuya-convert feels the develop branch is complete enough to become the main release?  Or is there some other reason?

Note, the 4 I did today work just fine on the 7.0 install, and I would not have even noticed had the web screen not switched to black.

**Comment by kueblc** [comment]
Tasmota v7.0.0.3 was included via #376 

@meingraham explains [in this comment](https://github.com/ct-Open-Source/tuya-convert/pull/294#issuecomment-538737273) how the `development` branch is stable and preferred over `master`, which has bugs that are resolved in `development`. `experimental` is the unstable branch in the Tasmota project.

Similarly, tuya-convert `development` branch is more or less stable. Merge to `master` is done after a batch of PRs has been tested and no regressions become apparent.
