### ISSUE TITLE
Video walk through is available for use. 

### ISSUE THREAD

**Issue by digiblur** [ct-Open-Source/tuya-convert#42]
I did a video walk through of the entire process of a blank SD card to a flashed Tasmota device. This might help cut down on some of the issues people are having as more and more people try the process out.

https://youtu.be/O5GYh470m5k

Edit: Livestream where I showed how to setup two plugs and figure out the in's and out's of things of what pins go to which switches/buttons/relays etc..

https://www.youtube.com/watch?v=m_O24tTzv8g

**Comment by ragenhe** [comment]
I for one was led here by your video. Thanks for putting it together.

**Comment by scfigg** [comment]
Agreed - I came here from your video.

In the event of a SSID change, is there any way to get back into Tasmota to configure settings? Haven't run into the issue now. Just wondering for the future.

**Comment by digiblur** [comment]
If you configure the your button as a button correctly then yes you can do a 4 button press to pull up the AP again which it might already be in if it can't connect to the SSID. You can also do a 40 second hold as well. Or worse comes to worse but in a backup SSID and password in the AP2 position.

**Comment by scfigg** [comment]
Awesome, good to know. Just trying to figure out what switches are compatible and what I should buy before they patch this :)

**Comment by digiblur** [comment]
Seems most I have heard from are having success.

**Comment by digiblur** [comment]
Livestream where I showed how to setup two plugs and figure out the in's and out's of things of what pins go to which switches/buttons/relays etc..

https://www.youtube.com/watch?v=m_O24tTzv8g

**Comment by kueblc** [comment]
Created a [wiki page](https://github.com/ct-Open-Source/tuya-convert/wiki/Additional-Resources) to host these sorts of things, feel free to edit and add
