### ISSUE TITLE
Configuring the MQQT and might have bricked it

### ISSUE THREAD

**Issue by madilla** [ct-Open-Source/tuya-convert#421]
I flashed tasmota 7.0.0 into a MPV2RO-US, everything is going great. 
I can connect to it through its local IP. I changed the configuration on generic(18) and when I click toggle, I hear the click the plug does. Now when I go to configure the MQQT to connect to the MQQT broker I have running on my HASS.io. My MQQT broker is running fine on my Hass.io, it has login auth so I entered the Hass.io local ip, the username, password and a topic to the mqqt parameters and hit save. After a moment, I lose connection through the local ip to the mpv2ro plug. Its not connected to my wifi at all. Using the button on the side of the plug does nothing. Has this been bricked? I have no logs, useless you want to see that the mqqt broker is running. (Sorry if this is the wrong place to post this)

**Comment by kueblc** [comment]
Hi @madilla, sorry to hear you're having issues with Tasmota. I suggest seeking support from [the Tasmota community](https://github.com/arendst/Tasmota) since this is not a `tuya-convert` issue. Good luck!

**Comment by madilla** [comment]
thank you!
