### ISSUE TITLE
Teckin SP23 - does not use an ESP82xx

### ISSUE THREAD

**Issue by matbrewer396** [ct-Open-Source/tuya-convert#425]
I bought another couple of teckin SP23 smart plug, I keep getting this error:

`WARNING: it appears this device does not use an ESP82xx and therefore cannot install ESP based firmware`

The model is SP23 on the back of plug too but does look a little different compared to the ones I got and successfully flashed a few months ago. 

Have they stopped using a ESP82 chip?

**Comment by kueblc** [comment]
Yes

Duplicate of #269 #310 #321 #327 #341 #364 #370 #380 #391

**Comment by tyjtyj** [comment]
There is 2 version SP23. the flat on plug side flashable to tasmota. the one with UK plug shape does not
