### ISSUE TITLE
Try to Flash switch but get: decryption failed or bad record mac

### ISSUE THREAD

**Issue by Maekes** [ct-Open-Source/tuya-convert#429]
Hello,
i today get my new switches from nooie [https://www.amazon.de/dp/B07V47PJWX](https://www.amazon.de/dp/B07V47PJWX )
Like someone mentioned, they can be flashed OTA. I tried it with my RPi, wir an used and a brand new system, but it doesn´t work. These are my Logs:

[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/3906569/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/3906570/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/3906571/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/3906572/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/3906573/smarthack-wifi.log)

The switch stops flashing, after hitting Enter, but then this happens and nothing more.

```
Sending SSID                  vtrust-flash
Sending wifiPassword          
Sending token                 00000000
Sending secret                0101
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................

****loops over and over again***

SmartConfig complete.
Resending SmartConfig Packets
..............
Device did not appear with the intermediate firmware
Check the *.log files in the scripts folder
Do you want to try flashing another device? [y/N] n
```

 I tried some ideas from fixed issues, but nothing helped...

**Comment by kueblc** [comment]
Unfortunately from the udp log I can tell it is likely that this device is not running on the ESP82xx and therefor you won't be able to install firmware like Tasmota which is built only for the ESP.
