### ISSUE TITLE
Bricked device on upgrade?

### ISSUE THREAD

**Issue by smekre** [ct-Open-Source/tuya-convert#434]
Hi,
I am completely new to home automation and coding. I have a set of smart outlets which I have flashed with tasmota using tuya convert. However, when I tried to flash another of the exact same outlet, it seems to have been bricked. I followed the steps exactly like before, it succefully flashed tasmota. When i tried to OTA upgrade, it restarted and i got the message "minimal firmware". I did the OTA firmware again, and after that the device is completely dead. The LED does not work, it is not connected to my wifi. Is there anything one can do to recover this? 

The device is a Neo WiFi smart plug, EU version, 10A.

**Comment by kueblc** [comment]
Sorry, we do not develop Tasmota, you will have to go through their support channels for help.
