### ISSUE TITLE
Successfully flashed Hama 176533

### ISSUE THREAD

**Issue by danielperna84** [ct-Open-Source/tuya-convert#44]
Successfully flashed Tasmota onto Hama 176533, which is a 16A socket outlet.
~~With the Sonoff Basic module configuration everything works fine, except the button on the device has no function.~~

~~I have tried some other profiles. When using `ESP Switch (50)` the button does toggle on and off. But the state is inverted, and besides that this profile seems to provide 4 toggles in the UI. The 4. one is the one that reacts (inverted). I think this might be the relevant code in Tasmota: https://github.com/arendst/Sonoff-Tasmota/blob/dc75b473cff67320292eb8e3e7e5830e2b5850b1/sonoff/sonoff_template.h#L1474~~

~~Does this information help to get the device fully functional? Which other steps can I take to provide more useful information?~~

This is how it has to be configured as a Generic Module:
![hama](https://user-images.githubusercontent.com/7396998/51874763-8fedbc00-2362-11e9-8610-6dcbe93e056f.png)

**Comment by merlinschumacher** [comment]
Thanks for your feedback!
