### ISSUE TITLE
Tuya camera support?

### ISSUE THREAD

**Issue by orrpan** [ct-Open-Source/tuya-convert#440]
Would it be possible to flash the tuya-camera? Like this https://h5.aliexpress.com/item/32973584717.html 
Can’t find any info about it, and no supporting firmware. Has anyone else tested this? Thinking of buying one just to test

**Comment by kueblc** [comment]
Very unlikely. All of the Tuya cameras I have seen do not use an ESP82xx. It would need to be something more powerful to handle streaming video.

**Comment by orrpan** [comment]
@kueblc okey to bad, was only thinking they use the same apps and cloud service (ex deltaco). Are there not esp32 with cameras?

**Comment by kueblc** [comment]
tuya-convert only supports ESP82xx devices, not the ESP32
