### ISSUE TITLE
List of supported/working WiFi Sticks?

### ISSUE THREAD

**Issue by dervitti** [ct-Open-Source/tuya-convert#445]
Hey,
apparently I am unable to buy an AP mode capable USB WIFI stick.
I tried a 0bda:8187 Realtek Semiconductor Corp. RTL8187 Wireless Adapter and a 2357:0109 TP-Link TL WN823N RTL8192EU.
With which Sticks are you able to use AP Mode? Is there a list of supportet WiFi Sticks? I found none.

**Comment by dervitti** [comment]
got it with a 7392:7811 Edimax EW-7811Un 802.11n Wireless Adapter [Realtek RTL8188CUS]

**Comment by ThFischer** [comment]
@dervitti 
Hi, did you used the version 2 of the EW-7811Un?

**Comment by dervitti** [comment]
Hm, i don´t think it was v2, do both versions use the same USB ID 7392:b811?
