### ISSUE TITLE
Stalling at Starting AP in a screen

### ISSUE THREAD

**Issue by bbalz** [ct-Open-Source/tuya-convert#449]
I've tried flashing a few times and used the lite and full Raspian builds.  Each time I've run into this same exact issue. 

It clones, installs and when I try to start flash, it stalls at the 'Starting AP in a screen' and never shows anything further. 

![image](https://user-images.githubusercontent.com/47855770/70578063-49681100-1b72-11ea-9d10-585a50026438.png)

It does broadcast the vtrust-flash SSID but the command prompt never progresses any further. 

I'm at a loss with what to do.  I've never had an issue with this process but it was months ago when it was working without a hiccup.  Since then I reflashed a new pi as noted above and I've even tried 2 different cards, 2 different versions of the Pi and no luck. 

Any help would be greatly appreciated.

**Comment by kueblc** [comment]
You might be connected to the device via the same wifi card that's used for the AP. You need to use another connection (ethernet, USB, etc) since the wifi is needed to create the AP.

**Comment by bbalz** [comment]
Oh geez, you're right.  I totally forgot about that when I did it the first time.  I'm sorry.  

Thank you a bajillion for the fast response.
