### ISSUE TITLE
Cant obtain IP from AP with any devices on Fedora WS

### ISSUE THREAD

**Issue by JonHeron** [ct-Open-Source/tuya-convert#450]
Fedora30_64
I modified the install_prereq.sh  and setup-ap.sh to work on fedora, see attached files if interested.
When the start-flash script runs it looks fine but when I try to connect with a phone or other device it never obtains an IP?
dnsmasq version dnsmasq-2.80-10.fc30.x86_64

Not sure what to try next?
Cheers,
Jon
Here is the cli output:

> [jonnyslaptop@jonnyslaptop-localdomain tuya-convert] $ ./start_flash.sh
Checking for network interface wlp2s0... Found.
Checking UDP port 53... Available.
Checking UDP port 67... Available.
Checking TCP port 80... Available.
Checking TCP port 443... Available.
Checking UDP port 6666... Available.
Checking UDP port 6667... Available.
Checking TCP port 1883... Available.
Checking TCP port 8886... Available.
======================================================
  Starting AP in a screen.
  Starting web server in a screen
  Starting Mosquitto in a screen
  Starting PSK frontend in a screen
  Starting Tuya Discovery in a screen

======================================================

IMPORTANT
1. Connect any other device (a smartphone or something) to the WIFI vtrust-flash
   This step is IMPORTANT otherwise the smartconfig may not work!
2. Put your IoT device in autoconfig/smartconfig/pairing mode (LED will blink fast). This is usually done by pressing and holding the primary button of the device
   Make sure nothing else is plugged into your IoT device while attempting to flash.
3. Press ENTER to continue

======================================================
Starting smart config pairing procedure
Waiting for the device to install the intermediate firmware
Put device in EZ config mode (blinking fast)
Sending SSID                  vtrust-flash
Sending wifiPassword          
Sending token                 00000000
Sending secret                0101
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
...........
Device did not appear with the intermediate firmware
Check the *.log files in the scripts folder
Do you want to try flashing another device? [y/N] n
Exiting...

>

**Comment by JonHeron** [comment]
Whoa, I screwed up the formatting there somehow. 
Too bad the code tags dont truncate the code, or am I doing it wrong?
I will put the log files in a zip file and upload them instead...
Cheers,
Jon

**Comment by JonHeron** [comment]
[smarthack-logs.zip](https://github.com/ct-Open-Source/tuya-convert/files/3948001/smarthack-logs.zip)

**Comment by JonHeron** [comment]
[modifiedFiles.zip](https://github.com/ct-Open-Source/tuya-convert/files/3948007/modifiedFiles.zip)

**Comment by JonHeron** [comment]
lol I cant fix the big fonts, not sure what is happening there, please bear with me...
Cheers,
Jon

**Comment by kueblc** [comment]
Use triple backtick (` ``` `) to enclose code blocks. Also note the preview feature.

**Comment by JonHeron** [comment]
Thanks for that!
Jon

**Comment by JonHeron** [comment]
I did some more playing with this today and checked some of the versions I am running for reference.
Python 2.7.17
Python3 3.7.5
OpenSSL 1.1.1d FIPS  10 Sep 2019
From pip:
Name: sslpsk Version: 1.0.0

I am thinking I will see what is happening with the AP using wireshark.
Do you think this is looking in the right direction?
Cheers,
Jon

**Comment by kueblc** [comment]
How about your `dnsmasq` version? This acts as our DHCP server so if you're unable to get an IP, it is likely related to `dnsmasq`.

Possibly related to #424

**Comment by JonHeron** [comment]
$ dnsmasq -version
Dnsmasq version 2.80  Copyright (c) 2000-2018 Simon Kelley
Compile time options: IPv6 GNU-getopt DBus no-i18n IDN2 DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth DNSSEC loop-detect inotify dumpfile

**Comment by JonHeron** [comment]
Thanks I think you may be right, it appears it is not even starting up.
sudo systemctl status dnsmasq
[sudo] password for jonnyslaptop: 
● dnsmasq.service - DNS caching server.
   Loaded: loaded (/usr/lib/systemd/system/dnsmasq.service; disabled; vendor pr>
   Active: failed (Result: exit-code) since Wed 2019-12-11 15:11:59 EST; 5min a>
  Process: 10314 ExecStart=/usr/sbin/dnsmasq -k (code=exited, status=2)
 Main PID: 10314 (code=exited, status=2)

Dec 11 15:11:59 jonnyslaptop-localdomain systemd[1]: Started DNS caching server>
Dec 11 15:11:59 jonnyslaptop-localdomain dnsmasq[10314]: dnsmasq: failed to cre>
Dec 11 15:11:59 jonnyslaptop-localdomain systemd[1]: dnsmasq.service: Main proc>
Dec 11 15:11:59 jonnyslaptop-localdomain dnsmasq[10314]: failed to create liste>
Dec 11 15:11:59 jonnyslaptop-localdomain systemd[1]: dnsmasq.service: Failed wi>
Dec 11 15:11:59 jonnyslaptop-localdomain dnsmasq[10314]: FAILED to start up
lines 1-12/12 (END)
I will dig into this deeper...
PS I dont seem to have a back tick on my Asus laptop keyboard...
Cheers,
Jon

**Comment by JonHeron** [comment]
Strange, even though it says it cant start cause port 53 is in use, it appears there are 2 instances of dnsmasq running...
$sudo lsof -i:53
COMMAND  PID    USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
dnsmasq 1242 dnsmasq    5u  IPv4  35524      0t0  UDP jonnyslaptop-localdomain:domain 
dnsmasq 1242 dnsmasq    6u  IPv4  35525      0t0  TCP jonnyslaptop-localdomain:domain (LISTEN)

Lol wtf.
On Fedora I think NetworkManger uses dnsmasq so perhaps that is the conflict, however stopping Network manager should resolve the conflict but it doesnt...
Cheers,
Jon

**Comment by JonHeron** [comment]
I got dnsmasq logging to a file now, it appears it is starting up normally though eh?
``` Dec 13 20:42:04 dnsmasq[23176]: started, version 2.80 cachesize 150
Dec 13 20:42:04 dnsmasq[23176]: compile time options: IPv6 GNU-getopt DBus no-i18n IDN2 DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth DNSSEC loop-detect inotify dumpfile
Dec 13 20:42:04 dnsmasq-dhcp[23176]: DHCP, IP range 10.42.42.10 -- 10.42.42.40, lease time 12h
Dec 13 20:42:04 dnsmasq-dhcp[23176]: DHCP, sockets bound exclusively to interface wlp2s0
Dec 13 20:42:04 dnsmasq[23176]: read /etc/hosts - 3 addresses
Dec 13 20:43:47 dnsmasq[23176]: exiting on receipt of SIGTERM```
I tried removing the lines you suggested in #424 with no joy either.
Cheers,
Jon

**Comment by billtown** [comment]
if dnsmasq isn't logging any attempts, but your ap is seen, likely it's your firewall.  as a stop gap

Check dmesg and look for REJECT and SPT=68 DPT=67 from 0.0.0.0  aka your missing dhcp requests.....

on fedora 30

```sudo systemctl stop firewalld.service```

Do you're thing upgrade of stuff or retest dnsmaq

Then turn your firewall back on when you are finished.

```sudo systemctl start firewalld.service when you are finished.```

**Comment by JonHeron** [comment]
That was it!
Thank you sir!
I feel dopey for not trying this sooner...
Cheers,
Jon
