### ISSUE TITLE
Will WinnerMicro based devices be supported?

### ISSUE THREAD

**Issue by mva-one** [ct-Open-Source/tuya-convert#454]
Recently I got some AWP08L plugs, or to be exact some plugs exactly looking like AWP08L plugs, and discovered that there is a "WinnerMicro W600-A800" SoC inside which obviosly doesnt work with tuya-convert. 

Is there any chance that in future these WinnerMicro-based devices will be supported?

**Comment by kueblc** [comment]
Unfortunately not, third party firmware designed for one SoC will not work on another.
