### ISSUE TITLE
Successfully flashed Hyleton 313 (UK Version)

### ISSUE THREAD

**Issue by Dav3UK** [ct-Open-Source/tuya-convert#46]
This is how I configured it - and it works like a dream !

![png image-f749308c8bf0-1](https://user-images.githubusercontent.com/34207893/51900041-38743e00-23ac-11e9-84eb-9ebea377f415.png)

![68747470733a2f2f7a6e616e65762e6769746875622e696f2f696d616765732f68796c65746f6e2d3331332f68796c65746f6e2d3331332e6a7067](https://user-images.githubusercontent.com/34207893/51900076-44f89680-23ac-11e9-938a-d1beb58d78f4.jpeg)

**Comment by merlinschumacher** [comment]
Thanks for your feedback!
