### ISSUE TITLE
Unable to Flash WL-LC01 Bulb Socket

### ISSUE THREAD

**Issue by farizazmip** [ct-Open-Source/tuya-convert#468]
Hello. Today I tried to flash my WL-LC01 bulb socket using tuya-convert. Unfortunately, it's stucked on "Resending SmartConfig Packets" step. The complete log is provided down below. Observing from the log, does it imply that my device can't be flashed using tuya-convert? Thank you in advance.

[log_tail_light_socket.txt](https://github.com/ct-Open-Source/tuya-convert/files/4006980/log_tail_light_socket.txt)

**Comment by kueblc** [comment]
Unfortunately, it does look like this is an unsupported device. We can only install firmware on the ESP82xx microcontroller. You might try `tuyapi` to control your device locally with the stock firmware, or try another bulb. Best of luck!
