### ISSUE TITLE
Gosund (WP5?) outlet successful flash

### ISSUE THREAD

**Issue by ragenhe** [ct-Open-Source/tuya-convert#47]
These were flashed successfully.  https://www.amazon.com/gp/product/B07GRLQV47/

Note:  Doing three in a row, it didn't appear as if the 2nd and 3rd plug was backed up.  I wasn't sure if that was intended, just wanted to raise that scenario here.

**Comment by merlinschumacher** [comment]
Thanks for your feedback!
