### ISSUE TITLE
will the swa11 be compatible?

### ISSUE THREAD

**Issue by baldarn** [ct-Open-Source/tuya-convert#471]
Just to know... :) I bought 2 plugs and I tried this hack but without success.

the swa11 is not listed in the supported devices, so this is a feature request :)

**Comment by kueblc** [comment]
There's no way to tell without trying, if you need help deciphering your logs please post them.

**Comment by baldarn** [comment]
it worked!! yesterday I was dumber and I didn't see that it was ok! today I successfully flashed tosmota on it!

the swa11 is supported!! 

:)

**Comment by kueblc** [comment]
Great, very happy to hear it worked out, and thank you very much for your support!

**Comment by thenightfighter** [comment]
Won't work for me :(.

Any ideas what I could do?

**Comment by marcob1281** [comment]
hi all, coming back to this old thread. 
I have the same smart plug, I could flash Tasmota FW, but Energy monitoring is not supported. any hint?
