### ISSUE TITLE
Try to flash a door sensor TYWE3S but not succesfull help appreciated ;-)

### ISSUE THREAD

**Issue by andyprivate** [ct-Open-Source/tuya-convert#478]
![IMG_20191231_112727](https://user-images.githubusercontent.com/59390083/71619197-7b91ef00-2bc3-11ea-8805-512516a220f5.jpg)
Hi all

i am a newbie here so sorry if i do something wrong i tried to flash a doorsensor image attached but cannot get it to work your help will be very usefull thanks in advance Andy
Logfiles are also attached
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/4012485/smarthack-mqtt.log)

[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/4012448/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/4012449/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/4012450/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/4012451/smarthack-wifi.log)

**Comment by kueblc** [comment]
Door and motion sensors only stay online for a brief period. See #135. Closing as duplicate.

**Comment by andyprivate** [comment]
Thanks to kueblc work now like a charm thanks and an nice new year ;-) thanks Andy

**Comment by kueblc** [comment]
Glad to hear it! Happy New Year

**Comment by kueblc** [comment]
Hi @muammersayar, I'm afraid I do not have the binaries you are looking for. Best of luck.
