### ISSUE TITLE
CE Costco Dimmer

### ISSUE THREAD

**Issue by stoehrmark** [ct-Open-Source/tuya-convert#48]
I successfully flashed this device with tuya-convert but now it is not working.
I setup the "Module type" to be "Tuya Dimmer (54)" but Tasmota will not talk to the switch. The buttons on the front of the switch still work but no connection to the Tasmota interface. Tasmota does not see any change from the buttons. Also, the green led is constantly flashing.
Any help would be great. And thanks for the hard work on this project!!
  [CE Costco Dimmers](https://www.costco.com/CE-Smart-Dimmer-Switch-2-pack.product.100414460.html )

**Comment by ragenhe** [comment]
I thought I bricked one last night, turns out it grabbed a new / different IP.  Double check the IP.

**Comment by stoehrmark** [comment]
I found the problem 
change to the following and everything works great

Tuya RX(108) to GPIO13
Tuya TX (107) to GPIO15

**Comment by merlinschumacher** [comment]
Thanks for your contribution
