### ISSUE TITLE
CE Smart Home outlet won't flash

### ISSUE THREAD

**Issue by jcbshw** [ct-Open-Source/tuya-convert#487]
Attempting to flash my CE Smart Home outlet (LA-WF3), it always disconnects from vtrust-flash a few seconds after connecting. Using a RPi4 running Raspbian Buster. 

[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/4022837/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/4022838/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/4022839/smarthack-wifi.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/4022840/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/4022841/smarthack-psk.log)

**Comment by kueblc** [comment]
Did you try [Troubleshooting](https://github.com/ct-Open-Source/tuya-convert/wiki/Troubleshooting)? Perhaps "vtrust-flash rejects subsequent connections after the first"?

**Comment by countcobolt** [comment]
Hi just wondering if this is similar to #483 ? I had the same behaviour? It had tuya 1.1.4 firmware on it

**Comment by kueblc** [comment]
No @countcobolt, you were able to get the device to connect as evidenced by your PSK log. Here, @jcbshw's device isn't staying connected at all.

**Comment by countcobolt** [comment]
@kueblc  Okido :)

**Comment by jcbshw** [comment]
@kueblc thanks for pointing that out. I attempted on my RPi4 running Arch Linux but had the same issues as well. I'm not sure if its directly related to the issue described in troubleshooting as it was on Raspbian Stretch with hostapd 2.4 which was fixed in 2.6.

I was able to successfully flash using my laptop on Ubuntu 19.10.
