### ISSUE TITLE
successfully flashed Koogeek KLOE4 Smart Power Strip

### ISSUE THREAD

**Issue by callahanharry** [ct-Open-Source/tuya-convert#50]
Thanks for great tool! I just successfully flashed Koogeek KLOE4 Smart Power Strip. 

This is my GPIO configuration in Tasmota:

gpio4	socket 2
gpio5	socket 1
gpio12	socket 3
gpio13	socket 4
gpio14	usb
gpio3	button
gpio1	power LED

![screen shot 2019-01-29 at 20 23 01](https://user-images.githubusercontent.com/42916182/51934900-fcb99280-2404-11e9-9d09-ea3e65d4231d.png)

![kloe4](https://user-images.githubusercontent.com/42916182/51935175-9b45f380-2405-11e9-918a-2d1445a40585.png)

**Comment by merlinschumacher** [comment]
Thanks for your contribution!

**Comment by sgrimee** [comment]
Worked great for me, but I had to use Led1i (56) instead to have the Led lit when one relay is on, and keep it off when all relays are off.
