### ISSUE TITLE
Clarification on expected wifi AP behavior 

### ISSUE THREAD

**Issue by Virtual-Nomad** [ct-Open-Source/tuya-convert#504]
Firstly my apologies as this may not be the right place to ask the question, however, I just wanted to confirm that my thinking is correct that despite the WiFi AP appearing to be configured and working if my phone refuses to join vtrust-flash (ie "the unable to join the network" ), I have a configuration issue and until that is resolved I won't be able to proceed.

![image](https://user-images.githubusercontent.com/57859302/72481307-d410ef80-3845-11ea-83d2-86beb2f53d1b.png)
![image](https://user-images.githubusercontent.com/57859302/72481335-ea1eb000-3845-11ea-8f38-c7aaec80396a.png)
![image](https://user-images.githubusercontent.com/57859302/72481347-f60a7200-3845-11ea-827b-c977378708d4.png)

**Comment by kueblc** [comment]
It may be that there is a deeper issue, perhaps with IP assignments from `dnsmasq`.

Is your phone not receiving an IP address or is the problem earlier than that?

Your phone MAC address should appear in your `smarthack-wifi.log` as soon as a connection is attempted.

Note that you will not have a connection to the internet from `vtrust-flash`, this is expected.

**Comment by kueblc** [comment]
Let me know if you need any further assistance, and good luck!
