### ISSUE TITLE
Bakibo TP22Y - flash was successfull - device dead

### ISSUE THREAD

**Issue by dragonvalor86** [ct-Open-Source/tuya-convert#507]
Hi all,
today I flash an Bakibo TP22Y device and everything looks fine. The flash process works great and after that I connect my smartphone to the tasmota-Wifi to change the wifi settings. After I press "Save" the device restart but from this moment the device is completly dead.

No lights, no relay-"click"-sound by pressing the button.

Does anybody know what happen or is it possible to open the device to flash it with FTDI?

BR Pad

**Comment by kueblc** [comment]
Hi @dragonvalor86, happy to hear the tuya-convert process worked smoothly for you. Sorry to hear you are having trouble post installation. This issue tracker is for tuya-convert issues, so I suggest you try elsewhere to resolve your post installation issues. Good luck!
