### ISSUE TITLE
sslpsk from git is not being installed + misleading error (attributeerror: '_ssl._sslsocket' object has no attribute '_sslobj') [solution included]

### ISSUE THREAD

**Issue by Lovely-Maisonette** [ct-Open-Source/tuya-convert#508]
_install_prereq.sh_
`pip install git+https://github.com/drbild/sslpsk.git@use-byte-string-for-identity-hints`

refuses to install if sslpsk is already installed. ie: 
`pip install sslpsk`

adding **--upgrade** solved my problem
`pip install --upgrade git+https://github.com/drbild/sslpsk.git@use-byte-string-for-identity-hints`

The _install_prereq.sh_ script fails gracefully, so I went on and tried to flash my devices, very frustrating trying to debug ssl errors at the wrong place.

**Comment by kueblc** [comment]
Thank you @Lovely-Maisonette for debugging this! I will plan on integrating this into the next release.
