### ISSUE TITLE
LED blinking rapidly, brick

### ISSUE THREAD

**Issue by d4icon** [ct-Open-Source/tuya-convert#512]
Hello and thanks for all the work.

I have flashed 3 shp2 devices, all ok.
Today I try fourth, and it has brick in the step: "flash3"

The "sonoff" wifi has not been created and now even if I disconnect and connect the plug I cannot launch the script again and led blick very fast
Also I can not connect with the original application.

Comment that I used this fork:
https://github.com/kueblc/tuya-convert

I have read some similar cases:
https://github.com/ct-Open-Source/tuya-convert/issues/366

But I still don't understand the reason why it happens.

I'm going to buy another one and I'd like to know what I've done wrong.

thanks

**Comment by kueblc** [comment]
Hi @d4icon,

This fork is not for public consumption, it is used for development. We do not use `/flash3` any longer. If you want help determining what went wrong you will need to post your logs. I highly recommend using the main repo for any future flashing needs.
