### ISSUE TITLE
LSC Smart Connect RGBW E27 Blub flashing doesn't work

### ISSUE THREAD

**Issue by root01** [ct-Open-Source/tuya-convert#513]
Hello,
I'm trying to flashing this bulb but it's not working. 
The LSC Smart Connect MR16 380lm RGBW Bulb flashed without problems but the E27 stays at 

> Starting smart config pairing procedure
Waiting for the device to install the intermediate firmware
.Put device in EZ config mode (blinking fast)
Sending SSID                  vtrust-flash
Sending wifiPassword          
Sending token                 00000000
Sending secret                0101
.................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
............
Device did not appear with the intermediate firmware
Check the *.log files in the scripts folder
Do you want to try flashing another device? [y/N] 

Hang up then breaks off.
Is there anything else I could try?

I can also provide the log files from the /script folder

**Comment by kueblc** [comment]
I don't believe this device is supported, as it does not use an ESP. To be sure you would need to share your logs as indicated in the instructions.

**Comment by root01** [comment]
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/4099357/smarthack-wifi.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/4099358/smarthack-udp.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/4099359/smarthack-mqtt.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/4099360/smarthack-web.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/4099361/smarthack-psk.log)

**Comment by root01** [comment]
The blub stops short blinking while the flashing process. something happens

**Comment by kueblc** [comment]
Unfortunately not an ESP, as revealed by the MAC address in your wifi log

**Comment by root01** [comment]
Ok. that's bad. Thanks
