### ISSUE TITLE
Tuya electric heater / Backup original firmware

### ISSUE THREAD

**Issue by agoralive** [ct-Open-Source/tuya-convert#517]
Hi

Have anybody had som/any luck with an electrical heater?

Is there a way to make a backup of the original firmware, in order to "rollback" in case it becomes necessary?

**Comment by kueblc** [comment]
Hi @agoralive,

Please refer to the README, as these questions are answered for you already, and this issue tracker is intended for reporting bugs and feature requests. As mentioned in our README, the community maintained wiki is the place to find out about supported devices, and the backup that our software creates can be flashed back to the device by wire.
