### ISSUE TITLE
start_flash.sh fails if ufw is enabled

### ISSUE THREAD

**Issue by ndfred** [ct-Open-Source/tuya-convert#518]
`start_flash.sh` does a great job of disabling services that run on the various ports it uses, but doesn't disable ufw (infinite loop in `Resending SmartConfig Packets`). After I disabled ufw and ran the script again everything worked. Maybe the script should check if the firewall is enabled, and suggest disabling it.

**Comment by kueblc** [comment]
Great catch! I had noticed some other folks with firewall issues. #450 #464

Any suggestions for the best way to detect and temporarily disable firewalls?

**Comment by kueblc** [comment]
Let me know what you think of this
```bash
check_firewall () {
	if sudo systemctl stop firewalld.service &>/dev/null; then
		echo "Attempting to stop firewalld.service"
		echo "When done, enable with: sudo systemctl start firewalld.service"
	fi
	if sudo ufw status | grep -qw active; then
		sudo ufw disable
		echo "When done, enable with: sudo ufw enable"
	fi
}
```
