### ISSUE TITLE
tuya-convert v2.4.0 and 2.4.1 does not work on deltaco SH-P02 (possible others also devices).

### ISSUE THREAD

**Issue by orrpan** [ct-Open-Source/tuya-convert#520]
I've not been able to flash the Deltaco SH-P02 with the latest versions, and I have no logs to show. I only noticed that the device got connected (and reconnected when ez/reset) in the wifi screen, but then nothing else happened. 
I then checked out the v2.3.0, and it worked like a charm.
`git checkout tags/v2.3.0 -b v2.3.0`
Will try to redo it and get logs

**Comment by kueblc** [comment]
Thanks for the report @orrpan! Have you tried the `development` branch?

**Comment by kueblc** [comment]
Just published v2.4.2. Let me know if you still have issues!
