### ISSUE TITLE
Unable to flash tuya bulb: fcc id: 2AJK8-LZ803

### ISSUE THREAD

**Issue by jimtino** [ct-Open-Source/tuya-convert#526]

**Comment by jimtino** [comment]
I'm using tuya convert version v2.4.3 . and am getting the "Device did not appear with the intermediate firmware" I don't see anything onerous in the error logs. Can someone help me decipher what may be going on?

Thanks so much. Logs attached:
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/4132312/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/4132313/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/4132314/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/4132315/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/4132316/smarthack-wifi.log)

**Comment by kueblc** [comment]
Looks like the device is taking the intermediate firmware, but then restarting back into the stock firmware. Might suggest that the upgrade image is corrupt in some way.

**Comment by jimtino** [comment]
Maybe I missed something. Where do I get the upgrade image? Is it part of tuya convert? I'm using a rasberry pi. Do I need to reimage the pi? Thanks so much.

**Comment by kueblc** [comment]
The upgrade image (`upgrade.bin`) is included with tuya-convert. It might be that it was corrupted in download, or that your device is in some way incompatible with the current version. It is difficult to say with the limited information.

**Comment by kueblc** [comment]
Closing due to age, please feel free to comment if this is still an issue
