### ISSUE TITLE
Successfully flashed "MoesHouse" WiFi Plug

### ISSUE THREAD

**Issue by micgus** [ct-Open-Source/tuya-convert#53]
Heya, 
Million thanks for great development. You guys rock.

Successfully flashed this smart plug, EU:
https://www.aliexpress.com/item/UK-US-EU-WiFi-Smart-Socket-Power-Plug-Outlet-Remote-Control-Works-with-Amazon-Alexa-Google/32954272490.html 

GPIO12 = Relay
GPIO5= Led, Inverted

**Comment by tkotz8105** [comment]
That socket looks similar to the Geekbes I'm working with in the US (https://slickdeals.net/f/10540212-3-pack-geekbes-smart-wifi-mini-plug-26-free-s-h).  Were you able to determine what GPIO the on-device button goes to?  Many thanks for any info you can provide.

**Comment by micgus** [comment]
I did indeed, got everything working including the button but I couldn't remember the button configuration.
I'll post a screenshot for ya asap.

Cheers

**Comment by merlinschumacher** [comment]
Thanks for your contribution
