### ISSUE TITLE
Want add another Tasmoate Version bigger than 512kb

### ISSUE THREAD

**Issue by iqmend** [ct-Open-Source/tuya-convert#530]
Hello,
i want add in tuya-convert/files an older tasmota version. But all versions are bigger than 512kb. 
Only the minimal and lite version are smaller but i dont want install this version.
Why do we have this limit and can i turn it up to 600kb ? Because than i can install every version i want.

![image](https://user-images.githubusercontent.com/59153482/73762958-15276000-4771-11ea-93df-7616279db630.png)

![image](https://user-images.githubusercontent.com/59153482/73763187-6172a000-4771-11ea-80ff-601449b47dc5.png)

**Comment by kueblc** [comment]
Use the included Tasmota and then upgrade to the version you want

**Comment by iqmend** [comment]
If i do like this i have to downgrade because i want use 7.1 
And i think downgrade to 7.1 is not possible afer i install 8.1

**Comment by kueblc** [comment]
Then why not start with minimal? The limit is not ours, it is a technical limitation that applies to every ESP OTA upgrade.

**Comment by kueblc** [comment]
You can also add (`A55AA55A FFFFFFFF 5AA55AA5`) to the end of any firmware to allow Tasmota 8.1 to upgrade to it.

**Comment by meingraham** [comment]
Danger Will Robertson! Danger!

Do not flash with tasmota-minimal. You have to start with something that will let you configure the Wi-Fi parameters and minimal will not. This version expects to find the Tasmota settings already in place.

**Comment by iqmend** [comment]
absolut right @meingraham 
i tryed one plug with minimal and got an error at wifi conect. Now i can not access to this plug. 
Its a TP22 Plug i can also not open it to flash with ftdi -.-

**Comment by kueblc** [comment]
Thanks for chiming in @meingraham, I'll keep that in mind
