### ISSUE TITLE
Vtrust-Recovery backup not downloaded can not reach device

### ISSUE THREAD

**Issue by riker65** [ct-Open-Source/tuya-convert#536]
I got stuck with the convert having wlan vtrust-recovery launched.

it is **a gosund SP1**

A restart of - did a couple of those - of start-flash.sh did not solve it.

```
- message. could not fetch a complete backup - 
continue anyway.
```

after doing so and trying to flash tasmota.

process tries to get info from device-IOT.---take a while saying ready to flash.
after selecting tasmota and y.

----but could not reach it.

can ping 10.42.42.42

vtrust-recovery is still up.
`VTRUST-FLASH 1.5
(c) VTRUST GMBH https://www.vtrust.de/35c3/
READ FLASH: http://10.42.42.42/backup
ChipID: 33f959
MAC: 24:62:AB:33:F9:59
BootVersion: 7
BootMode: normal
FlashMode: 1M DOUT @ 40MHz
FlashChipId: 144051
FlashChipRealSize: 1024K
Active Userspace: user2 0x81000`

How to solve this ?

Thanks T

[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/4176918/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/4176919/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/4176920/smarthack-web.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/4176921/smarthack-mqtt.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/4176922/smarthack-wifi.log)

**Comment by Dalli75** [comment]
Unfortunetely I can not help you, but I can confirm I have exectly the same problem with the Gosund E27 Smart LED Bulb.

I stuck at the same place. Bulb is in wlan vtrust mode and the bulb is pingable. But the fetching the backup and uploading the image fails duo to ther error: "could not reach the device"

**Comment by riker65** [comment]
hi please try

this worked for me 
some hints from: [https://github.com/ct-Open-Source/tuya-convert/issues/362](url)

connect to vtrust-recovery
with a different device 
`curl http://10.42.42.42/undo`

delete firmwarebackup in backups folder 

start-flash again....

worked

**Comment by jayshomebrew** [comment]
@riker65 Thanks so much, this fixed a bad backup for GDTech model MPV2RO-US (plug).

**Comment by Pa1nstar** [comment]
@riker65 thank you so much! finally this was the solution to my problem! :-)
