### ISSUE TITLE
Error: Device did not appear with the intermediate firmware - Bakibo TP22Y

### ISSUE THREAD

**Issue by The-May** [ct-Open-Source/tuya-convert#543]
I am getting following error:

`Device did not appear with the intermediate firmware`

The Device is switching from EZ config mode automatically to "normal" mode (static blue light).

Bakibo TP22Y
Version:
WI-FI Module: 1.1.4
MCU-Module 1.1.4

According to 2 different sources it should work with tuya-convert.

I have tried it on the latest buster and the last "latest" stretch version.
They are fresh Installs.
I tried it several times.

logs have been added and I also added a file that shows what i am getting:

[Commands.txt](https://github.com/ct-Open-Source/tuya-convert/files/4210149/Commands.txt)

[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/4210144/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/4210145/smarthack-wifi.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/4210146/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/4210147/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/4210148/smarthack-udp.log)

**Comment by kueblc** [comment]
Unfortunately you have a patched firmware using a new PSK, see #483. You will not be able to use tuya-convert on these devices at this time.
