### ISSUE TITLE
Teckin SB60 (new 800 lumen model with RGB + 2800K-6000K CCT) any clue?

### ISSUE THREAD

**Issue by Bidulglloq** [ct-Open-Source/tuya-convert#546]
Anyone tried and succeeded using Tuya-Convert on these new **Teckin SB60**?

**Comment by kueblc** [comment]
This is an issue tracker, not a forum. See wiki for known working and non-working devices.

**Comment by Bidulglloq** [comment]
Hi Colin,
There is no statement about this Teckin SB60 bulb on the working/non
working devices. I didn't find a way to ask if anyone have tried.
I don't know how to proceed

What would you suggest?

Thx a lot

Serge

--
Serge BUISINE

Tel:     +33 6 13 93 30 48
Email. serge.buisine@gmail.com
skype: serge.buisine
--------------
