### ISSUE TITLE
Tasmota keeps falling back to AP mode.

### ISSUE THREAD

**Issue by echojjj** [ct-Open-Source/tuya-convert#552]
I have used tuya-convert to flash Tasmota to a tuya bulb.  I did the OTA firmware upgrade to the latest version of Tasmota.  Every time my bulb reboots it goes back into AP mode, where I have to re-supply the Wifi setup, re-upgrade Tasmota, and restore my config backup.  Every time.  Is this a tuya-convert issue or a Tasmota issue?

**Comment by meingraham** [comment]
This is something in how you have configured Tasmota. You need to seek assistance on the Tasmota Discord channel.

**Comment by kueblc** [comment]
Closing as answered, thank you @meingraham. Best of luck resolving your issue @echojjj!
