### ISSUE TITLE
Port 80 is still occupied

### ISSUE THREAD

**Issue by Schnubby666** [ct-Open-Source/tuya-convert#555]
I recently installed tuya-convert on my Raspberry Pi 3b+.
Since then I have tried several times to flash Tuya devices.
However, it is always reported that port 80 is occupied. The web log also says
Could not start server on port 80
Close the process on this port and try again

I was able to successfully carry out a flash process. At that point, I had disconnected multiple devices from my network. Is it related?
The next time I tried, it didn't work again. Even if the WLAN was switched off and only Raspberry, Windows PC and the router were connected.
Where does port 80 exist at all, on the Windows PC or on the Raspberry? How can I find out which process is running there and how can I kill it?

Edit: Issue can closed. With "sudo apachectl stop" you can stop the Process on Port 80. Then it works

**Comment by kreuzspeiche** [comment]
same problem here,

 PI 4b 2GB, everythin fresh installed. web log also reported that the port 80 is occupied

Thank for your tip. 
With "sudo apachectl stop"  its runs smootly
