### ISSUE TITLE
In search for original Teckin SP22 firmware

### ISSUE THREAD

**Issue by IRp3r** [ct-Open-Source/tuya-convert#560]
Hello,

sorry if this isn't the right place.
I need to reflash the original firmware on one (about a year old, should use ESP8266) Teckin SP22.
Maybe someone from the community still has the original firmware image from the setup process.
Would be really cool!

If this request does not fit here, just let me know and I'll remove it.

Kind Regards

**Comment by kueblc** [comment]
You won't be able to use another device's firmware image with yours if you wish to use the Tuya cloud. Each firmware image has a uniquely assigned key specific to each device.

**Comment by IRp3r** [comment]
@kueblc  alright, thanks for your reply. I hope I'll find the original firmware somewhere (I know I extracted it somewhere). And even if not, luckily they are cheap.
