### ISSUE TITLE
Can't flash from Tasmota to Espurna or from Tasmota to default

### ISSUE THREAD

**Issue by pashdown** [ct-Open-Source/tuya-convert#561]
I successfully flashed Tasmota to Gosund WP6 devices, but would like to take them to Espurna instead.  Tasmota does not allow me to do so, telling me that the espurna flash is "not compatible".  I can't revert to the firmware backup either, Tasmota tells me "upload buffer miscompare".

**Comment by kueblc** [comment]
This is a Tasmota issue, not tuya-convert.

They have implemented a check to enforce only recent versions of Tasmota may be uploaded. As a workaround you can append `A55AA55A FFFFFFFF 5AA55AA5` to your binary before uploading.

See https://github.com/RavenSystem/esp-homekit-devices/issues/683#issuecomment-569532286.

**Comment by pashdown** [comment]
Thank you.
