### ISSUE TITLE
flash the deltaco sh-p02 does not work

### ISSUE THREAD

**Issue by farbrot** [ct-Open-Source/tuya-convert#564]
Hi
I saw another post about this but that one was closed. So as a newbie I repost since I am a newbie on this matter. :)
Tried to flash this sh-p02 without any success. 
Looked in the logs and really don't understand which one to look in.
Is there a tutorial on the matter that I can find. 
Thanks for all help.

**Comment by kueblc** [comment]
Please share some information so we can help you debug. I will need to see the logs found in your `tuya-convert/scripts` or `tuya-convert/backups` directory.

**Comment by farbrot** [comment]
Hi,
I starting to think it is the problem with the new firmware #483?? 
I'm not to sure its the issue.

[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/4303126/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/4303127/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/4303128/smarthack-wifi.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/4303129/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/4303130/smarthack-psk.log)

**Comment by leifclaesson** [comment]
Not the same issue, farbrot. The real error message is in the UDP log:
**WARNING: it appears this device does not use an ESP82xx and therefore cannot install ESP based firmware**

The MAC address appears to be from "Hangzhou Hangzhou Aixiangji Technology" -- I don't recognize this so I don't know what microcontroller it is, but if it's not an ESP82xx then Tasmota/ESPeasy won't work, unfortunately.

**Comment by kueblc** [comment]
According to your web log
```
WARNING: it appears this device does not use an ESP82xx and therefore cannot install ESP based firmware
```
We only support ESP based devices

**Comment by farbrot** [comment]
![WIN_20200308_18_32_51_Pro](https://user-images.githubusercontent.com/61867755/76168050-e899a600-616b-11ea-9d15-e05cbf083dcc.jpg)

Just show the device

**Comment by farbrot** [comment]
> Not the same issue, farbrot. The real error message is in the UDP log:
> **WARNING: it appears this device does not use an ESP82xx and therefore cannot install ESP based firmware**
> 
> The MAC address appears to be from "Hangzhou Hangzhou Aixiangji Technology" -- I don't recognize this so I don't know what microcontroller it is, but if it's not an ESP82xx then Tasmota/ESPeasy won't work, unfortunately.

It the same image as the show at the supported devices in https://templates.blakadder.com/deltaco_SH-P02.html

**Comment by thrawnarn** [comment]
I had the same problem as @farbrot . Same error message. I decided to sacrifice my plug to know if there is something to do. And it seams like Deltaco has change chipset inside of them. At least I couldn't find an ESP.

![IMG_1968](https://user-images.githubusercontent.com/5276026/76242509-244d7200-6237-11ea-91b6-ad4d32f4c3b3.jpg)
![IMG_1970](https://user-images.githubusercontent.com/5276026/76242513-257e9f00-6237-11ea-939d-f14b17c96bc0.jpg)
![IMG_1969](https://user-images.githubusercontent.com/5276026/76242515-26173580-6237-11ea-8332-91cc35451a4a.jpg)

**Comment by meingraham** [comment]
Yup, looks like they have switched to the RTL Wi-Fi chip.

**Comment by lerra** [comment]
Any chance to get support for the new chipset?
