### ISSUE TITLE
Tuya S126 bricked .... like a brick

### ISSUE THREAD

**Issue by petely** [ct-Open-Source/tuya-convert#569]
I installed the _tuya-convert_ package on an RPi 3+ and got all the upgrades / updates as described.
The flashing process worked without a problem. I installed the Espurna binary that comes with tuya-convert.
After the re-flash, the device was fine. I connected to its web server from my phone, changed its name, added a couple of Wifi networks. Saved the changes and hit the reboot button on the 192.168.4.1 web page. 
The device's LED went out and I unplugged it. Took it to where I will be using it, plugged it in and nothing happened. No LED came on. No AP was created. It didn't connect to any WiFi. Alexa couldn't see it.
It is now just a small paperweight.

Here's the screenshot of the re-flash - any thoughts?
![tuya-update](https://user-images.githubusercontent.com/18531010/76654014-48c48980-656a-11ea-902d-86166801c131.jpg)

**Comment by kueblc** [comment]
> The flashing process worked without a problem

Awesome!

> I installed the Espurna binary that comes with tuya-convert

So your issues are with Espurna, not tuya-convert. Try seeking support through Espurna's support channels as we have nothing to do with the project. Good luck!
