### ISSUE TITLE
Teckin SP20 not flashing

### ISSUE THREAD

**Issue by ebdavison** [ct-Open-Source/tuya-convert#577]
### Before opening a new issue, please read the following

**Are you reporting a successful flash?**  NO

**Do you have a question about configuring your newly flashed device?** NO

**Did you have issues getting a device to flash?**  YES
_Please be sure to include your device **name, model, and firmware version** as well as your **logs**!_

I have similar problems to other issues I have reviewed.  The fash flash blue lights, start tuya-convert, see the device connect and then the light goes off and tuya-convert says the device did not appear with intermediate firmware and no backup done.

I will attach logs but found this particular bit in the `smarthack-web.log` which seems to point to the core of the issue:

```
POST /d.json?a=tuya.device.config.get&et=1&other={"token":"00000000","region":"US"}&t=21&uuid=185eedb5cba866bf&v=4.1&sign=bd68076fe18d05a95733cbfcd2c8adbb
Host: a2.tuyaus.com
User-Agent: TUYA_IOT_SDK
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 37

payload 6253098D9A26EAAC038A3AF53218969C
WARNING: it appears this device does not use an ESP82xx and therefore cannot install ESP based firmware
Answer tuya.device.dynamic.config.get
reply {"result":"fn8oBaEAaJe3I+enO7OkYdd0LkD9WHnY6k8vmvctrJbpRIwZnmiwsIEV71EL0JI+9F2VBmqNqTqJcWuiX4YubPMRUNYBQEZA7PwY0dZSNsu7mevrGF2WUpAllBDW/Q5l","t":1585456761,"sign":"a5f9a827495cc207"}
[I 200328 23:39:21 web:2250] 200 POST /d.json?a=tuya.device.config.get&et=1&other={"token":"00000000","region":"US"}&t=21&uuid=185eedb5cba866bf&v=4.1&sign=bd68076fe18d05a95733cbfcd2c8adbb (10.42.42.1) 3.59ms
```

I got a 4-pack of Teckin SP20 plugs today from Amazon and one is connected to the smart app but the one I am trying to convert is fresh out of the box.  The connected device shows firmware as:

```
No updates available
Wi-Fi Modules: 1.0.2
MCU Module: 1.0.2
```

Logs
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/4398302/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/4398303/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/4398304/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/4398305/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/4398307/smarthack-wifi.log)

**Comment by kueblc** [comment]
Looks like you answered your own question

> WARNING: it appears this device does not use an ESP82xx and therefore cannot install ESP based firmware

`tuya-convert`, Tasmota, Espurna, etc, only support ESP8266 devices
