### ISSUE TITLE
Teckin SB50 connects but smarthack packets never complete

### ISSUE THREAD

**Issue by stratus-ss** [ct-Open-Source/tuya-convert#586]
I just recently bought a pair of Teckin SB50 from Amazon. They connect to the tuya-convert wifi but the smart packet section sends forever

Device name: Teckin SB50
Firmware Version: Unknown as I have never connected this to the app

I have flashed a dozen smart plugs, some wifi leds and some power bars successfully in the past.

I decided to start a new tuya-convert folder so I cloned a fresh copy of tuya convert from github  but I got the same result as before. I checked both of the mac addresses, but they appear compatible on the surface:

![image](https://user-images.githubusercontent.com/8162705/79073675-e1f3d680-7cb5-11ea-838f-ac11f2fb5647.png)

Host is Ubuntu 19.10 running from git not inside of a container

Logs attached:

[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/4466614/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/4466615/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/4466616/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/4466617/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/4466618/smarthack-wifi.log)

**Comment by kueblc** [comment]
Unfortunately these came with patched firmware, see #483

**Comment by stratus-ss** [comment]
When a device is blocked, is there a chance that things will be worked around in the future?

I am not quite clear what "blocked" means.

**Comment by kueblc** [comment]
Yes there is a chance a workaround will be developed, but nothing guaranteed

**Comment by stratus-ss** [comment]
Thank you for your responses!

**Comment by stratus-ss** [comment]
Do you accept bounties?
