### ISSUE TITLE
Blitzwolf SHP6 not reachable afer Flash

### ISSUE THREAD

**Issue by Toki99** [ct-Open-Source/tuya-convert#596]
I flashed the SHP6 with Tasmota 8.2 by using the NodeMCU Tool. After flashing I connect to the WLAN Configuration Siteand entered my WLAN credentials.

But the Device is Always as Acces Point listet, but now i can´t reached it as AP or Device.

What´s wrong?

**Comment by kueblc** [comment]
Unrelated project
