### ISSUE TITLE
Bseed and tasmota? 

### ISSUE THREAD

**Issue by Lightningpicture** [ct-Open-Source/tuya-convert#604]
Hey,
Can I flash tasmota on this device? 
I can't find any template for it but it has tuya :/
Bseed wall switch 
Anybody know this switch? 

https://www.amazon.de/dp/B087JD38KS/ref=cm_sw_r_wa_apa_i_VvQREbB6RYSWP

Thank you

**Comment by barbudor** [comment]
@Lightningpicture I suggest that you ask Tasmota related question to Tasmota discord server where we will tell you to check into the Tasmota repository.
