### ISSUE TITLE
Raspberry Pi 3B Raspbian GNU/Linux 9 (stretch) - ufw not found

### ISSUE THREAD

**Issue by clach04** [ct-Open-Source/tuya-convert#619]
Running `start_flash.sh` resulted in seeing errors in stderr about sudo ufw not found (sorry I do not have the logs for this).

    pi@raspberrypi:~/tuya-convert] master(+5/-0)* 12s ± uname -a
    Linux raspberrypi 4.14.50-v7+ #1122 SMP Tue Jun 19 12:26:26 BST 2018 armv7l GNU/Linux
    [pi@raspberrypi:~/tuya-convert] master(+5/-0)* ± cat /etc/*elease*
    PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
    NAME="Raspbian GNU/Linux"
    VERSION_ID="9"
    VERSION="9 (stretch)"
    ID=raspbian
    ID_LIKE=debian
    HOME_URL="http://www.raspbian.org/"
    SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
    BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by kueblc** [comment]
Benign, as described in #620
