### ISSUE TITLE
Ubuntu 16.04 LTS - ss: invalid option -- 'H'

### ISSUE THREAD

**Issue by clach04** [ct-Open-Source/tuya-convert#622]
I was able to get Ubuntu 16.04 LTS 32-bit to flash a device. However there are multiple errors from `ss` relating to bad "H" option/flag. This appears to be benign.

Not sure if this is worth documenting or fixing hence opening an issue.

Sample extract (repeated for different ports):

    localhost:~/dev/tuya-convert$ ./start_flash.sh 
    tuya-convert v2.4.3
    Checking for network interface wlx00259ca393b8... Found.
    Checking UDP port 53... ss: invalid option -- 'H'
    Usage: ss [ OPTIONS ]
           ss [ OPTIONS ] [ FILTER ]
       -h, --help          this message
       -V, --version       output version information
       -n, --numeric       don't resolve service names
       -r, --resolve       resolve host names
       -a, --all           display all sockets
       -l, --listening     display listening sockets
       -o, --options       show timer information
       -e, --extended      show detailed socket information
       -m, --memory        show socket memory usage
       -p, --processes     show process using socket
       -i, --info          show internal TCP information
       -s, --summary       show socket usage summary
       -b, --bpf           show bpf filter socket information
       -E, --events        continually display sockets as they are destroyed
       -Z, --context       display process SELinux security contexts
       -z, --contexts      display process and socket SELinux security contexts
       -N, --net           switch to the specified network namespace name

       -4, --ipv4          display only IP version 4 sockets
       -6, --ipv6          display only IP version 6 sockets
       -0, --packet        display PACKET sockets
       -t, --tcp           display only TCP sockets
       -u, --udp           display only UDP sockets
       -d, --dccp          display only DCCP sockets
       -w, --raw           display only RAW sockets
       -x, --unix          display only Unix domain sockets
       -f, --family=FAMILY display sockets of type FAMILY

       -A, --query=QUERY, --socket=QUERY
           QUERY := {all|inet|tcp|udp|raw|unix|unix_dgram|unix_stream|unix_seqpacket|packet|netlink}[,QUERY]

       -D, --diag=FILE     Dump raw information about TCP sockets to FILE
       -F, --filter=FILE   read filter information from FILE
           FILTER := [ state STATE-FILTER ] [ EXPRESSION ]
           STATE-FILTER := {all|connected|synchronized|bucket|big|TCP-STATES}
             TCP-STATES := {established|syn-sent|syn-recv|fin-wait-{1,2}|time-wait|closed|close-wait|last-ack|listen|closing}
              connected := {established|syn-sent|syn-recv|fin-wait-{1,2}|time-wait|close-wait|last-ack|closing}
           synchronized := {established|syn-recv|fin-wait-{1,2}|time-wait|close-wait|last-ack|closing}
                 bucket := {syn-recv|time-wait}
                    big := {established|syn-sent|fin-wait-{1,2}|closed|close-wait|last-ack|listen|closing}
    Available.
    Checking UDP port 67... ss: invalid option -- 'H'
    Usage: ss [ OPTIONS ]
           ss [ OPTIONS ] [ FILTER ]
       -h, --help          this message
       -V, --version       output version information
       -n, --numeric       don't resolve service names
       -r, --resolve       resolve host names
       -a, --all           display all sockets
       -l, --listening     display listening sockets
       -o, --options       show timer information
       -e, --extended      show detailed socket information
       -m, --memory        show socket memory usage
       -p, --processes     show process using socket
       -i, --info          show internal TCP information
       -s, --summary       show socket usage summary
       -b, --bpf           show bpf filter socket information
       -E, --events        continually display sockets as they are destroyed
       -Z, --context       display process SELinux security contexts
       -z, --contexts      display process and socket SELinux security contexts
       -N, --net           switch to the specified network namespace name

       -4, --ipv4          display only IP version 4 sockets
       -6, --ipv6          display only IP version 6 sockets
       -0, --packet        display PACKET sockets
       -t, --tcp           display only TCP sockets
       -u, --udp           display only UDP sockets
       -d, --dccp          display only DCCP sockets
       -w, --raw           display only RAW sockets
       -x, --unix          display only Unix domain sockets
       -f, --family=FAMILY display sockets of type FAMILY

       -A, --query=QUERY, --socket=QUERY
           QUERY := {all|inet|tcp|udp|raw|unix|unix_dgram|unix_stream|unix_seqpacket|packet|netlink}[,QUERY]

       -D, --diag=FILE     Dump raw information about TCP sockets to FILE
       -F, --filter=FILE   read filter information from FILE
           FILTER := [ state STATE-FILTER ] [ EXPRESSION ]
           STATE-FILTER := {all|connected|synchronized|bucket|big|TCP-STATES}
             TCP-STATES := {established|syn-sent|syn-recv|fin-wait-{1,2}|time-wait|closed|close-wait|last-ack|listen|closing}
              connected := {established|syn-sent|syn-recv|fin-wait-{1,2}|time-wait|close-wait|last-ack|closing}
           synchronized := {established|syn-recv|fin-wait-{1,2}|time-wait|close-wait|last-ack|closing}
                 bucket := {syn-recv|time-wait}
                    big := {established|syn-sent|fin-wait-{1,2}|closed|close-wait|last-ack|listen|closing}
    Available.
    Checking TCP port 80... ss: invalid option -- 'H'
    Usage: ss [ OPTIONS ]
           ss [ OPTIONS ] [ FILTER ]
       -h, --help          this message
       -V, --version       output version information
       -n, --numeric       don't resolve service names
       -r, --resolve       resolve host names
       -a, --all           display all sockets
       -l, --listening     display listening sockets
       -o, --options       show timer information
       -e, --extended      show detailed socket information
       -m, --memory        show socket memory usage
       -p, --processes     show process using socket
       -i, --info          show internal TCP information
       -s, --summary       show socket usage summary
       -b, --bpf           show bpf filter socket information
       -E, --events        continually display sockets as they are destroyed
       -Z, --context       display process SELinux security contexts
       -z, --contexts      display process and socket SELinux security contexts
       -N, --net           switch to the specified network namespace name

       -4, --ipv4          display only IP version 4 sockets
       -6, --ipv6          display only IP version 6 sockets
       -0, --packet        display PACKET sockets
       -t, --tcp           display only TCP sockets
       -u, --udp           display only UDP sockets
       -d, --dccp          display only DCCP sockets
       -w, --raw           display only RAW sockets
       -x, --unix          display only Unix domain sockets
       -f, --family=FAMILY display sockets of type FAMILY

       -A, --query=QUERY, --socket=QUERY
           QUERY := {all|inet|tcp|udp|raw|unix|unix_dgram|unix_stream|unix_seqpacket|packet|netlink}[,QUERY]

       -D, --diag=FILE     Dump raw information about TCP sockets to FILE
       -F, --filter=FILE   read filter information from FILE
           FILTER := [ state STATE-FILTER ] [ EXPRESSION ]
           STATE-FILTER := {all|connected|synchronized|bucket|big|TCP-STATES}
             TCP-STATES := {established|syn-sent|syn-recv|fin-wait-{1,2}|time-wait|closed|close-wait|last-ack|listen|closing}
              connected := {established|syn-sent|syn-recv|fin-wait-{1,2}|time-wait|close-wait|last-ack|closing}
           synchronized := {established|syn-recv|fin-wait-{1,2}|time-wait|close-wait|last-ack|closing}
                 bucket := {syn-recv|time-wait}
                    big := {established|syn-sent|fin-wait-{1,2}|closed|close-wait|last-ack|listen|closing}
    Available.
    Checking TCP port 443... ss: invalid option -- 'H'
    Usage: ss [ OPTIONS ]
           ss [ OPTIONS ] [ FILTER ]
       -h, --help          this message
       -V, --version       output version information
       -n, --numeric       don't resolve service names
       -r, --resolve       resolve host names
       -a, --all           display all sockets
       -l, --listening     display listening sockets
       -o, --options       show timer information
       -e, --extended      show detailed socket information
       -m, --memory        show socket memory usage
       -p, --processes     show process using socket
       -i, --info          show internal TCP information
       -s, --summary       show socket usage summary
       -b, --bpf           show bpf filter socket information
       -E, --events        continually display sockets as they are destroyed
       -Z, --context       display process SELinux security contexts
       -z, --contexts      display process and socket SELinux security contexts
       -N, --net           switch to the specified network namespace name

       -4, --ipv4          display only IP version 4 sockets
       -6, --ipv6          display only IP version 6 sockets
       -0, --packet        display PACKET sockets
       -t, --tcp           display only TCP sockets
       -u, --udp           display only UDP sockets
       -d, --dccp          display only DCCP sockets
       -w, --raw           display only RAW sockets
       -x, --unix          display only Unix domain sockets
       -f, --family=FAMILY display sockets of type FAMILY

       -A, --query=QUERY, --socket=QUERY
           QUERY := {all|inet|tcp|udp|raw|unix|unix_dgram|unix_stream|unix_seqpacket|packet|netlink}[,QUERY]

       -D, --diag=FILE     Dump raw information about TCP sockets to FILE
       -F, --filter=FILE   read filter information from FILE
           FILTER := [ state STATE-FILTER ] [ EXPRESSION ]
           STATE-FILTER := {all|connected|synchronized|bucket|big|TCP-STATES}
             TCP-STATES := {established|syn-sent|syn-recv|fin-wait-{1,2}|time-wait|closed|close-wait|last-ack|listen|closing}
              connected := {established|syn-sent|syn-recv|fin-wait-{1,2}|time-wait|close-wait|last-ack|closing}
           synchronized := {established|syn-recv|fin-wait-{1,2}|time-wait|close-wait|last-ack|closing}
                 bucket := {syn-recv|time-wait}
                    big := {established|syn-sent|fin-wait-{1,2}|closed|close-wait|last-ack|listen|closing}
    Available.
    Checking UDP port 6666... ss: invalid option -- 'H'
    Usage: ss [ OPTIONS ]
           ss [ OPTIONS ] [ FILTER ]
       -h, --help          this message
       -V, --version       output version information
       -n, --numeric       don't resolve service names
       -r, --resolve       resolve host names
       -a, --all           display all sockets
       -l, --listening     display listening sockets
       -o, --options       show timer information
       -e, --extended      show detailed socket information
       -m, --memory        show socket memory usage
       -p, --processes     show process using socket
       -i, --info          show internal TCP information
       -s, --summary       show socket usage summary
       -b, --bpf           show bpf filter socket information
       -E, --events        continually display sockets as they are destroyed
       -Z, --context       display process SELinux security contexts
       -z, --contexts      display process and socket SELinux security contexts
       -N, --net           switch to the specified network namespace name

       -4, --ipv4          display only IP version 4 sockets
       -6, --ipv6          display only IP version 6 sockets
       -0, --packet        display PACKET sockets
       -t, --tcp           display only TCP sockets
       -u, --udp           display only UDP sockets
       -d, --dccp          display only DCCP sockets
       -w, --raw           display only RAW sockets
       -x, --unix          display only Unix domain sockets
       -f, --family=FAMILY display sockets of type FAMILY

       -A, --query=QUERY, --socket=QUERY
           QUERY := {all|inet|tcp|udp|raw|unix|unix_dgram|unix_stream|unix_seqpacket|packet|netlink}[,QUERY]

       -D, --diag=FILE     Dump raw information about TCP sockets to FILE
       -F, --filter=FILE   read filter information from FILE
           FILTER := [ state STATE-FILTER ] [ EXPRESSION ]
           STATE-FILTER := {all|connected|synchronized|bucket|big|TCP-STATES}
             TCP-STATES := {established|syn-sent|syn-recv|fin-wait-{1,2}|time-wait|closed|close-wait|last-ack|listen|closing}
              connected := {established|syn-sent|syn-recv|fin-wait-{1,2}|time-wait|close-wait|last-ack|closing}
           synchronized := {established|syn-recv|fin-wait-{1,2}|time-wait|close-wait|last-ack|closing}
                 bucket := {syn-recv|time-wait}
                    big := {established|syn-sent|fin-wait-{1,2}|closed|close-wait|last-ack|listen|closing}
    Available.
    Checking UDP port 6667... ss: invalid option -- 'H'
    Usage: ss [ OPTIONS ]
           ss [ OPTIONS ] [ FILTER ]
       -h, --help          this message
       -V, --version       output version information
       -n, --numeric       don't resolve service names
       -r, --resolve       resolve host names
       -a, --all           display all sockets
       -l, --listening     display listening sockets
       -o, --options       show timer information
       -e, --extended      show detailed socket information
       -m, --memory        show socket memory usage
       -p, --processes     show process using socket
       -i, --info          show internal TCP information
       -s, --summary       show socket usage summary
       -b, --bpf           show bpf filter socket information
       -E, --events        continually display sockets as they are destroyed
       -Z, --context       display process SELinux security contexts
       -z, --contexts      display process and socket SELinux security contexts
       -N, --net           switch to the specified network namespace name

       -4, --ipv4          display only IP version 4 sockets
       -6, --ipv6          display only IP version 6 sockets
       -0, --packet        display PACKET sockets
       -t, --tcp           display only TCP sockets
       -u, --udp           display only UDP sockets
       -d, --dccp          display only DCCP sockets
       -w, --raw           display only RAW sockets
       -x, --unix          display only Unix domain sockets
       -f, --family=FAMILY display sockets of type FAMILY

       -A, --query=QUERY, --socket=QUERY
           QUERY := {all|inet|tcp|udp|raw|unix|unix_dgram|unix_stream|unix_seqpacket|packet|netlink}[,QUERY]

       -D, --diag=FILE     Dump raw information about TCP sockets to FILE
       -F, --filter=FILE   read filter information from FILE
           FILTER := [ state STATE-FILTER ] [ EXPRESSION ]
           STATE-FILTER := {all|connected|synchronized|bucket|big|TCP-STATES}
             TCP-STATES := {established|syn-sent|syn-recv|fin-wait-{1,2}|time-wait|closed|close-wait|last-ack|listen|closing}
              connected := {established|syn-sent|syn-recv|fin-wait-{1,2}|time-wait|close-wait|last-ack|closing}
           synchronized := {established|syn-recv|fin-wait-{1,2}|time-wait|close-wait|last-ack|closing}
                 bucket := {syn-recv|time-wait}
                    big := {established|syn-sent|fin-wait-{1,2}|closed|close-wait|last-ack|listen|closing}
    Available.
    Checking TCP port 1883... ss: invalid option -- 'H'
    Usage: ss [ OPTIONS ]
           ss [ OPTIONS ] [ FILTER ]
       -h, --help          this message
       -V, --version       output version information
       -n, --numeric       don't resolve service names
       -r, --resolve       resolve host names
       -a, --all           display all sockets
       -l, --listening     display listening sockets
       -o, --options       show timer information
       -e, --extended      show detailed socket information
       -m, --memory        show socket memory usage
       -p, --processes     show process using socket
       -i, --info          show internal TCP information
       -s, --summary       show socket usage summary
       -b, --bpf           show bpf filter socket information
       -E, --events        continually display sockets as they are destroyed
       -Z, --context       display process SELinux security contexts
       -z, --contexts      display process and socket SELinux security contexts
       -N, --net           switch to the specified network namespace name

       -4, --ipv4          display only IP version 4 sockets
       -6, --ipv6          display only IP version 6 sockets
       -0, --packet        display PACKET sockets
       -t, --tcp           display only TCP sockets
       -u, --udp           display only UDP sockets
       -d, --dccp          display only DCCP sockets
       -w, --raw           display only RAW sockets
       -x, --unix          display only Unix domain sockets
       -f, --family=FAMILY display sockets of type FAMILY

       -A, --query=QUERY, --socket=QUERY
           QUERY := {all|inet|tcp|udp|raw|unix|unix_dgram|unix_stream|unix_seqpacket|packet|netlink}[,QUERY]

       -D, --diag=FILE     Dump raw information about TCP sockets to FILE
       -F, --filter=FILE   read filter information from FILE
           FILTER := [ state STATE-FILTER ] [ EXPRESSION ]
           STATE-FILTER := {all|connected|synchronized|bucket|big|TCP-STATES}
             TCP-STATES := {established|syn-sent|syn-recv|fin-wait-{1,2}|time-wait|closed|close-wait|last-ack|listen|closing}
              connected := {established|syn-sent|syn-recv|fin-wait-{1,2}|time-wait|close-wait|last-ack|closing}
           synchronized := {established|syn-recv|fin-wait-{1,2}|time-wait|close-wait|last-ack|closing}
                 bucket := {syn-recv|time-wait}
                    big := {established|syn-sent|fin-wait-{1,2}|closed|close-wait|last-ack|listen|closing}
    Available.
    Checking TCP port 8886... ss: invalid option -- 'H'
    Usage: ss [ OPTIONS ]
           ss [ OPTIONS ] [ FILTER ]
       -h, --help          this message
       -V, --version       output version information
       -n, --numeric       don't resolve service names
       -r, --resolve       resolve host names
       -a, --all           display all sockets
       -l, --listening     display listening sockets
       -o, --options       show timer information
       -e, --extended      show detailed socket information
       -m, --memory        show socket memory usage
       -p, --processes     show process using socket
       -i, --info          show internal TCP information
       -s, --summary       show socket usage summary
       -b, --bpf           show bpf filter socket information
       -E, --events        continually display sockets as they are destroyed
       -Z, --context       display process SELinux security contexts
       -z, --contexts      display process and socket SELinux security contexts
       -N, --net           switch to the specified network namespace name

       -4, --ipv4          display only IP version 4 sockets
       -6, --ipv6          display only IP version 6 sockets
       -0, --packet        display PACKET sockets
       -t, --tcp           display only TCP sockets
       -u, --udp           display only UDP sockets
       -d, --dccp          display only DCCP sockets
       -w, --raw           display only RAW sockets
       -x, --unix          display only Unix domain sockets
       -f, --family=FAMILY display sockets of type FAMILY

       -A, --query=QUERY, --socket=QUERY
           QUERY := {all|inet|tcp|udp|raw|unix|unix_dgram|unix_stream|unix_seqpacket|packet|netlink}[,QUERY]

       -D, --diag=FILE     Dump raw information about TCP sockets to FILE
       -F, --filter=FILE   read filter information from FILE
           FILTER := [ state STATE-FILTER ] [ EXPRESSION ]
           STATE-FILTER := {all|connected|synchronized|bucket|big|TCP-STATES}
             TCP-STATES := {established|syn-sent|syn-recv|fin-wait-{1,2}|time-wait|closed|close-wait|last-ack|listen|closing}
              connected := {established|syn-sent|syn-recv|fin-wait-{1,2}|time-wait|close-wait|last-ack|closing}
           synchronized := {established|syn-recv|fin-wait-{1,2}|time-wait|close-wait|last-ack|closing}
                 bucket := {syn-recv|time-wait}
                    big := {established|syn-sent|fin-wait-{1,2}|closed|close-wait|last-ack|listen|closing}
    Available.
    ======================================================
      Starting AP in a screen.
      Starting web server in a screen
      Starting Mosquitto in a screen
      Starting PSK frontend in a screen
      Starting Tuya Discovery in a screen

    ======================================================

This was using a USB wifi cisco linksys WUSB54GC ver.3.

**Comment by joshgarde** [comment]
What a strange coincidence - I'm running the same environment with the same USB wifi hardware lol
