### ISSUE TITLE
Bneta Gu10 downlight not flashing

### ISSUE THREAD

**Issue by HellfireZA** [ct-Open-Source/tuya-convert#626]
I'm having trouble flashing the mentioned bulb, I'm also unsure how to attain the logs so could someone please help me with that.

I'm running on Ubuntu 16.04 and have Tuya-convert setup correctly AFAIK, I'm able to connect my phone to the flash network and it says "connected". I then put the bulb into flash mode and it definitely links up to "vtrust-flash" in seconds but doesn't go any further. I can see it on the vtrust-flash network using the Fing app and am able to ping it without a problem. I then changed the IPs in the config from 10.42.42.42 to 10.42.42.22 and it does seem to communicate but connection is refused when backing up and attempting to write firmware. 

Any help would be gladly appreciated. 

EDIT: I see no logs in my script folder.

**Comment by kueblc** [comment]
Check for logs in your backup folder

**Comment by HellfireZA** [comment]
> Check for logs in your backup folder

I checked my backup folder and a folder is generated it seems every time the bulb does connect to vtrust-flash, all folders are empty though. I've attached screenshots of the backup folder and then what happens the moment I run start_flash.sh

![Screenshot from 2020-05-18 08-58-02](https://user-images.githubusercontent.com/27960351/82184124-63f3a280-98e7-11ea-8b42-45232460570d.png)
![Screenshot from 2020-05-18 09-08-11](https://user-images.githubusercontent.com/27960351/82184135-65bd6600-98e7-11ea-8f6a-3ea1b2ef6653.png)

**Comment by HellfireZA** [comment]
I went and bought another bulb from local vendor and same thing, connection refused but it hooks onto the vtrust-flash network perfectly.

**Comment by kueblc** [comment]
Looks like you have an older version of `ss`, and so it is failing to check for occupied ports.

Check those ports manually to make sure they are available, otherwise the software may not be able to start successfully.

**Comment by kueblc** [comment]
Also, do not change the IP in the scripts from `10.42.42.42`. It must remain so.

**Comment by HellfireZA** [comment]
So an update, I reinstalled Ubuntu to 18.04.4 and everything worked perfectly, I think it was the occupied ports, seemed that Python was using them. Thank you for your help and your work!

**Comment by kueblc** [comment]
Excellent! Glad you got it working

**Comment by aquarat** [comment]
Hi

I hope it's okay if I post something to this closed issue: @HellfireZA did you flash Tasmota to your BNeta GU10 device? and if so, what template did you use to control it?

**Comment by HellfireZA** [comment]
Hi @aquarat I did to over 30 bulbs now. 
I did experience two different variants of the bulb though.

What you can do is use "generic" and then manually select each pin according to what Tasmota recommends for the Gu10, I found that for one variant of the bulb used: https://templates.blakadder.com/bneta_IO-WIFI60-E27P.html

and the other, the correct gu10: https://templates.blakadder.com/bneta_IO-WIFI-GU10S.html

**Comment by aquarat** [comment]
Thanks for the info @HellfireZA, yes I've gone and bought 30 of them too haha, so much flashing.
