### ISSUE TITLE
tuya curtain switch device did not appear 

### ISSUE THREAD

**Issue by savasoskan** [ct-Open-Source/tuya-convert#629]
Hi 
I'm new here and I have little experience, 
I usually use my relays with esphome but my new switches are connected to the tuya platform.
I couldn't pair when writing flash
ı use 
win 10 x64
paspberry pi 4 B
curtain switch ( tywe2s wifi module )

pls help :)

======================================================
Starting smart config pairing procedure
Waiting for the device to install the intermediate firmware
Put device in EZ config mode (blinking fast)
Sending SSID vtrust-flash
Sending wifiPassword
Sending token 00000000
Sending secret 0101
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
................
Device did not appear with the intermediate firmware
Check the *.log files in the scripts folder
Stopping smart config

Do you want to flash another device? [y/N]

[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/4647516/smarthack-psk.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/4647517/smarthack-web.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/4647518/smarthack-mqtt.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/4647519/smarthack-wifi.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/4647520/smarthack-udp.log)

**Comment by kueblc** [comment]
Unfortunately you have a device with patched firmware which is not currently supported. See #483 for more information and hopefully an eventual workaround.
