### ISSUE TITLE
Device did not appear with the intermediate firmware - Name: Novadigital - Model: WK-BR

### ISSUE THREAD

**Issue by estevaoc** [ct-Open-Source/tuya-convert#635]
Hello there!

I am trying to flash a smart plug by a brazilian brand called Novadigital, model WK-BR. I am using a raspberry pi 3 and a NodeMCU as the donor device.

Like some other people, I am also stuck with the message "Device did not appear with the intermediate firmware". I have tried it many times without success.

Can you help me understand what could be the issue? Find the logs below.

Thank you!

[smarthack-mqtt.txt](https://github.com/ct-Open-Source/tuya-convert/files/4670188/smarthack-mqtt.txt)
[smarthack-psk.txt](https://github.com/ct-Open-Source/tuya-convert/files/4670189/smarthack-psk.txt)
[smarthack-udp.txt](https://github.com/ct-Open-Source/tuya-convert/files/4670190/smarthack-udp.txt)
[smarthack-web.txt](https://github.com/ct-Open-Source/tuya-convert/files/4670191/smarthack-web.txt)
[smarthack-wifi.txt](https://github.com/ct-Open-Source/tuya-convert/files/4670192/smarthack-wifi.txt)

**Comment by kueblc** [comment]
Unfortunately your firmware has been patched by Tuya, see #483
