### ISSUE TITLE
Gosund SP112 FW: 1.1.3 problem - always Resending SmartConfig Packets

### ISSUE THREAD

**Issue by stefan-schwarz** [ct-Open-Source/tuya-convert#639]
**Problem Description:**
I have tried to flash the Gosund SP112 with Firmware 1.1.3 over the air, however it always loops through Resending SmartConfig Packets. 
I can connect to the AP opened by raspberry Pi 4 with either my ipad or iphone. However short after executing ./start_flash.sh the Gosund Plug turns from quickly flashing blue into normal constant red light.

I've already checked some things on the web:
- I am using a freshly installed Raspberry PI 4
- Firewall is off
- Apache is stopped when I run ./start_flash.sh

**Logs**
I've found an interesting Part in the smarthack-psk.log:
```
PSK: 3605d2d9f08c921f68dbd9541c39cc835df74c797ccd5e92b3ab31b4ccef5f5a
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.39:13529
ID: 0242416f68626d64366147393149465231a6d1c174fce49ade3adb64bc58eb08234aae2818d8f68e53a493856cbc3988e7
PSK: 3605d2d9f08c921f68dbd9541c39cc835df74c797ccd5e92b3ab31b4ccef5f5a
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.39:23436
```

[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/4671902/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/4671903/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/4671904/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/4671905/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/4671906/smarthack-wifi.log)

Thanks for your help!

**Comment by kueblc** [comment]
Unfortunately your device has patched firmware, note the PSK ID starting with `02`. Follow #483 for more information and hopefully an eventual resolution.
