### ISSUE TITLE
BlitzWolf BW-RC1 and firmware too large

### ISSUE THREAD

**Issue by eliafino** [ct-Open-Source/tuya-convert#647]
https://templates.blakadder.com/blitzwolf_BW-RC1.html

"You can also provide your own image by placing it in the /files directory"
"Please ensure the firmware fits the device and includes the bootloader"
"MAXIMUM SIZE IS 512KB"

But file http://thehackbox.org/tasmota/release/tasmota-ir.bin is 566KB (580240) so no flash possible

**Comment by kueblc** [comment]
Correct. You must flash the included Tasmota first, and then upgrade to your desired build from there.

**Comment by eliafino** [comment]
Thank you very much!
