### ISSUE TITLE
new style Merkury Plug - MI-WW218 - Not able to flash. What is this chip? Pics/Logs

### ISSUE THREAD

**Issue by ctrl50** [ct-Open-Source/tuya-convert#649]
Hey got some new merkury plugs that wont flash.

Opened one up and This is what I have:

I have a CP2102 will I be able to flash it? Not even sure what chip this is. Google isnt finding much on the p/n and  model# 219979
![20200529_161216](https://user-images.githubusercontent.com/51256504/83312999-4e288c00-a1c9-11ea-9cf8-ebf37bc9be07.jpg)
![20200529_151435](https://user-images.githubusercontent.com/51256504/83313005-51237c80-a1c9-11ea-82e5-b92778be5335.jpg)
![20200529_162105](https://user-images.githubusercontent.com/51256504/83313016-58e32100-a1c9-11ea-8f5d-7750c067caf3.jpg)

logs:
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/4704745/smarthack-wifi.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/4704746/smarthack-web.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/4704747/smarthack-udp.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/4704748/smarthack-psk.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/4704749/smarthack-mqtt.log)

Anyone have any Info on this? Should i hook it up to teh cp2102 and see what happens or is this a non-flashable chip?

never flashed any esp stuff with serial.. so any pointers? tasmotizer?

**Comment by ctrl50** [comment]
by the way.. they dont want you opening this thing.. it took a while with a hacksaw.. its salvagable.. but its not pretty.

**Comment by kueblc** [comment]
Unfortunately this is not an ESP82xx as evidenced by the MAC address. You will not be able to install ESP82xx firmware (Tasmota, Espurna, etc) on this device. Sorry to be the bearer of bad news!

**Comment by ctrl50** [comment]
alright.. well that sucks.. RIP cheap merkury plugs.. Guessing they will update the lights to this chip next.

Thanks.

**Comment by Didgeridrew** [comment]
> alright.. well that sucks.. RIP cheap Merkury plugs.. Guessing they will update the lights to this chip next.

They have updated the bulbs now... at least mine are.

#692

**Comment by ctrl50** [comment]
> > alright.. well that sucks.. RIP cheap Merkury plugs.. Guessing they will update the lights to this chip next.
> 
> They have updated the bulbs now... at least mine are.
> 
> #692

Yup. I got some with the WB2L that wont flash.

![20200824_224939 (1)](https://user-images.githubusercontent.com/51256504/95659638-32b68180-0ad7-11eb-9a25-a779d5834c6f.jpg)
