### ISSUE TITLE
cannot flash Gosund bulb WB4

### ISSUE THREAD

**Issue by itsme2465** [ct-Open-Source/tuya-convert#654]
Hi,

trying to flash a Gosund WB4 I always get the following:

======================================================
Starting smart config pairing procedure
Waiting for the device to install the intermediate firmware
Put device in EZ config mode (blinking fast)
Sending SSID                  vtrust-flash
Sending wifiPassword
Sending token                 00000000
Sending secret                0101
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
............
Device did not appear with the intermediate firmware
Check the *.log files in the scripts folder
Do you want to try flashing another device? [y/N]

The bulb stays blinking fast.

Please help!
[Logs.zip](https://github.com/ct-Open-Source/tuya-convert/files/4705745/Logs.zip)

**Comment by kueblc** [comment]
Unfortunately this firmware version is unsupported, see #483
