### ISSUE TITLE
Flashed Deltaco SH-LE27RGB No Wifi AP to config

### ISSUE THREAD

**Issue by InterceptorDK** [ct-Open-Source/tuya-convert#662]
Used Raspberry Pi with Tuya convert OS.
Flashed the bulb fine.
Bulb turned off and no wifi AP to connect to never came.
Now it just seems dead.

Bulb had been on the Smartlife app beforehand.

**Comment by kueblc** [comment]
Not a tuya-convert issue, please seek support from the firmware provider
