### ISSUE TITLE
Resending packets without success

### ISSUE THREAD

**Issue by alexmc1510** [ct-Open-Source/tuya-convert#663]
### Before opening a new issue, please read the following

**Are you reporting a successful flash?**
No

**Do you have a question about configuring your newly flashed device?**
No

**Did you have issues getting a device to flash?**
Yes.
Smart WiFi Plug Adaptor 16A Remote Voice Control Power Monitor Socket Outlet Timing Function work with Alexa Google Home Tuya
https://www.aliexpress.com/item/4000060646437.html?spm=a2g0s.9042311.0.0.49ad63c0NARO3N

[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/4753481/smarthack-wifi.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/4753482/smarthack-web.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/4753483/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/4753484/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/4753485/smarthack-udp.log)

**Please remember to close your issue when the problem has been addressed!**

**Comment by kueblc** [comment]
Unfortunately this device cannot be converted as it does not use an ESP82xx.

From your web log:
```
WARNING: it appears this device does not use an ESP82xx and therefore cannot install ESP based firmware
```
