### ISSUE TITLE
Gosund SP112 does not flash

### ISSUE THREAD

**Issue by stefan242** [ct-Open-Source/tuya-convert#664]
I have already flashed 5 Gosund SP112 without problems in january/february. 
The two latest SP112 , ordered from Amazon one week ago, cannot be flashed. I did a complete reinstall of my Raspi and flashed a RM mini and two Maxcio plugs afterwards without any problem.

Both SP112 do blink when pressed for 7 seconds, but the blinking turns off very quickly, when tuya-convert is running. When it is not running the LED blinks forever.
Both plugs switch on/off the output with a red light, when on (=not configured).

[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/4754262/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/4754263/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/4754264/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/4754265/smarthack-wifi.log)

**Comment by kueblc** [comment]
Duplicate #483
