### ISSUE TITLE
question : Tuya convert tuya zigbee gateway

### ISSUE THREAD

**Issue by ngok31** [ct-Open-Source/tuya-convert#668]
Hello,

I am quite new to IoT Tuya Home assisstant and more.
There is sevrals Tuya Zigbee Gateway available in the market.
Is there a way or a project to make tuya-convert works with one of these Tuya Zigbee Gateway ?
It will be a great thing.
Thanks

**Comment by kueblc** [comment]
There is no way to know for certain until you try.

You can check the wiki to see if anyone else has had success with such a device. If you manage to get the MAC address of the device you want to flash, you can verify it's OUI to see if it is "Espressif Inc.". We only support ESP82xx devices.

Even if these are both true, it is not guaranteed to flash as Tuya may have updated the firmware to block `tuya-convert` for any given device.
