### ISSUE TITLE
Unable to flash DOGAIN E12 Smart Bulbs

### ISSUE THREAD

**Issue by lonestriker** [ct-Open-Source/tuya-convert#669]
I've been able to flash other devices using my current setup (RGB smart bulbs as well as smart plugs).  
The bulbs are listed as being [Tasmota compatible.](https://templates.blakadder.com/dogain-4_5w.html)

Device bought from Amazon: [DOGAIN Smart Bulbs.](https://www.amazon.com/Candelabra-Changing-Compatible-Chandelier-Equivalent/dp/B07WGL5L8Q/ref=pd_sbs_60_5/147-8472797-5931618?_encoding=UTF8&pd_rd_i=B07WGL5L8Q&pd_rd_r=586c5f37-9650-4ef3-8446-39107b0a9c1b&pd_rd_w=aceAg&pd_rd_wg=iegzw&pf_rd_p=665be1f4-8d3b-46dd-91b4-582d3cec8dd6&pf_rd_r=HV58HP6NCTKZW0PXC1S1&psc=1&refRID=HV58HP6NCTKZW0PXC1S1)

The two bulbs' MAC address shows as being owned by [Espressif Inc.](https://aruljohn.com/mac/D8BFC0C660F4) and [second one.](https://aruljohn.com/mac/D8BFC0C6B740)

My logs:
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/4777173/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/4777174/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/4777175/smarthack-wifi.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/4777176/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/4777177/smarthack-psk.log)

Thanks!

Edit:
The bulbs are flashing on and off before I start the script, once the script runs, the bulb stops flashing but never completes.  Similar to other's reports of not being able to flash with the wrong MAC address, not owned by Espressif.  But mine appear to be at least owned by Espressif, just not able to flash.

Edit2:
Appears my issue is one that's being worked on and [tracked here](https://github.com/ct-Open-Source/tuya-convert/issues/483).  If that's the case, I can close this issue and track it in the #483 instead.

**Comment by kueblc** [comment]
You are correct, your device is using an update and yet unsupported PSK

Thanks for reporting, keep an eye on #483 for progress
