### ISSUE TITLE
Introduce a list of unsupported devices

### ISSUE THREAD

**Issue by maichai** [ct-Open-Source/tuya-convert#699]
### Before opening a new issue, please read the following

**Are you reporting a successful flash?**
No

**Do you have a question about configuring your newly flashed device?**
No

**Did you have issues getting a device to flash?**
Yes

**Please remember to close your issue when the problem has been addressed!**

More recently I am coming across more devices that have unsupported firmware, but they are not yet known in the Blakadder database or in your list of supported devices. 
Should we have a list of unsupported devices here to document this knowledge and spare others the hassle of buying and sending back devices that are not supported? (The unsupported devices category in the Blakadder DB does not match this, since it is there only categorized as unsupported, if it cannot be flashed using any means, e.g. also serial does not work. I do not even try that - if it does not work with tuya-convert I return the item and would be happy to know in advance that the device does not work with tuya-convert).

**Comment by kueblc** [comment]
The first column on the wiki is "supported?". If you think you need more, go ahead, the wiki is public.
