### ISSUE TITLE
Issue Flashing new Version of Novostella LED Flood Light

### ISSUE THREAD

**Issue by Schlabberanesi** [ct-Open-Source/tuya-convert#700]
I succesfully flashed such lights 2 weeks ago. This time, it doesnt work. The light stops blinking, but nothing changes. It might be the same issue as in https://github.com/ct-Open-Source/tuya-convert/issues/483

PSK shows the following:
ID: 0242416f68626d6436614739314946523173106c1b5b6c27c3886116567b35e847ffa4b2ab4ab64e1704d1f260d7b85a31
PSK: 165bbd09dc3281cb53b181846b026bc958b4283dee0dbdb43341b1fc155d34b5
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad$

I added all logs bellow. I dont know what to do next - help would be great!

pi@raspberrypi:~/tuya-convert $ ./start_flash.sh
tuya-convert v2.4.4
Checking for network interface wlan0... Found.
Checking UDP port 53... Available.
Checking UDP port 67... Available.
Checking TCP port 80... Available.
Checking TCP port 443... Available.
Checking UDP port 6666... Available.
Checking UDP port 6667... Available.
Checking TCP port 1883... Available.
Checking TCP port 8886... Available.
======================================================
  Starting AP in a screen
  Starting web server in a screen
  Starting Mosquitto in a screen
  Starting PSK frontend in a screen
  Starting Tuya Discovery in a screen

======================================================

IMPORTANT
1. Connect any other device (a smartphone or something) to the WIFI vtrust-flash
   This step is IMPORTANT otherwise the smartconfig may not work!
2. Put your IoT device in autoconfig/smartconfig/pairing mode (LED will blink fast). This i            s usually done by pressing and holding the primary button of the device
   Make sure nothing else is plugged into your IoT device while attempting to flash.
3. Press ENTER to continue

======================================================
Starting smart config pairing procedure
Waiting for the device to install the intermediate firmware
Put device in EZ config mode (blinking fast)
Sending SSID                  vtrust-flash
Sending wifiPassword
Sending token                 00000000
Sending secret                0101
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
.............
Device did not appear with the intermediate firmware
Check the *.log files in the scripts folder
Do you want to try flashing another device? [y/N] n
======================================================
Cleaning up...
Closing AP
Exiting...

%%%%%%%%%%%%%  smarthack-wifi.log

System info
===========
94acc3b
Linux raspberrypi 4.19.118-v7+ #1311 SMP Mon Apr 27 14:21:24 BST 2020 armv7l GNU/Linux
OpenSSL 1.1.1d  10 Sep 2019
Dnsmasq version 2.80  Copyright (c) 2000-2018 Simon Kelley
Compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipse$

This software comes with ABSOLUTELY NO WARRANTY.
Dnsmasq is free software, and you are welcome to redistribute it
under the terms of the GNU General Public License, version 2 or 3.
hostapd v2.8-devel
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Python 3.7.3
===========
Attempting to stop wpa_supplicant
Configuring AP interface...
RTNETLINK answers: File exists
Starting DNSMASQ server...
Starting AP on wlan0...
Configuration file: /dev/stdin

%%%%%%%%%%%%%  smarthack-web.log

Listening on 10.42.42.1:80
^[[32m[I 200715 22:35:48 web:2250]^[[m^O 302 GET /hotspot-detect.html (10.42.42.25) 4.33ms
^[[32m[I 200715 22:35:48 web:2250]^[[m^O 200 GET / (10.42.42.25) 5.18ms
^[[32m[I 200715 22:35:51 web:2250]^[[m^O 302 GET /hotspot-detect.html (10.42.42.25) 2.84ms
^[[32m[I 200715 22:35:51 web:2250]^[[m^O 200 GET / (10.42.42.25) 3.11ms
^[[32m[I 200715 22:35:51 web:2250]^[[m^O 302 GET /hotspot-detect.html (10.42.42.25) 3.21ms
^[[32m[I 200715 22:35:51 web:2250]^[[m^O 200 GET / (10.42.42.25) 3.44ms
^[[32m[I 200715 22:36:02 web:2250]^[[m^O 302 GET /hotspot-detect.html (10.42.42.25) 3.44ms
^[[32m[I 200715 22:36:02 web:2250]^[[m^O 200 GET / (10.42.42.25) 3.29ms
^[[32m[I 200715 22:36:03 web:2250]^[[m^O 302 GET /hotspot-detect.html (10.42.42.25) 3.01ms
^[[32m[I 200715 22:36:03 web:2250]^[[m^O 200 GET / (10.42.42.25) 3.96ms
^[[32m[I 200715 22:36:03 web:2250]^[[m^O 302 GET /hotspot-detect.html (10.42.42.25) 3.62ms
^[[32m[I 200715 22:36:03 web:2250]^[[m^O 200 GET / (10.42.42.25) 3.79ms
^CReceived SIGINT, exiting...
Listening on 10.42.42.1:80
^CReceived SIGINT, exiting...
Listening on 10.42.42.1:80
^CReceived SIGINT, exiting...
^CListening on 10.42.42.1:80
^CReceived SIGINT, exiting...
Listening on 10.42.42.1:80
^CReceived SIGINT, exiting...

%%%%%%%%%%%%%  smarthack-web.mqtt

1594848935: mosquitto version 1.5.7 starting
1594848935: Using default config.
1594848935: Opening ipv4 listen socket on port 1883.
1594848935: Opening ipv6 listen socket on port 1883.
^C1594849064: mosquitto version 1.5.7 terminating
1594849292: mosquitto version 1.5.7 starting
1594849292: Using default config.
1594849292: Opening ipv4 listen socket on port 1883.
1594849292: Opening ipv6 listen socket on port 1883.
^C1594849711: mosquitto version 1.5.7 terminating
1594849743: mosquitto version 1.5.7 starting
1594849743: Using default config.
1594849743: Opening ipv4 listen socket on port 1883.
1594849743: Opening ipv6 listen socket on port 1883.
^C^C1594849753: mosquitto version 1.5.7 terminating
1594850644: mosquitto version 1.5.7 starting
1594850644: Using default config.
1594850644: Opening ipv4 listen socket on port 1883.
1594850644: Opening ipv6 listen socket on port 1883.
^C1594850769: mosquitto version 1.5.7 terminating
1594851053: mosquitto version 1.5.7 starting
1594851053: Using default config.
1594851053: Opening ipv4 listen socket on port 1883.

%%%%%%%%%%%%%  smarthack-web.udp

Listening for Tuya broadcast on UDP 6666
Listening for encrypted Tuya broadcast on UDP 6667
^CListening for Tuya broadcast on UDP 6666
Listening for encrypted Tuya broadcast on UDP 6667
^CListening for Tuya broadcast on UDP 6666
Listening for encrypted Tuya broadcast on UDP 6667
^C^CListening for Tuya broadcast on UDP 6666
Listening for encrypted Tuya broadcast on UDP 6667
^CListening for Tuya broadcast on UDP 6666
Listening for encrypted Tuya broadcast on UDP 6667
^C

%%%%%%%%%%%% nano scripts/smarthack-psk.log

new client on port 443 from 10.42.42.25:57209
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1056)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.25:57210
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1056)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.25:57211
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1056)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.25:57212
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1056)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.25:57213
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1056)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.25:57214
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1056)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.25:57218
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1056)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.25:57219
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1056)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.25:57220
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1056)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.36:32635
ID: 0242416f68626d6436614739314946523173106c1b5b6c27c3886116567b35e847ffa4b2ab4ab64e1704d1f260d7b85a31
PSK: 165bbd09dc3281cb53b181846b026bc958b4283dee0dbdb43341b1fc155d34b5
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad$
new client on port 443 from 10.42.42.36:30070
ID: 0242416f68626d6436614739314946523173106c1b5b6c27c3886116567b35e847ffa4b2ab4ab64e1704d1f260d7b85a31
PSK: 165bbd09dc3281cb53b181846b026bc958b4283dee0dbdb43341b1fc155d34b5
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad$
new client on port 443 from 10.42.42.36:2563
ID: 0242416f68626d6436614739314946523173106c1b5b6c27c3886116567b35e847ffa4b2ab4ab64e1704d1f260d7b85a31

**Comment by Schlabberanesi** [comment]
IP 10.42.42.25 is my phone, 10.42.42.36 is the light in question

**Comment by kueblc** [comment]
Currently not possible to flash OTA. See #483

**Comment by ethank** [comment]
I love these lights. I bought 6 and flashed them successfully. Where'd you buy them from where the firmware was changed to not support OTA? I might buy some to just convert them for the future.

**Comment by Schlabberanesi** [comment]
From Amazon DE

**Comment by tt-appdev** [comment]
@kueblc Having the same issue. I've seen you suggest using Wireshark while configuring with API, do you have general instruction for this or any other advice for capturing the necessary data? Im an application developer by day and its been years since I've had to use Wireshark but happy to help in any way possible

**Comment by TATERxxWARDY** [comment]
@kueblc Having the same issue. I've seen you suggest using Wireshark while configuring with API, do you have general instruction for this or any other advice for capturing the necessary data? Im an application developer by day and its been years since I've had to use Wireshark but happy to help in any way possible

**Comment by kueblc** [comment]
Hi @TATERxxWARDY, I appreciate your willingness to help. We currently have more than enough data to look at right now, unless you happen to have a device of the same model with older firmware.

**Comment by TATERxxWARDY** [comment]
@kueblc I do not, sorry
