### ISSUE TITLE
Cannot Flash Arlec Smart Bulb

### ISSUE THREAD

**Issue by Nickdee7** [ct-Open-Source/tuya-convert#701]
Hi All, 

I have flashed devices successfully with the Tasmota firmware for ESP8266 devices that I have. However, I am trying to flash [this device]([https://templates.blakadder.com/arlec_GLD110HA.html]) now with no luck. 

Here are details from log files:
**smarthack-psk.log**
_new client on port 443 from 10.42.42.30:32338
ID: 0242416f68626d6436614739314946523155a5777e28d7dd773368a10d1f54ec4180b7ce247f274bc2703daaf57ad76ab4
PSK: d72a99042f58345901c799d8440316079e9272f2bc3025c632f3c97700ce8282
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:852)
new client on port 443 from 10.42.42.40:40474
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:852)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.40:40480
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:852)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.40:40484
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:852)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.40:40486
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:852)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.30:41555
ID: 0242416f68626d6436614739314946523155a5777e28d7dd773368a10d1f54ec4180b7ce247f274bc2703daaf57ad76ab4
PSK: d72a99042f58345901c799d8440316079e9272f2bc3025c632f3c97700ce8282
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:852)
new client on port 443 from 10.42.42.40:40494
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:852)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.30:18461
ID: 0242416f68626d6436614739314946523155a5777e28d7dd773368a10d1f54ec4180b7ce247f274bc2703daaf57ad76ab4
PSK: d72a99042f58345901c799d8440316079e9272f2bc3025c632f3c97700ce8282
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:852)
new client on port 443 from 10.42.42.30:13712
ID: 0242416f68626d6436614739314946523155a5777e28d7dd773368a10d1f54ec4180b7ce247f274bc2703daaf57ad76ab4
PSK: d72a99042f58345901c799d8440316079e9272f2bc3025c632f3c97700ce8282
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:852)
new client on port 443 from 10.42.42.30:40919
ID: 0242416f68626d6436614739314946523155a5777e28d7dd773368a10d1f54ec4180b7ce247f274bc2703daaf57ad76ab4
PSK: d72a99042f58345901c799d8440316079e9272f2bc3025c632f3c97700ce8282
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:852)
new client on port 443 from 10.42.42.30:3893
ID: 0242416f68626d6436614739314946523155a5777e28d7dd773368a10d1f54ec4180b7ce247f274bc2703daaf57ad76ab4
PSK: d72a99042f58345901c799d8440316079e9272f2bc3025c632f3c97700ce8282
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:852)__

**smarthack-wifi.log**
_Attempting to stop wpa_supplicant
Stopping NetworkManager...
Configuring AP interface...
RTNETLINK answers: File exists
Starting DNSMASQ server...
Starting AP on wlx0013ef6a83ef...
Configuration file: /dev/stdin
Using interface wlx0013ef6a83ef with hwaddr 00:13:ef:6a:83:ef and ssid "vtrust-flash"
wlx0013ef6a83ef: interface state UNINITIALIZED->ENABLED
wlx0013ef6a83ef: AP-ENABLED 
wlx0013ef6a83ef: AP-STA-CONNECTED 7a:36:d3:59:d2:80
wlx0013ef6a83ef: AP-STA-CONNECTED f4:cf:a2:55:c6:29
wlx0013ef6a83ef: AP-STA-CONNECTED f4:cf:a2:55:c6:29
wlx0013ef6a83ef: interface state ENABLED->DISABLED
wlx0013ef6a83ef: AP-STA-DISCONNECTED f4:cf:a2:55:c6:29
wlx0013ef6a83ef: AP-STA-DISCONNECTED 7a:36:d3:59:d2:80
wlx0013ef6a83ef: AP-DISABLED 
nl80211: deinit ifname=wlx0013ef6a83ef disabled_11b_rates=0
AP closed_
Here f4 is the bulb, 7a is my phone. 

**smarthack-udp.log** 
_Listening for Tuya broadcast on UDP 6666
Listening for encrypted Tuya broadcast on UDP 6667_

**smarthack-mqtt.log**
_1594905688: mosquitto version 1.4.15 (build date Tue, 18 Jun 2019 11:42:22 -0300) starting
1594905688: Using default config.
1594905688: Opening ipv4 listen socket on port 1883.
1594905688: Opening ipv6 listen socket on port 1883.
^C1594905980: mosquitto version 1.4.15 terminating_

I have seen others report this issue, but cannot find a solution that has been posted on those issue reports. Can someone please help? I am fairly new to this. Please let me know if there is any further information that I need to provide that might help with troubleshooting. Thanks in advance.

**Comment by kueblc** [comment]
Currently not possible to flash OTA. See #483
