### ISSUE TITLE
Gosund SP112 not flashing

### ISSUE THREAD

**Issue by serge13232** [ct-Open-Source/tuya-convert#702]
I have a new set of Gosund SP112: https://www.amazon.de/Gosund-USB-Anschl%C3%BCssen-%C3%BCberspannungsschutz-Stimmenkontrolle-Fernsteurung/dp/B07PPZS351

With my first set of the same Plugs this worked.
I have a rpi b+ with wifi dongle.

AP is set.
Plug is flashing fast.
I was first connecting with my mobile phone to vtrust.

When i hit -ENTER- in the console the plug turns off very fast.

logs: https://mega.nz/folder/WIRGnA7B#fooPLwT0NIGuPbXAxCSoRQ

**Comment by kueblc** [comment]
Currently not possible to flash OTA. See #483

**Comment by malheleco** [comment]
Also already updated this in the Wiki as I encountered the same problem as @serge13232 .
