### ISSUE TITLE
Stuck on 'Attempting to flash tasmota.bin, this may take a few seconds...'

### ISSUE THREAD

**Issue by Draxter** [ct-Open-Source/tuya-convert#709]
The process is getting stuck after chosing the bin to flash with, I have given it about 15 minutes and eventually had to exit with ctrl+c. The device in question is this: https://templates.blakadder.com/julun_JL-021.html

After rebooting the device it comes back with a vtrust-recovery SSID.

Terminal Output:

Starting smart config pairing procedure
Waiting for the device to install the intermediate firmware
Put device in EZ config mode (blinking fast)
Sending SSID                  vtrust-flash
Sending wifiPassword
Sending token                 00000000
Sending secret                0101
................
SmartConfig complete.
Resending SmartConfig Packets
...................................
IoT-device is online with ip 10.42.42.42
Fetching firmware backup
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1024k  100 1024k    0     0  63879      0  0:00:16  0:00:16 --:--:-- 28970
curl: Saved to filename 'firmware-4be7a.bin'
======================================================
Getting Info from IoT-device
VTRUST-FLASH 1.5
(c) VTRUST GMBH https://www.vtrust.de/35c3/
READ FLASH: http://10.42.42.42/backup
ChipID: 4be7a
MAC: D8:F1:5B:04:BE:7A
BootVersion: 7
BootMode: normal
FlashMode: 1M QIO @ 40MHz
FlashChipId: 144068
FlashChipRealSize: 1024K
Active Userspace: user2 0x81000
======================================================
Ready to flash third party firmware!

For your convenience, the following firmware images are already included in this repository:
  Tasmota v8.1.0.2 (wifiman)
  ESPurna 1.13.5 (base)

You can also provide your own image by placing it in the /files directory
Please ensure the firmware fits the device and includes the bootloader
MAXIMUM SIZE IS 512KB

Available options:
  0) return to stock
  1) flash espurna.bin
  2) flash tasmota.bin
  q) quit; do nothing
Please select 0-2: 2
Are you sure you want to flash tasmota.bin? This is the point of no return [y/N] y
Attempting to flash tasmota.bin, this may take a few seconds...

LOGS:

smarthack-psk.log:
new client on port 443 from 10.42.42.39:51552
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1056)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.39:51553
new client on port 443 from 10.42.42.39:51557
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1056)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.10:142
ID: 0142416f68626d64366147393149465231ebf4aa7a36fe5b93a3557fa68e4b1a845fcaeb57ecf83a187b59927ffeccb1f30d
PSK: d53840ac1fd766145f29a60a74d7c68ffc75fbfe4f02c45a0133ddd229305dcf
new client on port 443 from 10.42.42.10:30664
ID: 0142416f68626d64366147393149465231ebf4aa7a36fe5b93a3557fa68e4b1a845fcaeb57ecf83a187b59927ffeccb1f30d
PSK: d53840ac1fd766145f29a60a74d7c68ffc75fbfe4f02c45a0133ddd229305dcf
new client on port 443 from 10.42.42.10:30233
ID: 0142416f68626d64366147393149465231ebf4aa7a36fe5b93a3557fa68e4b1a845fcaeb57ecf83a187b59927ffeccb1f30d
PSK: d53840ac1fd766145f29a60a74d7c68ffc75fbfe4f02c45a0133ddd229305dcf
new client on port 8886 from 10.42.42.10:20987
ID: 0142416f68626d64366147393149465231ebf4aa7a36fe5b93a3557fa68e4b1a845fcaeb57ecf83a187b59927ffeccb1f30d
PSK: d53840ac1fd766145f29a60a74d7c68ffc75fbfe4f02c45a0133ddd229305dcf
new client on port 443 from 10.42.42.10:12283
ID: 0142416f68626d64366147393149465231ebf4aa7a36fe5b93a3557fa68e4b1a845fcaeb57ecf83a187b59927ffeccb1f30d
PSK: d53840ac1fd766145f29a60a74d7c68ffc75fbfe4f02c45a0133ddd229305dcf
new client on port 443 from 10.42.42.39:51558
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1056)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.39:51559
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1056)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.10:31409
ID: 0142416f68626d64366147393149465231ebf4aa7a36fe5b93a3557fa68e4b1a845fcaeb57ecf83a187b59927ffeccb1f30d
PSK: d53840ac1fd766145f29a60a74d7c68ffc75fbfe4f02c45a0133ddd229305dcf
new client on port 443 from 10.42.42.10:18607
ID: 0142416f68626d64366147393149465231ebf4aa7a36fe5b93a3557fa68e4b1a845fcaeb57ecf83a187b59927ffeccb1f30d
PSK: d53840ac1fd766145f29a60a74d7c68ffc75fbfe4f02c45a0133ddd229305dcf
new client on port 443 from 10.42.42.39:51561
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1056)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.39:51562
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1056)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.39:51563
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1056)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.10:3187
ID: 0142416f68626d64366147393149465231ebf4aa7a36fe5b93a3557fa68e4b1a845fcaeb57ecf83a187b59927ffeccb1f30d
PSK: d53840ac1fd766145f29a60a74d7c68ffc75fbfe4f02c45a0133ddd229305dcf
new client on port 443 from 10.42.42.10:8340
ID: 0142416f68626d64366147393149465231ebf4aa7a36fe5b93a3557fa68e4b1a845fcaeb57ecf83a187b59927ffeccb1f30d
PSK: d53840ac1fd766145f29a60a74d7c68ffc75fbfe4f02c45a0133ddd229305dcf
new client on port 443 from 10.42.42.39:51564
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1056)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.39:62356
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1056)
don't panic this is probably just your phone!
^CTraceback (most recent call last):
  File "./psk-frontend.py", line 113, in <module>
    main()
  File "./psk-frontend.py", line 106, in main
    r,_,_ =  select.select(readables, [], [])
KeyboardInterrupt

smarthack-udp.log:
Listening for Tuya broadcast on UDP 6666
Listening for encrypted Tuya broadcast on UDP 6667
10.42.42.10 {"ip":"10.42.42.10","gwId":"00377585d8f15b04be7a","active":2,"ability":0,"mode":0,"encrypt":true,"productKey":"keyj979nf3q3theh","version":"3.3"}
^C% 

smarthack-web.log:
Listening on 10.42.42.1:80

GET /gw.json?a=s.gw.token.get&et=1&gwId=00377585d8f15b04be7a&other={"token":"00000000","region":"US","tlinkStat":{"configure":"smartconfig","time":1,"source":"ap","path":"broadcast"}}&t=7&v=3.0&sign=309e5fac112c64fbb94de391ed98d09a
Host: a3.tuyaus.com
User-Agent: ESP8266SDK
Connection: keep-alive

Answer s.gw.token.get
reply {"t":1595233610,"e":false,"success":true,"result":{"gwApiUrl":"http://10.42.42.1/gw.json","stdTimeZone":"-05:00","mqttRanges":"","timeZone":"-05:00","httpsPSKUrl":"https://10.42.42.1/gw.json","mediaMqttUrl":"10.42.42.1","gwMqttUrl":"10.42.42.1","dstIntervals":[],"mqttsUrl":"10.42.42.1","mqttsPSKUrl":"10.42.42.1","mediaMqttsUrl":"10.42.42.1","aispeech":"10.42.42.1"}}
[I 200720 09:26:50 web:2250] 200 GET /gw.json?a=s.gw.token.get&et=1&gwId=00377585d8f15b04be7a&other={"token":"00000000","region":"US","tlinkStat":{"configure":"smartconfig","time":1,"source":"ap","path":"broadcast"}}&t=7&v=3.0&sign=309e5fac112c64fbb94de391ed98d09a (10.42.42.1) 56.99ms

POST /gw.json?a=s.gw.dev.fk.active&et=1&gwId=00377585d8f15b04be7a&other={"token":"00000000"}&t=8&v=3.0&sign=edca730bd3f5d3de3b2debe03a3d4a0d
Host: 10.42.42.1
User-Agent: ESP8266SDK
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 485

payload 8230A8B4568AF5B9409385319B7A544E6B4E7294CF6071B309C5954D97C1356AE5D572BBFA8D6583312B041468BFCE650A4A21EBFF6CB9A99EAF2D40746609BDFBAE4CA145E9D3F9C7DF64C7611BD7FD7D38FF8797674C536DCB1050F2DF777B5823E23DAEA9438CF18D615DE02F9872A4E340B1A1F2DEB021AB2966548EA3C3E4DD848937253AE3394D4640D589B8D8DBDD14EB634971F41D8C085EC6A0E5230B512079A574F7D8AD51C88335EDB7B19EABBF49C70BA4A4BC90D7EB6F40A352CCEE85908B72FB26D2D772C31C5AD614A0324864327612AFD6E90E0BD10A7FCF36E9ABA8913B5D3B08B0F8C2E2EC78A3
Answer s.gw.dev.pk.active
reply {"t":1595233611,"e":false,"success":true,"result":{"schema":"[{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"}]","uid":"00000000000000000000","devEtag":"0000000000","secKey":"0000000000000000","schemaId":"0000000000","localKey":"0000000000000000"}}
TRIGGER UPGRADE IN 10 SECONDS
[I 200720 09:26:51 web:2250] 200 POST /gw.json?a=s.gw.dev.fk.active&et=1&gwId=00377585d8f15b04be7a&other={"token":"00000000"}&t=8&v=3.0&sign=edca730bd3f5d3de3b2debe03a3d4a0d (10.42.42.1) 99.97ms

POST /gw.json?a=tuya.device.dynamic.config.get&et=1&gwId=00377585d8f15b04be7a&t=10&v=1.0&sign=1c3cdbc2c683e43d9442429f11688219
Host: 10.42.42.1
User-Agent: ESP8266SDK
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 0

Answer tuya.device.dynamic.config.get
reply {"result":"fn8oBaEAaJe3I+enO7OkYdd0LkD9WHnY6k8vmvctrJa9WaA3RnzcxiTXft51wEM99F2VBmqNqTqJcWuiX4YubEpaNC8XBQ0vum+naeT1XRW7mevrGF2WUpAllBDW/Q5l","t":1595233612,"sign":"294aadd96f7eb20d"}
[I 200720 09:26:52 web:2250] 200 POST /gw.json?a=tuya.device.dynamic.config.get&et=1&gwId=00377585d8f15b04be7a&t=10&v=1.0&sign=1c3cdbc2c683e43d9442429f11688219 (10.42.42.1) 6.33ms

POST /gw.json?a=atop.online.debug.log&et=1&gwId=00377585d8f15b04be7a&t=1595233612&sign=b0dad1b14c8cfc15c022b6e2bdc6f788
Host: 10.42.42.1
User-Agent: ESP8266SDK
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 229

payload {"data":4,"exp":"epc1=0x00000000, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000"}
Answer atop.online.debug.log
reply {"result":"oQwdS0ZeSlfgX+dHrKUihqhQrjFjTte9/VKl8JeiNY+FXmAf4muUZeCPnR1XSN8u","t":1595233613,"sign":"51f5afd8fc7800e3"}
[I 200720 09:26:53 web:2250] 200 POST /gw.json?a=atop.online.debug.log&et=1&gwId=00377585d8f15b04be7a&t=1595233612&sign=b0dad1b14c8cfc15c022b6e2bdc6f788 (10.42.42.1) 47.97ms

POST /gw.json?a=s.gw.update&et=1&gwId=00377585d8f15b04be7a&t=1595233614&v=2.0&sign=fd16d6c1b51756faf91853c1f01018c8
Host: 10.42.42.1
User-Agent: ESP8266SDK
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 229

payload {"gwId":"00377585d8f15b04be7a","verSw":"3.3.16","bv":"5.45","pv":"2.2","cdVer":"1.0.0","devAttribute":3}
Answer generic (s.gw.update)
reply {"result":"JqgC3KcL+PhFfrJ6QVst1l5haucx2Aof7YwfLTHK1zeFXmAf4muUZeCPnR1XSN8u","t":1595233614,"sign":"6553eb9343117278"}
[I 200720 09:26:54 web:2250] 200 POST /gw.json?a=s.gw.update&et=1&gwId=00377585d8f15b04be7a&t=1595233614&v=2.0&sign=fd16d6c1b51756faf91853c1f01018c8 (10.42.42.1) 59.82ms

POST /gw.json?a=s.gw.dev.update&et=1&gwId=00377585d8f15b04be7a&t=1595233615&v=2.0&sign=d0cf1283e3be87bfc5c2c905cc01d0f1
Host: 10.42.42.1
User-Agent: ESP8266SDK
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 197

payload {"devId":"00377585d8f15b04be7a","verSw":"3.3.16","cdVer":"1.0.0","devAttribute":3}
Answer generic (s.gw.dev.update)
reply {"result":"JqgC3KcL+PhFfrJ6QVst1hVh6wq2bGSMe3YemOeNcvqFXmAf4muUZeCPnR1XSN8u","t":1595233616,"sign":"1b3e605fc0eb7e6e"}
[I 200720 09:26:56 web:2250] 200 POST /gw.json?a=s.gw.dev.update&et=1&gwId=00377585d8f15b04be7a&t=1595233615&v=2.0&sign=d0cf1283e3be87bfc5c2c905cc01d0f1 (10.42.42.1) 50.67ms
encoding {"data":{"gwId":"00377585d8f15b04be7a"},"protocol":15,"s":"1523715","t":"1595233621"} using protocol 2.2
b'2.23\x08B\xe223362196\xb7\x98\xa7\x08\xc0\xc7\xa5\xc2JB\x9c_9\xed\x91m\x13\xff\xf2Q\x17\xc1R\x94G\xde\xf6kFf0^\xd6\x9fa\xa9!\xe9\xd51\x84fS\xbc\xcf%]\xf0\x91\xfa\xef\xd4\xa8\xffL\x1a\xef\x01\r\x8e\xbd\xf5EL\xf8S\xddE\x91\x05X\xca~\xbb/\xff\xed\x0fH\xe5\xbc\x9a#\xb7\xe1qW:x\xb8#\x87\x11\xd3\xfe\xce'

POST /gw.json?a=tuya.device.upgrade.get&et=1&gwId=00377585d8f15b04be7a&t=1595233621&v=4.3&sign=80e8855abea54b3eb79494a88fe31f8d
Host: 10.42.42.1
User-Agent: ESP8266SDK
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 37

payload {"type":0}
Answer s.gw.upgrade.get
reply {"result":"NXBuln3ez+yclRKuHLyrIZFa9xM+0mFb9LQj7O2LTSrUE24kPlUfewWxjy66ka8i+if2gcvjrCBj3QU86Q1qxFgdNRT4xyl9Gf145roqTAsDwsiUfyt5tWfHXxi4+rNEblx1zwlRMvjzlvm8F22DqurYQfkNM4ZEPEbCV50oPT6z8fhl53+/foI98cWuvYhTuvuYxpQtpksOTUQHtwhh4Fh4F45WNdsPHzoa4J7L/wzRUDFvxAv1a7QVF95+HmBl16re/wMgTuKW1HrDr+znuJMk5QV3H6P5gUMc3eruvOg=","t":1595233622,"sign":"8be0baab9dbced48"}
[I 200720 09:27:02 web:2250] 200 POST /gw.json?a=tuya.device.upgrade.get&et=1&gwId=00377585d8f15b04be7a&t=1595233621&v=4.3&sign=80e8855abea54b3eb79494a88fe31f8d (10.42.42.1) 54.02ms

POST /gw.json?a=s.gw.upgrade.updatestatus&et=1&gwId=00377585d8f15b04be7a&t=1595233622&sign=0424bb1e6c5050cbfd6ec7cbdaabeca0
Host: 10.42.42.1
User-Agent: ESP8266SDK
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 69

payload {"upgradeStatus":2}
Answer s.gw.upgrade.updatestatus
reply {"result":"JqgC3KcL+PhFfrJ6QVst1ovLIUtoVuNotcmCjgI/Ri6FXmAf4muUZeCPnR1XSN8u","t":1595233622,"sign":"b129ac145d26035b"}
[I 200720 09:27:02 web:2250] 200 POST /gw.json?a=s.gw.upgrade.updatestatus&et=1&gwId=00377585d8f15b04be7a&t=1595233622&sign=0424bb1e6c5050cbfd6ec7cbdaabeca0 (10.42.42.1) 46.03ms
[I 200720 09:27:02 web:2250] 206 HEAD /files/upgrade.bin (10.42.42.10) 42.19ms
[I 200720 09:27:06 web:2250] 200 GET /files/upgrade.bin (10.42.42.10) 3712.41ms
[I 200720 09:27:56 web:2250] 302 GET /bag (10.42.42.39) 3.39ms
[I 200720 09:27:56 web:2250] 200 GET / (10.42.42.39) 3.16ms
[I 200720 09:37:30 web:2250] 200 GET /files/tasmota.bin (10.42.42.42) 594938.74ms
^CReceived SIGINT, exiting...

smarthack-wifi.log:
System info
===========
94acc3b
Linux homepi 4.19.118-v7+ #1311 SMP Mon Apr 27 14:21:24 BST 2020 armv7l GNU/Linux
OpenSSL 1.1.1d  10 Sep 2019
Dnsmasq version 2.80  Copyright (c) 2000-2018 Simon Kelley
Compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify dumpfile

This software comes with ABSOLUTELY NO WARRANTY.
Dnsmasq is free software, and you are welcome to redistribute it
under the terms of the GNU General Public License, version 2 or 3.
hostapd v2.8-devel
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Python 3.7.3
===========
Attempting to stop wpa_supplicant
Stopping NetworkManager...
Configuring AP interface...
RTNETLINK answers: File exists
Starting DNSMASQ server...
Starting AP on wlan0...
Configuration file: /dev/stdin
wlan0: Could not connect to kernel driver
Using interface wlan0 with hwaddr 72:8c:e9:8b:04:34 and ssid "vtrust-flash"
wlan0: interface state UNINITIALIZED->ENABLED
wlan0: AP-ENABLED
wlan0: AP-STA-CONNECTED 50:bc:96:67:63:49
wlan0: AP-STA-CONNECTED d8:f1:5b:04:be:7a
wlan0: AP-STA-DISCONNECTED d8:f1:5b:04:be:7a
wlan0: AP-STA-CONNECTED d8:f1:5b:04:be:7a
wlan0: AP-STA-DISCONNECTED 50:bc:96:67:63:49
wlan0: AP-STA-CONNECTED 50:bc:96:67:63:49
wlan0: AP-STA-DISCONNECTED d8:f1:5b:04:be:7a
wlan0: AP-STA-CONNECTED d8:f1:5b:04:be:7a
wlan0: AP-STA-DISCONNECTED d8:f1:5b:04:be:7a
wlan0: AP-STA-CONNECTED d8:f1:5b:04:be:7a
wlan0: interface state ENABLED->DISABLED
wlan0: AP-STA-DISCONNECTED d8:f1:5b:04:be:7a
wlan0: AP-STA-DISCONNECTED 50:bc:96:67:63:49
wlan0: AP-DISABLED
wlan0: CTRL-EVENT-TERMINATING
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
AP closed
Stopping DNSMASQ server...
Restarting NetworkManager...

**Comment by kueblc** [comment]
Can you reboot the device with `start_flash` still running? You can skip attaching a phone to `vtrust-flash`.

**Comment by Draxter** [comment]
> Can you reboot the device with `start_flash` still running? You can skip attaching a phone to `vtrust-flash`.

Certainly can. After some more messing around I am not even getting the 'vtrust-recovery' SSIDs from the two lightbulbs that I tried, so I guess I bricked them.
I still have one more stock one that I haven't touched. Could you outline the entire process to me? Is rebooting the device that is in recovery mode while start_flash is still running supposed to help recovert it back to stock firmware?

**Comment by Draxter** [comment]
I can returrn to stock firmware fine, thanks for the /undo trick, didn't realise that was a thing. But still no luck flashing Tasmota at all. Perhaps they patched the firmware. Tried all combinations of rebooting the device at various stages of tuya-convert running and no joy, still stuck on 'Attempting to flash tasmota...' screen.
