### ISSUE TITLE
Unable to flash Blitzwolf LT11 led strip

### ISSUE THREAD

**Issue by kaphwor** [ct-Open-Source/tuya-convert#712]
Hello :) 

Tried to flash a [Blitzwolf BW-LT11](https://www.blitzwolf.com/BlitzWolf-BW-LT11-Smart-LED-Light-Strip-with-4000K-Color-Temperature,-RGB-Color,-Works-with-Alexa--Google-Assistant,-APP-Control,-IP44-Water-Resistant-p-310.html) but for some reason without any success.

The steps i took was starting the tuya convert, connect my phone to vtrust-flash, put the led strip in Ez Mode (Rapid blinking) and proceed with the flash. (Successfully flashed ~12 bulbs this way)

I've attempted a full reinstall of the OS but the result was the same.

As for the output I simply get a repeated "Auto retry" message untill it pops the "Device did not appear with the intermediate firmware".

Any idea on what i'm doing wrong, including more information i'm not aware of in order to flash the led strip?

Thanks in advance :) 

**Main Module and MCU Module Firmware:**
1.0.7

**Logs:**
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/4962293/smarthack-wifi.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/4962295/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/4962296/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/4962297/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/4962298/smarthack-web.log)

**Comment by kueblc** [comment]
Unsupported firmware, see #483 for details
