### ISSUE TITLE
Other reasons for "it appears this device does not use an ESP82xx"

### ISSUE THREAD

**Issue by Simsdebims** [ct-Open-Source/tuya-convert#715]
Hi,

I've got an 1byone EOP03-EU outdoor plug which should be the same like [this one](https://templates.blakadder.com/signstek_EOP03-EU.html) (at least they look the same and have the same model number), which was reported to be successfully flashed with tuya-convert. So is it possible that there is another reason for 
`WARNING: it appears this device does not use an ESP82xx and therefore cannot install ESP based firmware` ?

Unfortunately I can't open the device (without destroying) to see which chip is actually in there...

However the device somehow reacts to the process, since the LED stops blinking when i start flashing.

[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/4975910/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/4975911/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/4975912/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/4975913/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/4975914/smarthack-wifi.log)

Thanks :-)

**Comment by kueblc** [comment]
No, there is no other reason. Your device does not contain an ESP8266. Manufacturers have been switching to other chipsets without changing the model number or FCC ID. Sorry to be the bearer of bad news!
