### ISSUE TITLE
Trying to flash Feit SYSW-BR30RGBAGT2 -- Doesn't get to intermediate stage

### ISSUE THREAD

**Issue by cmoski** [ct-Open-Source/tuya-convert#717]
Hey all -- 

Just picked up some of these bulbs at Costco. They are the SYW-BR30RGBAGT2 / Feit BPBR30/RGBw/AG/2(C) with date code 17-20-19S 11

I am able to get the bulb to connect to the wifi network, but it doesn't seem to to take the intermediate flash. Web doesn't report any traffic, psk doesn't report anything either, just see the device connected in the wifi log.

Any assistance would be appreciated. Took one of them apart and the actual module is the WB3L

(https://docs.tuya.com/en/iot/device-development/module/wifibt-dual-mode-module/wb3l-module-datasheet?id=K9duiggw2v8sp)

**Comment by sacdroid** [comment]
@cmoski were you able to get anywhere with flashing these feit br30 bulbs?

**Comment by cmoski** [comment]
@sacdroid Hey! Sorry I didn't see your reply until now. 

I gave up on flashing these bulbs and return them for a different model, sadly. I still have one if you have any ideas though :)

**Comment by bani6809** [comment]
Looks related to #814

**Comment by kueblc** [comment]
@bani6809 is probably right. Closing as the issue author has come to their own resolution.
