### ISSUE TITLE
Intermediate Firmware hangup for "Smart Wifi 4" Downlight"

### ISSUE THREAD

**Issue by atdemeo** [ct-Open-Source/tuya-convert#723]
Device did not appear with the Intermediate Firmware

Name: Smart Wifi 4" inch LED Downlight, 10W LED Recessed Dimmable Lighting..."
MAKE: Dejavu (Amazon Seller)
Model: Smart WiFi 4" inch L....Baffle Design, No Hub (With Barcode X002AJZ0RD)
[Amazon Link:  ](https://www.amazon.com/Downlight-Recessed-Dimmable-Lighting-Changing/dp/B07X3FST6D/ref=sr_1_5?dchild=1&keywords=dejavu+4%22+recessed+LED+SMART+DOWNLIGHT&qid=1596185205&sr=8-5)
Firmware: ?Not Listed anywhere on packaging or site
NOT connected to Tuya App at any point

Logs:
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/5006020/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/5006021/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/5006022/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/5006023/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/5006024/smarthack-wifi.log)

I put the light in pairing mode, and the script gets to the following:
```
SmartConfig complete.
Resending SmartConfig Packets
............
Device did not appear with the intermediate firmware
Check the *.log files in the scripts folder
Do you want to try flashing another device? [y/N] n
```

The light goes from pairing mode (Flashing) to solid and stays there.

I tried a couple fixes from other issues, such as running start_flash a second/third time, as well as trying without the phone attached to the AP, no success.  Device is not broadcasting recovery SSID that I can see.

Thanks for the help!

**Comment by kueblc** [comment]
You've unfortunately hit #483, for which there is currently no resolution. You can flash the device by serial, use the stock firmware with tuyapi for local control, or wait to see if someone develops a workaround.
