### ISSUE TITLE
No Intermediate Firmware  SMRTLite (Costco) contains TYWE2L chip - is chip supported ?

### ISSUE THREAD

**Issue by Tipalo** [ct-Open-Source/tuya-convert#726]
**Are you reporting a successful flash?**
No
**Do you have a question about configuring your newly flashed device?**
No
**Did you have issues getting a device to flash?**
Yes
Smrtlite 15" RGB color changing LED panel DS18901

[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/5011234/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/5011235/smarthack-wifi.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/5011236/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/5011237/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/5011238/smarthack-udp.log)

TC reports "no intermediate firmware"

Thanks for creating this wonderful utility.

**Comment by kueblc** [comment]
The chip is supported, the firmware is unfortunately not. You've hit #483, for which there is currently no resolution. Keep our fingers crossed someone will find a workaround, until then you'll have to flash by serial.
