### ISSUE TITLE
KingSo Smart LED E14 WiFi: Device did not appear with the intermediate firmware

### ISSUE THREAD

**Issue by SynTexDZN** [ct-Open-Source/tuya-convert#730]
### Device did not appear with the intermediate firmware

**Name :** KingSo Smart LED E14 WiFi
**Model :** KINGSOecioldde450
**Firmware Version :** 3.3.30

Even with almost perfect timing the device is not able to flash. I tried it several times and always after 2 seconds, when the flash process started, the bulb stays white and does not blink anymore. So it has a connection to the Raspberry Pi AP but something goes wrong.

_Is there only a list of devices that are supported by this project? I bought 3 other bulbs from different vendors and they also can not be flashed. My older devices / bulbs I used in my house for over 1 year now were all successfully flashed to tasmota firmware._

## Logs
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/5022585/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/5022586/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/5022587/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/5022588/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/5022589/smarthack-wifi.log)

Thanks for all kind of your help :)

**Comment by kueblc** [comment]
Unfortunately you've hit #483 

> Is there only a list of devices that are supported by this project? I bought 3 other bulbs from different vendors and they also can not be flashed. My older devices / bulbs I used in my house for over 1 year now were all successfully flashed to tasmota firmware.

There's the community maintained wiki, but as firmware updates are being continuously pushed out all bets are off.
