### ISSUE TITLE
looping with "Resending SmartConfig Packets" when attempting to flash ESP driven Smart Bulb

### ISSUE THREAD

**Issue by fnees** [ct-Open-Source/tuya-convert#733]
Hi, 
I am stuck at Resending SmartConfig Packets. 
All other cases I found here were from non-ESP devices, which doesnt seem to be my case.
Did I get an unsupported ESP? Any help would be extremely welcome as I have run out of options...

[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/5046708/smarthack-psk.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/5046709/smarthack-wifi.log)

Thank You!!

**Comment by kueblc** [comment]
Blocked by #483
