### ISSUE TITLE
Tasmota flashed LED stops working half!

### ISSUE THREAD

**Issue by carsten-h** [ct-Open-Source/tuya-convert#734]
I succesfully flashed a tuya-LED (Avatar) with tasmota.
It worked for weeks without any problem.

Suddenly it will no longer switch the light on and I can not reach the website of the LED.
But what I see is that it connects to my router and gets an IP-address.

I tried to switch it on/off more than seven times to reset it. There is shortly a "tasmota-xxxxx" SSID seen in WIFI config but I can not connect to it. Then the LED still connects to my router.

Is there anything I can do or is this LED simply dead?

Thank you!

**Comment by kueblc** [comment]
This issue tracker is for tuya-convert, please ask Tasmota.
