### ISSUE TITLE
Action LSC CCT GU10 support

### ISSUE THREAD

**Issue by deku-m** [ct-Open-Source/tuya-convert#735]
# Before opening a new issue, please read the following

**Are you reporting a successful flash?**
No as soon as i start the flash procedure it fails (blinking led to solid and keeps sending/retry packets in smartconfig mode)

**Do you have a question about configuring your newly flashed device?**
No, only how to get this supported/working.

**Did you have issues getting a device to flash?**
LSC GU10 CCT (WARM WHITE/WHITE LIGHT)

**Please remember to close your issue when the problem has been addressed!**

Additional context
https://www.action.com/globalassets/cmsarticleimages/76/02/3000267_8712879146223-111.png?preset=mediaSliderImageLargeHD

**LOGS:**
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/5077893/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/5077894/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/5077895/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/5077896/smarthack-wifi.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/5077897/smarthack-mqtt.log)

**Comment by kueblc** [comment]
Please include your logs

**Comment by deku-m** [comment]
I will look for the logs this weekend. 
They are created in script folder right?

**Comment by deku-m** [comment]
Included logs

**Comment by kueblc** [comment]
Unsupported firmware, see #483
