### ISSUE TITLE
NX-SM112 - Device did not appear with the intermediate firmware

### ISSUE THREAD

**Issue by sym0nd0** [ct-Open-Source/tuya-convert#737]
Model: NX-SM112
Firmware: unknown (if someone can tell me how to check, please, I'll update with it)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/5057790/smarthack-wifi.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/5057791/smarthack-web.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/5057792/smarthack-udp.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/5057793/smarthack-psk.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/5057794/smarthack-mqtt.log)

```
IMPORTANT
1. Connect any other device (a smartphone or something) to the WIFI vtrust-flash
   This step is IMPORTANT otherwise the smartconfig may not work!
2. Put your IoT device in autoconfig/smartconfig/pairing mode (LED will blink fast). This is usually done by pressing and holding the primary button of the device
   Make sure nothing else is plugged into your IoT device while attempting to flash.
3. Press ENTER to continue


======================================================
Starting smart config pairing procedure
Waiting for the device to install the intermediate firmware
.Put device in EZ config mode (blinking fast)
Sending SSID                  vtrust-flash
Sending wifiPassword
Sending token                 00000000
Sending secret                0101
.................
.SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
...............
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
Device did not appear with the intermediate firmware
Check the *.log files in the scripts folder
Stopping smart config
Do you want to try flashing another device? [y/N] n
======================================================
Cleaning up...
Closing AP
Exiting...
```

I bought a cheap unbranded UK power monitoring plug from AliExpress, mostly to see if I could flash it with Tuya-Convert, like I have with some other plugs. Sadly, no such luck, after multiple attempts in a row I hit upon the dreaded:

`Device did not appear with the intermediate firmware
`

I'm guessing that this plug isn't compatible with Tuya-Convert, but as I am a complete novice with this (it took me over an hour to figure out how to get the log files copied to my laptop lol) I just want to check with the expert. Not the end of the world if so but if there is something I can do to get it working that would be awesome.

It is showing on the [Tasmota template list](https://templates.blakadder.com/NX-SM112.html), thinking I might have to research flashing over GPIO if OTA is out of the window.

Thanks for any help and apologies if I've made a right mess of submitting this!

**Comment by kueblc** [comment]
#483
