### ISSUE TITLE
 tuya  air conditioning partner

### ISSUE THREAD

**Issue by flower87lucky** [ct-Open-Source/tuya-convert#740]
Who has tried this device, tuya
 air conditioning partner, support infrared reception, transmission, relay, power statistics
![u=1657434492,3786047045 fm=199 app=68 f=JPEG](https://user-images.githubusercontent.com/45326473/90115425-ac0b4f80-dd86-11ea-84c2-ea8ebdaef7c8.jpg)

**Comment by kueblc** [comment]
Check the wiki
