### ISSUE TITLE
ARLEC PC190HA - Device did not appear with intermediate firmware

### ISSUE THREAD

**Issue by theboystu** [ct-Open-Source/tuya-convert#746]
**EDIT: If i'm not mistaken this is the problem #483 ???**

Attempting to flash Tasmota to an [Arlec PC190HA](https://templates.blakadder.com/arlec_PC190HA.html) using Tuya-Convert

Using [instructions ](https://www.youtube.com/watch?v=dt5-iZc4_qU)provided by digiblurDIY

I get the error "Device did not appear with intermediate firmware" has anyone had success flashing one of these plugs with Tuya-Convert recently? The info on blackadder seems to imply it might not be possible?

Logs below

Cheers
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/5093759/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/5093760/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/5093761/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/5093762/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/5093763/smarthack-wifi.log)

**Comment by kueblc** [comment]
Yes you are correct, this is #483. Check the collaboration document on the wiki and subscribe to #483 to be notified if a workaround develops.
