### ISSUE TITLE
Vtrust does not populate

### ISSUE THREAD

**Issue by forrestrose** [ct-Open-Source/tuya-convert#75]
Using Kali-linux from windows laptop.
Have gone through the process, all the way up to flashing but can't seem to broadcast vtrust. 

All the info available is mostly for raspi and I'm struggling with this one.

Im connected by ethernet.

**Comment by Interloping** [comment]
You'll need to provide a bit more/clearer info. Have you updated config.txt with the correct device name for your wireless device? Have you checked the logs to see if there are any errors? Not all wireless devices can create an access point, so I'd be guessing that hostapd might be throwing an error.

**Comment by kueblc** [comment]
Closing until we get more feedback
