### ISSUE TITLE
Merkury A21 10W MI-BW210-999W DATE:2004

### ISSUE THREAD

**Issue by softwheat** [ct-Open-Source/tuya-convert#750]
### Before opening a new issue, please read the following

**Are you reporting a successful flash?**
No, the newer seems like I might have a newer version of the bulbs that are currently supported. I have a bunch of these that are version number 1906 and they flash just fine. I have tried the development branch like others have reported that it resolves the issues however mine no success.

I have attached the logs from the attempted flashing of the light bulbs and it keeps on trying to resend smartconfigration packets. 

The bulb is responding to the initial communication to flash, however it's not going through the flashing process.

======================================================
Starting smart config pairing procedure
Waiting for the device to install the intermediate firmware
Put device in EZ config mode (blinking fast)
Sending SSID                  vtrust-flash
Sending wifiPassword
Sending token                 00000000
Sending secret                0101
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
..............
Device did not appear with the intermediate firmware
Check the *.log files in the scripts folder
Do you want to try flashing another device? [y/N] y
======================================================

IMPORTANT
1. Connect any other device (a smartphone or something) to the WIFI vtrust-flash
   This step is IMPORTANT otherwise the smartconfig may not work!
2. Put your IoT device in autoconfig/smartconfig/pairing mode (LED will blink fast). This is usually done by pressing and holding the primary button of the device
   Make sure nothing else is plugged into your IoT device while attempting to flash.
3. Press ENTER to continue

======================================================
Starting smart config pairing procedure
Waiting for the device to install the intermediate firmware
Put device in EZ config mode (blinking fast)
Sending SSID                  vtrust-flash
Sending wifiPassword
Sending token                 00000000
Sending secret                0101
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
..............
Device did not appear with the intermediate firmware
Check the *.log files in the scripts folder
Do you want to try flashing another device? [y/N]

**Did you have issues getting a device to flash?**
The device used for flashing: Raspberry Pi 3
normal cell phone to piggie off the vflash ap

Bulb: Merkury A21 10W MI-BW210-999W DATE:2004

**Please remember to close your issue when the problem has been addressed!**

**Comment by softwheat** [comment]
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/5114476/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/5114477/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/5114478/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/5114479/smarthack-wifi.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/5114480/smarthack-mqtt.log)

**Comment by softwheat** [comment]
Give those a shot Kueblc, I am sorry I didn't know you could just drag and drop like that in the window to attach the files. Please let me know if you need anything else additionally.

**Comment by kueblc** [comment]
Unfortunately this device is not based on the ESP82xx and thus incapable of running ESP firmware like Tasmota. We do not support non ESP devices in tuya-convert.
