### ISSUE TITLE
WIFI AP not working for flashing

### ISSUE THREAD

**Issue by Dandub** [ct-Open-Source/tuya-convert#754]
Hi,

I need some help with the tuya convert as I don't seem to manage to get my pc to broadcast the AP WIFI.
See below and please let me know if I did anything wrong.
Many thanks,
Dan 

dan@Dans-NUC:~$ cd tuya-convert
dan@Dans-NUC:~/tuya-convert$ sudo ./install_prereq.sh
[sudo] password for dan: 
Hit:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 http://ie.archive.ubuntu.com/ubuntu focal InRelease                      
Hit:3 http://ie.archive.ubuntu.com/ubuntu focal-updates InRelease              
Hit:4 http://ie.archive.ubuntu.com/ubuntu focal-backports InRelease            
Hit:5 http://security.ubuntu.com/ubuntu focal-security InRelease               
Get:6 https://packages.grafana.com/enterprise/deb stable InRelease [12.1 kB]   
Err:6 https://packages.grafana.com/enterprise/deb stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8C8C34C524098CB6
Reading package lists... Done
W: GPG error: https://packages.grafana.com/enterprise/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8C8C34C524098CB6
E: The repository 'https://packages.grafana.com/enterprise/deb stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
dan@Dans-NUC:~/tuya-convert$ nano config.txt
dan@Dans-NUC:~/tuya-convert$ sudo ./start_flash.sh
tuya-convert v2.4.4
Checking for network interface wlp58s0... Found.
Checking UDP port 53... Occupied by systemd-resolve with PID 706.
Port 53 is needed to resolve DNS queries
Do you wish to terminate systemd-resolve? [y/N] y
Attempting to stop systemd-resolved.service
Checking UDP port 67... Available.
Checking TCP port 80... Available.
Checking TCP port 443... Available.
Checking UDP port 6666... Available.
Checking UDP port 6667... Available.
Checking TCP port 1883... Available.
Checking TCP port 8886... Available.
======================================================
  Starting AP in a screen.
  Starting web server in a screen
  Starting Mosquitto in a screen
  Starting PSK frontend in a screen
  Starting Tuya Discovery in a screen

======================================================

IMPORTANT
1. Connect any other device (a smartphone or something) to the WIFI vtrust-flash
   This step is IMPORTANT otherwise the smartconfig may not work!
2. Put your IoT device in autoconfig/smartconfig/pairing mode (LED will blink fast). This is usually done by pressing and holding the primary button of the device
   Make sure nothing else is plugged into your IoT device while attempting to flash.
3. Press ENTER to continue

**Comment by kueblc** [comment]
Hi Dan, could you post your wifi log please?

**Comment by Dandub** [comment]
> Hi Dan, could you post your wifi log please?

Hi Kueblc, thanks for trying to help. Please see below log

[    5.760187] iwlwifi 0000:3a:00.0: Applying debug destination EXTERNAL_DRAM
[    5.900395] iwlwifi 0000:3a:00.0: Applying debug destination EXTERNAL_DRAM
[    5.970183] iwlwifi 0000:3a:00.0: FW already configured (0) - re-configuring
[    8.343465] rfkill: input handler disabled
[    9.562519] wlp58s0: authenticate with ac:22:05:59:73:75
[    9.572204] wlp58s0: send auth to ac:22:05:59:73:75 (try 1/3)
[    9.577665] wlp58s0: authenticated
[    9.581847] wlp58s0: associate with ac:22:05:59:73:75 (try 1/3)
[    9.618789] wlp58s0: RX AssocResp from ac:22:05:59:73:75 (capab=0x511 status=0 aid=5)
[    9.621444] wlp58s0: associated
[    9.662031] IPv6: ADDRCONF(NETDEV_CHANGE): wlp58s0: link becomes ready
[   13.670811] logitech-hidpp-device 0003:046D:4023.0003: HID++ 2.0 device connected.
[   15.796736] logitech-hidpp-device 0003:046D:4054.0004: HID++ 4.5 device connected.
[   23.072091] Bluetooth: RFCOMM TTY layer initialized
[   23.072100] Bluetooth: RFCOMM socket layer initialized
[   23.072103] Bluetooth: RFCOMM ver 1.11
[   23.246895] rfkill: input handler enabled
[   25.910103] rfkill: input handler disabled
[   26.102323] audit: type=1400 audit(1598466738.726:53): apparmor="DENIED" operation="capable" profile="/snap/snapd/8790/usr/lib/snapd/snap-confine" pid=2100 comm="snap-confine" capability=4  capname="fsetid"
[   27.938124] audit: type=1400 audit(1598466740.562:54): apparmor="DENIED" operation="open" profile="snap.snap-store.ubuntu-software" name="/var/lib/snapd/hostfs/usr/share/mime/mime.cache" pid=2100 comm="snap-store" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[   27.938127] audit: type=1400 audit(1598466740.562:55): apparmor="DENIED" operation="open" profile="snap.snap-store.ubuntu-software" name="/var/lib/snapd/hostfs/usr/share/mime/globs2" pid=2100 comm="snap-store" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[   27.938129] audit: type=1400 audit(1598466740.562:56): apparmor="DENIED" operation="open" profile="snap.snap-store.ubuntu-software" name="/var/lib/snapd/hostfs/usr/share/mime/magic" pid=2100 comm="snap-store" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[   27.938131] audit: type=1400 audit(1598466740.562:57): apparmor="DENIED" operation="open" profile="snap.snap-store.ubuntu-software" name="/var/lib/snapd/hostfs/usr/share/mime/aliases" pid=2100 comm="snap-store" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[   27.938133] audit: type=1400 audit(1598466740.562:58): apparmor="DENIED" operation="open" profile="snap.snap-store.ubuntu-software" name="/var/lib/snapd/hostfs/usr/share/mime/subclasses" pid=2100 comm="snap-store" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[   27.938134] audit: type=1400 audit(1598466740.562:59): apparmor="DENIED" operation="open" profile="snap.snap-store.ubuntu-software" name="/var/lib/snapd/hostfs/usr/share/mime/icons" pid=2100 comm="snap-store" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[   27.938137] audit: type=1400 audit(1598466740.562:60): apparmor="DENIED" operation="open" profile="snap.snap-store.ubuntu-software" name="/var/lib/snapd/hostfs/usr/share/mime/generic-icons" pid=2100 comm="snap-store" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[   28.410730] audit: type=1400 audit(1598466741.034:61): apparmor="DENIED" operation="open" profile="snap.snap-store.ubuntu-software" name="/var/lib/snapd/hostfs/usr/share/glib-2.0/schemas/gschemas.compiled" pid=2100 comm="snap-store" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[   28.728939] audit: type=1107 audit(1598466741.350:62): pid=761 uid=103 auid=4294967295 ses=4294967295 msg='apparmor="DENIED" operation="dbus_method_call"  bus="system" path="/org/freedesktop/PolicyKit1/Authority" interface="org.freedesktop.DBus.Properties" member="GetAll" mask="send" name=":1.8" pid=2100 label="snap.snap-store.ubuntu-software" peer_pid=784 peer_label="unconfined"
                exe="/usr/bin/dbus-daemon" sauid=103 hostname=? addr=? terminal=?'
[   29.770241] pci 0000:01:00.0: [8086:15da] type 01 class 0x060400
[   29.770304] pci 0000:01:00.0: enabling Extended Tags
[   29.770394] pci 0000:01:00.0: supports D1 D2
[   29.770395] pci 0000:01:00.0: PME# supported from D0 D1 D2 D3hot D3cold
[   29.782149] pci 0000:02:00.0: [8086:15da] type 01 class 0x060400
[   29.782293] pci 0000:02:00.0: enabling Extended Tags
[   29.782451] pci 0000:02:00.0: supports D1 D2
[   29.782454] pci 0000:02:00.0: PME# supported from D0 D1 D2 D3hot D3cold
[   29.782855] pci 0000:02:01.0: [8086:15da] type 01 class 0x060400
[   29.782992] pci 0000:02:01.0: enabling Extended Tags
[   29.783174] pci 0000:02:01.0: supports D1 D2
[   29.783180] pci 0000:02:01.0: PME# supported from D0 D1 D2 D3hot D3cold
[   29.783611] pci 0000:02:02.0: [8086:15da] type 01 class 0x060400
[   29.783736] pci 0000:02:02.0: enabling Extended Tags
[   29.783916] pci 0000:02:02.0: supports D1 D2
[   29.783921] pci 0000:02:02.0: PME# supported from D0 D1 D2 D3hot D3cold
[   29.784347] pci 0000:01:00.0: PCI bridge to [bus 02-39]
[   29.784367] pci 0000:01:00.0:   bridge window [mem 0xc4000000-0xda0fffff]
[   29.784380] pci 0000:01:00.0:   bridge window [mem 0xa0000000-0xc1ffffff 64bit pref]
[   29.784536] pci 0000:03:00.0: [8086:15d9] type 00 class 0x088000
[   29.784591] pci 0000:03:00.0: reg 0x10: [mem 0xda000000-0xda03ffff]
[   29.784613] pci 0000:03:00.0: reg 0x14: [mem 0xda040000-0xda040fff]
[   29.784709] pci 0000:03:00.0: enabling Extended Tags
[   29.784893] pci 0000:03:00.0: supports D1 D2
[   29.784898] pci 0000:03:00.0: PME# supported from D0 D1 D2 D3hot D3cold
[   29.785275] pci 0000:02:00.0: PCI bridge to [bus 03]
[   29.785296] pci 0000:02:00.0:   bridge window [mem 0xda000000-0xda0fffff]
[   29.785463] pci 0000:02:01.0: PCI bridge to [bus 04-38]
[   29.785483] pci 0000:02:01.0:   bridge window [mem 0xc4000000-0xd9efffff]
[   29.785498] pci 0000:02:01.0:   bridge window [mem 0xa0000000-0xc1ffffff 64bit pref]
[   29.785722] pci 0000:39:00.0: [8086:15db] type 00 class 0x0c0330
[   29.785834] pci 0000:39:00.0: reg 0x10: [mem 0xd9f00000-0xd9f0ffff]
[   29.789660] pci 0000:39:00.0: supports D1 D2
[   29.789666] pci 0000:39:00.0: PME# supported from D0 D1 D2 D3hot D3cold
[   29.789774] pci 0000:39:00.0: 8.000 Gb/s available PCIe bandwidth, limited by 2.5 GT/s x4 link at 0000:02:02.0 (capable of 31.504 Gb/s with 8 GT/s x4 link)
[   29.790501] pci 0000:02:02.0: PCI bridge to [bus 39]
[   29.790522] pci 0000:02:02.0:   bridge window [mem 0xd9f00000-0xd9ffffff]
[   29.790588] pci_bus 0000:02: Allocating resources
[   29.790630] pci 0000:02:01.0: bridge window [io  0x1000-0x0fff] to [bus 04-38] add_size 1000
[   29.790638] pci 0000:02:02.0: bridge window [io  0x1000-0x0fff] to [bus 39] add_size 1000
[   29.790646] pci 0000:02:02.0: bridge window [mem 0x00100000-0x000fffff 64bit pref] to [bus 39] add_size 200000 add_align 100000
[   29.790654] pci 0000:01:00.0: bridge window [io  0x1000-0x0fff] to [bus 02-39] add_size 3000
[   29.790665] pci 0000:01:00.0: BAR 13: no space for [io  size 0x3000]
[   29.790670] pci 0000:01:00.0: BAR 13: failed to assign [io  size 0x3000]
[   29.790677] pci 0000:01:00.0: BAR 13: no space for [io  size 0x3000]
[   29.790682] pci 0000:01:00.0: BAR 13: failed to assign [io  size 0x3000]
[   29.790700] pci 0000:02:02.0: BAR 15: no space for [mem size 0x00200000 64bit pref]
[   29.790705] pci 0000:02:02.0: BAR 15: failed to assign [mem size 0x00200000 64bit pref]
[   29.790711] pci 0000:02:01.0: BAR 13: no space for [io  size 0x1000]
[   29.790715] pci 0000:02:01.0: BAR 13: failed to assign [io  size 0x1000]
[   29.790721] pci 0000:02:02.0: BAR 13: no space for [io  size 0x1000]
[   29.790726] pci 0000:02:02.0: BAR 13: failed to assign [io  size 0x1000]
[   29.790740] pci 0000:02:02.0: BAR 15: no space for [mem size 0x00200000 64bit pref]
[   29.790746] pci 0000:02:02.0: BAR 15: failed to assign [mem size 0x00200000 64bit pref]
[   29.790752] pci 0000:02:02.0: BAR 13: no space for [io  size 0x1000]
[   29.790755] pci 0000:02:02.0: BAR 13: failed to assign [io  size 0x1000]
[   29.790760] pci 0000:02:01.0: BAR 13: no space for [io  size 0x1000]
[   29.790765] pci 0000:02:01.0: BAR 13: failed to assign [io  size 0x1000]
[   29.790771] pci 0000:02:00.0: PCI bridge to [bus 03]
[   29.790788] pci 0000:02:00.0:   bridge window [mem 0xda000000-0xda0fffff]
[   29.790806] pci 0000:02:01.0: PCI bridge to [bus 04-38]
[   29.790818] pci 0000:02:01.0:   bridge window [mem 0xc4000000-0xd9efffff]
[   29.790827] pci 0000:02:01.0:   bridge window [mem 0xa0000000-0xc1ffffff 64bit pref]
[   29.790841] pci 0000:02:02.0: PCI bridge to [bus 39]
[   29.790854] pci 0000:02:02.0:   bridge window [mem 0xd9f00000-0xd9ffffff]
[   29.790872] pci 0000:01:00.0: PCI bridge to [bus 02-39]
[   29.790885] pci 0000:01:00.0:   bridge window [mem 0xc4000000-0xda0fffff]
[   29.790895] pci 0000:01:00.0:   bridge window [mem 0xa0000000-0xc1ffffff 64bit pref]
[   29.795674] xhci_hcd 0000:39:00.0: xHCI Host Controller
[   29.795692] xhci_hcd 0000:39:00.0: new USB bus registered, assigned bus number 3
[   29.801984] xhci_hcd 0000:39:00.0: hcc params 0x200077c1 hci version 0x110 quirks 0x0000000200009810
[   29.802475] usb usb3: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 5.04
[   29.802480] usb usb3: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[   29.802485] usb usb3: Product: xHCI Host Controller
[   29.802489] usb usb3: Manufacturer: Linux 5.4.0-42-generic xhci-hcd
[   29.802492] usb usb3: SerialNumber: 0000:39:00.0
[   29.803115] hub 3-0:1.0: USB hub found
[   29.803235] hub 3-0:1.0: 2 ports detected
[   29.805454] xhci_hcd 0000:39:00.0: xHCI Host Controller
[   29.805473] xhci_hcd 0000:39:00.0: new USB bus registered, assigned bus number 4
[   29.805484] xhci_hcd 0000:39:00.0: Host supports USB 3.1 Enhanced SuperSpeed
[   29.805609] usb usb4: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 5.04
[   29.805615] usb usb4: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[   29.805620] usb usb4: Product: xHCI Host Controller
[   29.805626] usb usb4: Manufacturer: Linux 5.4.0-42-generic xhci-hcd
[   29.805631] usb usb4: SerialNumber: 0000:39:00.0
[   29.806329] hub 4-0:1.0: USB hub found
[   29.806369] hub 4-0:1.0: 2 ports detected
[   54.533871] kauditd_printk_skb: 7 callbacks suppressed
[   54.533873] audit: type=1400 audit(1598466767.158:70): apparmor="DENIED" operation="open" profile="snap.snap-store.ubuntu-software" name="/var/lib/snapd/hostfs/usr/share/icons/Yaru/icon-theme.cache" pid=2100 comm="pool-org.gnome." requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[   54.533876] audit: type=1400 audit(1598466767.158:71): apparmor="DENIED" operation="open" profile="snap.snap-store.ubuntu-software" name="/var/lib/snapd/hostfs/usr/share/icons/Yaru/8x8/emblems/" pid=2100 comm="pool-org.gnome." requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[   54.534962] audit: type=1400 audit(1598466767.158:72): apparmor="DENIED" operation="open" profile="snap.snap-store.ubuntu-software" name="/var/lib/snapd/hostfs/usr/share/icons/Yaru/icon-theme.cache" pid=2100 comm="pool-org.gnome." requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[   54.534965] audit: type=1400 audit(1598466767.158:73): apparmor="DENIED" operation="open" profile="snap.snap-store.ubuntu-software" name="/var/lib/snapd/hostfs/usr/share/icons/Yaru/16x16/actions/" pid=2100 comm="pool-org.gnome." requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[   54.536902] audit: type=1400 audit(1598466767.158:74): apparmor="DENIED" operation="open" profile="snap.snap-store.ubuntu-software" name="/var/lib/snapd/hostfs/usr/share/icons/Yaru/icon-theme.cache" pid=2100 comm="pool-org.gnome." requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[   54.536904] audit: type=1400 audit(1598466767.158:75): apparmor="DENIED" operation="open" profile="snap.snap-store.ubuntu-software" name="/var/lib/snapd/hostfs/usr/share/icons/Yaru/16x16/apps/" pid=2100 comm="pool-org.gnome." requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[   54.537535] audit: type=1400 audit(1598466767.158:76): apparmor="DENIED" operation="open" profile="snap.snap-store.ubuntu-software" name="/var/lib/snapd/hostfs/usr/share/icons/Yaru/icon-theme.cache" pid=2100 comm="pool-org.gnome." requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[   54.537540] audit: type=1400 audit(1598466767.158:77): apparmor="DENIED" operation="open" profile="snap.snap-store.ubuntu-software" name="/var/lib/snapd/hostfs/usr/share/icons/Yaru/16x16/categories/" pid=2100 comm="pool-org.gnome." requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[   54.537605] audit: type=1400 audit(1598466767.158:78): apparmor="DENIED" operation="open" profile="snap.snap-store.ubuntu-software" name="/var/lib/snapd/hostfs/usr/share/icons/Yaru/icon-theme.cache" pid=2100 comm="pool-org.gnome." requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[   54.537611] audit: type=1400 audit(1598466767.158:79): apparmor="DENIED" operation="open" profile="snap.snap-store.ubuntu-software" name="/var/lib/snapd/hostfs/usr/share/icons/Yaru/16x16/devices/" pid=2100 comm="pool-org.gnome." requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[   70.698172] xhci_hcd 0000:39:00.0: Refused to change power state, currently in D3
[   70.774015] xhci_hcd 0000:39:00.0: Refused to change power state, currently in D3
[   70.774028] xhci_hcd 0000:39:00.0: Controller not ready at resume -19
[   70.774029] xhci_hcd 0000:39:00.0: PCI post-resume error -19!
[   70.774031] xhci_hcd 0000:39:00.0: HC died; cleaning up
[   70.774088] xhci_hcd 0000:39:00.0: remove, state 4
[   70.774090] usb usb4: USB disconnect, device number 1
[   70.774491] xhci_hcd 0000:39:00.0: USB bus 4 deregistered
[   70.774499] xhci_hcd 0000:39:00.0: remove, state 4
[   70.774501] usb usb3: USB disconnect, device number 1
[   70.774838] xhci_hcd 0000:39:00.0: Host halt failed, -19
[   70.774840] xhci_hcd 0000:39:00.0: Host not accessible, reset failed.
[   70.774904] xhci_hcd 0000:39:00.0: USB bus 3 deregistered
[   71.314441] pci_bus 0000:02: Allocating resources
[   71.314481] pcieport 0000:02:01.0: bridge window [io  0x1000-0x0fff] to [bus 04-38] add_size 1000
[   71.314489] pcieport 0000:02:02.0: bridge window [io  0x1000-0x0fff] to [bus 39] add_size 1000
[   71.314496] pcieport 0000:02:02.0: bridge window [mem 0x00100000-0x000fffff 64bit pref] to [bus 39] add_size 200000 add_align 100000
[   71.314503] pcieport 0000:01:00.0: bridge window [io  0x1000-0x0fff] to [bus 02-39] add_size 3000
[   71.314514] pcieport 0000:01:00.0: BAR 13: no space for [io  size 0x3000]
[   71.314519] pcieport 0000:01:00.0: BAR 13: failed to assign [io  size 0x3000]
[   71.314524] pcieport 0000:01:00.0: BAR 13: no space for [io  size 0x3000]
[   71.314527] pcieport 0000:01:00.0: BAR 13: failed to assign [io  size 0x3000]
[   71.314546] pcieport 0000:02:02.0: BAR 15: no space for [mem size 0x00200000 64bit pref]
[   71.314550] pcieport 0000:02:02.0: BAR 15: failed to assign [mem size 0x00200000 64bit pref]
[   71.314554] pcieport 0000:02:01.0: BAR 13: no space for [io  size 0x1000]
[   71.314558] pcieport 0000:02:01.0: BAR 13: failed to assign [io  size 0x1000]
[   71.314561] pcieport 0000:02:02.0: BAR 13: no space for [io  size 0x1000]
[   71.314565] pcieport 0000:02:02.0: BAR 13: failed to assign [io  size 0x1000]
[   71.314574] pcieport 0000:02:02.0: BAR 15: no space for [mem size 0x00200000 64bit pref]
[   71.314578] pcieport 0000:02:02.0: BAR 15: failed to assign [mem size 0x00200000 64bit pref]
[   71.314582] pcieport 0000:02:02.0: BAR 13: no space for [io  size 0x1000]
[   71.314586] pcieport 0000:02:02.0: BAR 13: failed to assign [io  size 0x1000]
[   71.314590] pcieport 0000:02:01.0: BAR 13: no space for [io  size 0x1000]
[   71.314594] pcieport 0000:02:01.0: BAR 13: failed to assign [io  size 0x1000]
[   75.775471] pcieport 0000:02:00.0: Refused to change power state, currently in D3
[   75.777864] pci_bus 0000:03: busn_res: [bus 03] is released
[   75.778102] pci_bus 0000:04: busn_res: [bus 04-38] is released
[   75.778411] pci_bus 0000:39: busn_res: [bus 39] is released
[   75.778679] pci_bus 0000:02: busn_res: [bus 02-39] is released
[   81.058839] kauditd_printk_skb: 4731 callbacks suppressed
[   81.058844] audit: type=1400 audit(1598466793.682:4811): apparmor="DENIED" operation="open" profile="snap.snap-store.ubuntu-software" name="/var/lib/snapd/hostfs/usr/share/mime/mime.cache" pid=2100 comm="pool-org.gnome." requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[   81.058856] audit: type=1400 audit(1598466793.682:4812): apparmor="DENIED" operation="open" profile="snap.snap-store.ubuntu-software" name="/var/lib/snapd/hostfs/usr/share/mime/globs2" pid=2100 comm="pool-org.gnome." requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[   81.058863] audit: type=1400 audit(1598466793.682:4813): apparmor="DENIED" operation="open" profile="snap.snap-store.ubuntu-software" name="/var/lib/snapd/hostfs/usr/share/mime/magic" pid=2100 comm="pool-org.gnome." requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[   81.058873] audit: type=1400 audit(1598466793.682:4814): apparmor="DENIED" operation="open" profile="snap.snap-store.ubuntu-software" name="/var/lib/snapd/hostfs/usr/share/mime/aliases" pid=2100 comm="pool-org.gnome." requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[   81.058889] audit: type=1400 audit(1598466793.682:4815): apparmor="DENIED" operation="open" profile="snap.snap-store.ubuntu-software" name="/var/lib/snapd/hostfs/usr/share/mime/subclasses" pid=2100 comm="pool-org.gnome." requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[   81.059116] audit: type=1400 audit(1598466793.682:4816): apparmor="DENIED" operation="open" profile="snap.snap-store.ubuntu-software" name="/var/lib/snapd/hostfs/usr/share/mime/icons" pid=2100 comm="pool-org.gnome." requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[   81.059128] audit: type=1400 audit(1598466793.682:4817): apparmor="DENIED" operation="open" profile="snap.snap-store.ubuntu-software" name="/var/lib/snapd/hostfs/usr/share/mime/generic-icons" pid=2100 comm="pool-org.gnome." requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[  101.787743] wlp58s0: deauthenticating from ac:22:05:59:73:75 by local choice (Reason: 3=DEAUTH_LEAVING)
[  101.806108] wlp58s0: authenticate with ac:22:05:59:73:75
[  101.814949] wlp58s0: send auth to ac:22:05:59:73:75 (try 1/3)
[  101.856542] wlp58s0: authenticated
[  101.857914] wlp58s0: associate with ac:22:05:59:73:75 (try 1/3)
[  101.896867] wlp58s0: RX AssocResp from ac:22:05:59:73:75 (capab=0x511 status=0 aid=5)
[  101.900722] wlp58s0: associated
[  193.873803] bpfilter: Loaded bpfilter_umh pid 3904
[  193.874109] Started bpfilter
[  193.975180] wlp58s0: deauthenticating from ac:22:05:59:73:75 by local choice (Reason: 3=DEAUTH_LEAVING)
[  194.704956] iwlwifi 0000:3a:00.0: Applying debug destination EXTERNAL_DRAM
[  194.840813] iwlwifi 0000:3a:00.0: Applying debug destination EXTERNAL_DRAM
[  194.908929] iwlwifi 0000:3a:00.0: FW already configured (0) - re-configuring
[  198.859755] wlp58s0: authenticate with ac:22:05:59:73:75
[  198.867095] wlp58s0: send auth to ac:22:05:59:73:75 (try 1/3)
[  198.895917] wlp58s0: authenticated
[  198.899753] wlp58s0: associate with ac:22:05:59:73:75 (try 1/3)
[  198.937088] wlp58s0: RX AssocResp from ac:22:05:59:73:75 (capab=0x511 status=0 aid=5)
[  198.941186] wlp58s0: associated
[  198.995614] IPv6: ADDRCONF(NETDEV_CHANGE): wlp58s0: link becomes ready

**Comment by kueblc** [comment]
There should be a `smarthack-wifi.log` file in your `tuya-convert/scripts` directory

**Comment by Dandub** [comment]
> There should be a `smarthack-wifi.log` file in your `tuya-convert/scripts` directory

Sorry....


This software comes with ABSOLUTELY NO WARRANTY.
Dnsmasq is free software, and you are welcome to redistribute it
under the terms of the GNU General Public License, version 2 or 3.
./setup_ap.sh: line 13: hostapd: command not found
Python 3.8.2
===========
Attempting to stop wpa_supplicant
Stopping NetworkManager...
Configuring AP interface...
RTNETLINK answers: File exists
Starting DNSMASQ server...
Starting AP on wlp58s0...
sudo: hostapd: command not found
AP closed
Stopping DNSMASQ server...
Restarting NetworkManager...
System info
===========
94acc3b
Linux Dans-NUC 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
OpenSSL 1.1.1f  31 Mar 2020
Dnsmasq version 2.80  Copyright (c) 2000-2018 Simon Kelley
Compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify dumpfile

This software comes with ABSOLUTELY NO WARRANTY.
Dnsmasq is free software, and you are welcome to redistribute it
under the terms of the GNU General Public License, version 2 or 3.
./setup_ap.sh: line 13: hostapd: command not found
Python 3.8.2
===========
Attempting to stop wpa_supplicant
Stopping NetworkManager...
Configuring AP interface...
RTNETLINK answers: File exists
Starting DNSMASQ server...
Starting AP on wlp58s0...
sudo: hostapd: command not found
AP closed
Stopping DNSMASQ server...
Restarting NetworkManager...

**Comment by Dandub** [comment]
found the problem,,,hostapd was missing now the AP is active so that's the good news
the bad news is that the BHT-002 thermostat doesn't find the AP od the AP doesn't find the thermostat...

any suggestions?

Thanks again for your help

**Comment by Dandub** [comment]
A module seems to be missing according to the below....

Starting smart config pairing procedure
Waiting for the device to install the intermediate firmware
Traceback (most recent call last):
  File "./smartconfig/main.py", line 15, in <module>
    from smartconfig import smartconfig
  File "/home/dan/tuya-convert/scripts/smartconfig/smartconfig.py", line 43, in <module>
    from multicast import multicast_head, encode_multicast_body
  File "/home/dan/tuya-convert/scripts/smartconfig/multicast.py", line 12, in <module>
    from Cryptodome.Cipher import AES
ModuleNotFoundError: No module named 'Cryptodome'
........................................................................................................................
Device did not appear with the intermediate firmware
Check the *.log files in the scripts folder
Do you want to try flashing another device? [y/N] n
