### ISSUE TITLE
Jinvoo valve flash with tua convert [ jinvoo_SM-AW713 ]

### ISSUE THREAD

**Issue by Dylantje** [ct-Open-Source/tuya-convert#755]
Do have a 
[https://templates.blakadder.com/jinvoo_SM-AW713.html](url)
Should be possible to flash..
Only how do i ghet this thing in he learning mode?

**Comment by kueblc** [comment]
Having a template does not mean it is possible to flash. Hardware and software on these devices are constantly changing, so there is no guarantee it is possible to flash even if it was possible before.

Please refer to your vendor documentation for how to set your device into pairing mode.
