### ISSUE TITLE
Fail to get any of Nedis Wi-Fi Smart Plugs (WIFIP130FWT3) flashed

### ISSUE THREAD

**Issue by miXza81** [ct-Open-Source/tuya-convert#761]
Hi.

I have no any success when trying to use _tuya-convert_ to any of my just bought _Nedis Wi-Fi Smart Plugs_ (Code: **WIFIP130FWT3**)... They are selled 3 plugs in 1 set. When I put it any of those in to Pairing mode, green LED starts to flashing, but when tuya-convert try to send SmartConfig Packets, that LED flashing stops.

I'm newbie in _tasmota_ and _tuya-convert_ use, but I have now succefully updated (and calibrated) four new _Nedis PO120 IP44 Power Monitoring Outdoor Plugs_ (Every each of them was selled one by one with code: **WIFIPO120FWT**), so I think this problem is not caused because of my stupidity.

[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/5203654/smarthack-udp.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/5203655/smarthack-psk.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/5203656/smarthack-mqtt.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/5203657/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/5203658/smarthack-wifi.log)

Not sure what firmware version them use... How to check?

Is there any hope to get those things updated without breaking them into parts?

**Comment by kueblc** [comment]
Unsupported firmware, see #483
