### ISSUE TITLE
Lerlink X802A-RF Flash tasmota failed. I brought a new wall switch today with TYWE3S Chip.

### ISSUE THREAD

**Issue by horacecar** [ct-Open-Source/tuya-convert#768]
### Before opening a new issue, please read the following

**Did you have issues getting a device to flash?**

Lerlink X802A-RF Flash tasmota failed using the latest tuya-convert v2.4.4.

 I brought a new wall switch with TYWE3S chip today, but still cannot flash with tuya-convert . (REF. Picture A).
The log i uploaded below. thank you

![A](https://user-images.githubusercontent.com/44496483/93630542-c33ffb80-fa1c-11ea-975d-03cf0539694e.jpg)
![B](https://user-images.githubusercontent.com/44496483/93630543-c3d89200-fa1c-11ea-9326-22af53834275.jpg)
![C](https://user-images.githubusercontent.com/44496483/93630534-c1763800-fa1c-11ea-909a-1470211a84e3.jpg)

[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/5247407/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/5247409/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/5247410/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/5247412/smarthack-wifi.log)

[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/5247406/smarthack-mqtt.log)

Please Help 👍
**Please remember to close your issue when the problem has been addressed!**

**Comment by kueblc** [comment]
Thank you for filling in the issue template and providing all the requested details.

Unfortunately you've hit #483. Tuya has patched the vulnerabilities we use to spoof the device onto our fake cloud. No solution in the foreseeable future but subscribe for updates and/or follow along in the wiki in case something changes.

**Comment by horacecar** [comment]
@kueblc  hello. Thanks for the reply, can I use the wire hack (esptools) to flash the Firmware for the latest tywe3s tuya chip?

**Comment by kueblc** [comment]
Yes you should be able to flash this by wire

**Comment by vizras** [comment]
What contacts needs? Please give scrin.
