### ISSUE TITLE
How to use IRRecv and IRSend?

### ISSUE THREAD

**Issue by botak13** [ct-Open-Source/tuya-convert#77]
I have now managed to flash a Wifi infrared remote control with Tasmota.
Unfortunately, I do not understand how I can now teach and send infrared commands from Tasmota.

**Comment by ctandi** [comment]
Hi botak13,

I have yet to try this function, so I can't give you an answer. Someone in the [Tasmota repo](https://github.com/arendst/Sonoff-Tasmota) might be able to help you with that. Please rather ask firmware specific questions in the corresponding repo, the chances of getting a good answer are better over there :)

Cheers
