### ISSUE TITLE
Different SoC on newer RGBCCT Bulbs

### ISSUE THREAD

**Issue by kopfsalat** [ct-Open-Source/tuya-convert#777]
Hi,

I was trying to flash a RGBCCT bulb with tasmota via tuya convert, had no luck and sent it back. Ordered [another brand](https://templates.blakadder.com/le_901001-EU-a.html) and tried again. Still no luck. So I started investigating and found Issue [#483](https://github.com/ct-Open-Source/tuya-convert/issues/483) and related Information. So I thought I could disassamble the bulb and try flashing it via serial. Found [this tutorial](https://tasmota.github.io/docs/devices/Mirabella-Genio-Bulb/) with a bulb design which looked very similar to my bulb. PCB didn't come out well and at a certain point I decided to cut the housing to get to the "inner" pcb. 
Turns out it has different pin outs so I broke off the metal shield with the RoHS sticker. I found a [Beken 7231](https://github.com/bekencorp/bk72xx-alios-2.1.0-sdk) Chip on a [WB2L shield](https://developer.tuya.com/en/docs/iot/device-development/module/wifibt-dual-mode-module/wb2l-datasheet?id=K9duegc9bualu).

I don't know if this is the right place for this information but I wanted to let you know. Maybe they are migrating to another design and Soc? I attached a photo of the LED pcb and the control pcb.

If this is not the right place, feel free to close the issue. It would be nice if you redirect me to the place where this information belongs.

Regards,
Jeldrik

![control_pcb](https://user-images.githubusercontent.com/5787847/94861603-13b15300-0438-11eb-9612-e5c65aa9a99f.jpg)
![led_pcb](https://user-images.githubusercontent.com/5787847/94861653-29267d00-0438-11eb-88f8-5ca9c7ab8d5c.jpg)

**Comment by kueblc** [comment]
Hi @kopfsalat, thanks for the report. Yes, we've been aware for some time now that manufacturers are moving away from ESP based devices. When possible, we report non-ESP devices in the log files.

I've pinned #484 for increased visibility of this issue. Feel free to contribute.
