### ISSUE TITLE
Successfully Flashed Merkury White Bulb (9W, E26)

### ISSUE THREAD

**Issue by hav0ck** [ct-Open-Source/tuya-convert#78]
I was able to successfully flash and configure a Merkury White LEB Bulb.

Here are the details for the bulb

Merkury
E26 Socket
A19 Smart Wi-Fi LED Bulb Dimmable White
MIC-BW902-999W (Canada)
MI-BW902-999WS (US) I think they are the same but I don't know for sure
GPIO5=PWM1

**Comment by ctandi** [comment]
Hi Rob,

thanks for adding the device to the wiki!

Cheers!
