### ISSUE TITLE
TYWE3S fail

### ISSUE THREAD

**Issue by dbrokenbone** [ct-Open-Source/tuya-convert#780]
i found out that my tuya switch 3gang(wifi) using TYWE3S, and i having problem flashing it with tasmota, can it flash with tasmota?

**Comment by oldschoolharry** [comment]
I have the same issue... getting the 'Resending Smartconfig packets' looping but then nothing.

**Comment by finnzz** [comment]
If you upload your log files, we can better determine what the problem may be.

**Comment by drudgebg** [comment]
Same with my new Zemismart 3gang Switch with TYWE3S
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:852)

**Comment by kueblc** [comment]
Please fill out the requested information when opening a new issue. We can't help you if you don't give us any information.

**Comment by dbrokenbone** [comment]
> I have the same issue... getting the 'Resending Smartconfig packets' looping but then nothing.

ok solved that by flashing it with usbttl cable and gpio0 to ground, and flash it with 'tasmota.bin'

**Comment by dbrokenbone** [comment]
> Same with my new Zemismart 3gang Switch with TYWE3S
> could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:852)

flash it with usbttl is way easier tho...im on Bardi's hardware

![12041](https://user-images.githubusercontent.com/3991708/95274792-f97cd800-0870-11eb-87b9-34fa55219e00.jpg)

**Comment by drudgebg** [comment]
Thanks, I already do it too. Now everything is fine.

> > Same with my new Zemismart 3gang Switch with TYWE3S
> > could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:852)
> 
> flash it with usbttl is way easier tho...im on Bardi's hardware
> 
> ![12041](https://user-images.githubusercontent.com/3991708/95274792-f97cd800-0870-11eb-87b9-34fa55219e00.jpg)

**Comment by dbrokenbone** [comment]
> Thanks, I already do it too. Now everything is fine.
> 
> > > Same with my new Zemismart 3gang Switch with TYWE3S
> > > could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:852)
> > 
> > 
> > flash it with usbttl is way easier tho...im on Bardi's hardware
> > ![12041](https://user-images.githubusercontent.com/3991708/95274792-f97cd800-0870-11eb-87b9-34fa55219e00.jpg)

awesome...good to knw...
