### ISSUE TITLE
tuya-convert hangs after start_flash.sh at "starting web server in a screen"

### ISSUE THREAD

**Issue by PuckeyP** [ct-Open-Source/tuya-convert#782]
Hi All,
I have a problem using tuya-convert.
I have installed VMWarePlayer on an up to date windows machine, installed Ubuntu Desktop, and installed tuya-convert conform instructions. All goes well, even with exactly the expected output like in the install examples, but the installation/execution stops at  "starting web server in a screen".
Any ideas how to solve this?
PPee

**Comment by PuckeyP** [comment]
mmmm... sorry. should have been more patient

**Comment by PuckeyP** [comment]
Still having problems with this. Takes such a long time for "starting webserver". This doesnot look normal is it?

**Comment by kueblc** [comment]
It should not take more than a second or two to start the web server. Check your smarthack-web.log file for issues.

**Comment by PuckeyP** [comment]
Thanks Colin,
Must be something wrong with VMWarePlayer 
Switched to a Pi (works fine),and discovered that my Tuya power switches are based on a tot supported chipset 'winner'. Thx for the swift response
PPee

**Comment by kueblc** [comment]
No problem, sorry to hear your devices are not flashable.
