### ISSUE TITLE
Bakipo plug model TP22Y can not flash

### ISSUE THREAD

**Issue by Stasky1968** [ct-Open-Source/tuya-convert#785]
Are you reporting a successful flash? no

Do you have a question about configuring your newly flashed device?  no

Did you have issues getting a device to flash? Yes

I have one Bakipo plug model TP22Y

When i start the flash the plus stop to blink , I hear the relay activate and the light becomes steady.

Smartconfig compleate
Resending Smartconfig Packets

And continue in this way 

[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/5356560/smarthack-wifi.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/5356561/smarthack-web.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/5356562/smarthack-udp.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/5356563/smarthack-psk.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/5356564/smarthack-mqtt.log)

**Comment by kueblc** [comment]
Unsupported due to patched firmware, see #483 and the wiki for details
