### ISSUE TITLE
T103_V1.0 LED Controller: Device did not appear with the intermediate firmware

### ISSUE THREAD

**Issue by jkmaxwell** [ct-Open-Source/tuya-convert#789]
**"Device did not appear with the intermediate firmware"**

Logs:
https://gist.github.com/jkmaxwell/41eabf0aabb05104cf343be9acf6ed02

Device:
Tuya XY001 WiFi RGB LED Controller

Chip Board:
T103_V1.0 2015-7-16

![Image of Board](https://user-images.githubusercontent.com/342903/95661287-fa1ca500-0ae2-11eb-834a-53d9c88acf1c.jpg)

**Comment by jkmaxwell** [comment]
It looks like this could be related to https://github.com/arendst/Tasmota/issues/6434

**Comment by kueblc** [comment]
Indeed, this is not an ESP82xx, unfortunately.
