### ISSUE TITLE
After Successfully flashed  can not conect

### ISSUE THREAD

**Issue by bensil1** [ct-Open-Source/tuya-convert#79]
1. After the sonoff device seemed dead, create a wifi network with the same SSID I set up the sonoff to connect to, but NO password/security

2. connect to the tasmota settings page (by identifying the IP address my router gave the sonoff and putting that in a web browser on a device on the same network)

the hotspot ip ?

**Comment by kueblc** [comment]
> the hotspot ip ?

No,

> the IP address my router gave the sonoff

**Comment by bensil1** [comment]
1. After the sonoff device seemed dead, create a wifi network with the same SSID I set up the sonoff to connect to, but NO password/security
