### ISSUE TITLE
decryption failed or bad record mac 

### ISSUE THREAD

**Issue by OddmarDam** [ct-Open-Source/tuya-convert#794]
I have a CALEX SMART LED REFLECTOR GU10 5W that does not want to flash with tuya convert.
I have had success flashing other models from the same brand, but this one is not flashing. They are both based on the esp8285 chip.

Here is what the logs say:
```
==> smarthack-web.log <==
[I 201013 20:25:41 web:2250] 304 GET / (10.42.42.10) 2.07ms
[I 201013 20:25:41 web:2250] 302 GET /favicon.ico (10.42.42.10) 2.54ms
[I 201013 20:25:41 web:2250] 304 GET / (10.42.42.10) 2.42ms
[I 201013 20:25:41 web:2250] 302 GET /generate_204 (10.42.42.10) 2.30ms
[I 201013 20:25:41 web:2250] 302 GET /generate_204 (10.42.42.10) 2.21ms

==> smarthack-psk.log <==
new client on port 443 from 10.42.42.36:8090
ID: 0242416f68626d64366147393149465231a7795b3208f7e5a17a748c0d219d6f74f2421feb077579d825235f513f5fece9
PSK: 05db5e897c6230658771c6d024a110c0caf012249b7d4da636ae7d8e4599dab0
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
```

This is the only information i can find on the bulb.
[Calex_Smart_Reflector_LED_lamp_5W_345lm_2200-4000K.pdf](https://github.com/ct-Open-Source/tuya-convert/files/5373756/Calex_Smart_Reflector_LED_lamp_5W_345lm_2200-4000K.pdf)

The esp chip is a esp8285
![IMG_20201013_205925](https://user-images.githubusercontent.com/4441007/95909836-0c266e00-0d97-11eb-8834-86f70a624f79.jpg)

**Comment by kueblc** [comment]
Unsupported firmware, see #483
