### ISSUE TITLE
How to flash Lumary wifi led strip controller

### ISSUE THREAD

**Issue by mnayef95** [ct-Open-Source/tuya-convert#809]
I have lumary led strip, like [this](https://www.amazon.com/Led-Strip-Lights-Waterproof-White16-4ft/dp/B07PVDXWGS).

And this is the board
![20201027_165344](https://user-images.githubusercontent.com/25001862/97317460-e2337800-187b-11eb-9803-cacc0c6b50fb.jpg)
![20201027_165352](https://user-images.githubusercontent.com/25001862/97317527-f0819400-187b-11eb-8277-01ae638e2ff9.jpg)

How I can flash it while the board is not have any place to connect it to serial port?

**Comment by kueblc** [comment]
This is not an ESP82xx so you cannot install ESP firmware on it.
