### ISSUE TITLE
Feit BR30 does not flash

### ISSUE THREAD

**Issue by bani6809** [ct-Open-Source/tuya-convert#814]
Feit BR30 do not appear to be flashable. https://www.amazon.com/gp/product/B07GFV1Y9C

Put the bulb in fast pairing mode. As soon as the packets are sent, the bulb stops flashing. But the bulb never sends any requests.

This seems completely unrelated to the issue 483 PSK issue. No PSK involved because no traffic.

**Comment by bani6809** [comment]
`
[log.txt](https://github.com/ct-Open-Source/tuya-convert/files/5506044/log.txt)
`

**Comment by bani6809** [comment]
Looks like related to #784 

So a new class of OTA upgrade failures not related to PSK.

**Comment by kueblc** [comment]
I see three devices in your wifi log, can you identify them?

**Comment by bani6809** [comment]
ac:d1:b8:c0:c2:91  laptop
a0:20:a6:16:f7:04  makerfocus d1 mini
18:69:d8:53:ab:36  appears to be the feit br30, shows up when i put the bulb into fast pairing

**Comment by kueblc** [comment]
All ESP82xx have an OUI of Espressif Inc. Unfortunately your Feit BR30 is not using an ESP82xx and thus is not capable of running third party ESP firmware. Sorry to be the bearer of bad news!

**Comment by bani6809** [comment]
disassembled the bulb, looks like feit is using the new arm-based tuya wb2l module. the FCC ID is the same as old feit br30 bulbs with esp8266, this seems to be an fcc violation.

**Comment by nsh99** [comment]
I purchased the same bulb from Lowes. Same beginning MAC address: https://maclookup.app/macaddress/1869D8
