### ISSUE TITLE
Successfully Flashed HUGOAI AWP02L-N

### ISSUE THREAD

**Issue by tkotz8105** [ct-Open-Source/tuya-convert#82]
HUGOAI Model AWP02L-N.

https://www.amazon.com/dp/B07D9H9XCD/ref=cm_sw_em_r_mt_dp_U_9QDxCb45FJZYT

I used Tasmota Generic Module with following configuration:
GPIO0:  LED2i
GPIO2:  LED1i
GPIO13: Button1
GPIO15: Relay1

I added to Wiki list of Compatible Devices

**Comment by ctandi** [comment]
Great, thanks a lot for contributing!
