### ISSUE TITLE
no shared cipher (_ssl.c:1056)

### ISSUE THREAD

**Issue by Polvere79** [ct-Open-Source/tuya-convert#822]
Hello everyone,

I'm new here, and trying to flash Tasmota on my new Teckin SP22 smartplugs.
I didn't open them, so I don't know whether they mount the right version of the chip. 
These are the plugs:
[https://www.amazon.it/Intelligente-Compatibile-TECKIN-Controllo-Temporizzazione/dp/B07D5V139R/ref=sr_1_2?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=teckin+sp22&qid=1605869977&sr=8-2](url)

I didn't manage to get them flashed, and it seems i get stuck at this, in psk log:
` "could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1056)
don't panic this is probably just your phone!"`
I tried changing the phone twice (2 different phones used), but no luck.

I saw also the dreaded message
`WARNING: it appears this device does not use an ESP82xx and therefore cannot install ESP based firmware`
but that appears only before I hit ENTER for starting the process, so I'm not sure this is the real cause (I was checking the logs live with tail -f etc...)

Attached all the logs file (i retried a few times, so logs refer to a few retries).

[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/5573092/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/5573093/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/5573094/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/5573095/smarthack-wifi.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/5573096/smarthack-mqtt.log)

Thanks in advance for helping :)

**Comment by kueblc** [comment]
> "could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1056) don't panic this is probably just your phone!"

Like the log says, it's just your phone. Nothing to worry about, it is not a problem.

> `WARNING: it appears this device does not use an ESP82xx and therefore cannot install ESP based firmware`

This is actually the real issue, the test is reliable. You will see this before pressing ENTER if the device has previously gone through the process.

Unfortunately nothing can be done on our end if it does not use the ESP82xx microcontroller. Some adventurous folks have managed to replace the chip with an ESP, but AFAIK there are no mature alternative firmware for the newer lines of IoT chips.
