### ISSUE TITLE
Girier Mini not flashing

### ISSUE THREAD

**Issue by rgrunb** [ct-Open-Source/tuya-convert#823]
Hello, I just bought two Girier Mini switches, that are almost identical to Sonoff Minis, but with 16A instead of 10A.

The flashing didn´t work out.

Has anyone been successful flashing this devices?

https://www.aliexpress.com/item/1005001273143481.html?spm=a2g0s.9042311.0.0.7ae74c4dfheTrh

I´m attaching the Log files, and maybe someone has a solution for this.

Thanks!!!

[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/5576171/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/5576172/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/5576173/smarthack-wifi.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/5576174/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/5576175/smarthack-psk.log)

**Comment by kueblc** [comment]
Unfortunately these don't use an ESP82xx. From your log:
```
WARNING: it appears this device does not use an ESP82xx and therefore cannot install ESP based firmware
```

You won't be able to use ESP firmware such as Tasmota on these devices.
