### ISSUE TITLE
Unable to flash curtain module QS-Zigbee-C01

### ISSUE THREAD

**Issue by adbig** [ct-Open-Source/tuya-convert#831]
Hi,

I was trying to flash a Tuya device named QS-Zigbee-C01 but without any success

```
Device did not appear with the intermediate firmware
Check the *.log files in the scripts folder
Do you want to try flashing another device? [y/N] 

```
![IMG_20201127_084837](https://user-images.githubusercontent.com/12624309/100424578-12925000-308e-11eb-953e-d3b21e0ad1b2.jpg)

When opening this module I discovered that it is powered by a [TYZS5](https://developer.tuya.com/en/docs/iot/device-development/module/zigbee-module/tyzs5-zigbee-module-datasheet?id=K97gu1imy1m3u) chip.

Is tuya-convert able to flash this module ? Is TYZS5 the reason why I can't manage to flahs it ?
Please find in attachement my log files .

Thanks in advance for your response.

[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/5606592/smarthack-udp.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/5606593/smarthack-psk.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/5606594/smarthack-mqtt.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/5606595/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/5606596/smarthack-wifi.log)

**Comment by kueblc** [comment]
Yes, unfortunately it looks like the TYZS5 is not based on the ESP82xx, the only chip supported by tuya-convert and ESP alternative firmware like Tasmota, Espurna, and ESPHome. Sorry to be the bearer of bad news!
