### ISSUE TITLE
Unable to flash FEIT Electric Smart WiFi Downlight LEDR6/RGBW/AG (C)

### ISSUE THREAD

**Issue by hunsra** [ct-Open-Source/tuya-convert#833]
### Before opening a new issue, please read the following

**Are you reporting a successful flash?**
No

**Do you have a question about configuring your newly flashed device?**
No

**Did you have issues getting a device to flash?**
Yes
Name: FEIT Electric Smart WiFi Downlight
Model: LEDR6/RGBW/AG (C)
Firmware: Main Module: 1.1.1, MCU Module 1.1.1

Steps to reproduce:
1.  Start start_flash.sh script.
2.  Connect to vtrust-flash with a smartphone.
3.  Put light into fast-flashing mode.
4.  Press enter on start_flash.sh script.
5.  Light stops flashing.
6.  Script reports "SmartConfig complete" and retries until finally reporting "Device did not appear with the intermediate firmware".

Logs attached.
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/5612416/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/5612417/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/5612418/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/5612419/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/5612420/smarthack-wifi.log)

**Comment by kueblc** [comment]
Unfortunately these have been patched against tuya-convert in a firmware update. We do not know when or if we will discover a workaround for this. See #483.
