### ISSUE TITLE
Device did not appear with the intermediate firmware

### ISSUE THREAD

**Issue by Cheddaz** [ct-Open-Source/tuya-convert#846]
Hi, having trouble flashing some tuya smart switches I purchased from ebay. The following is a link to the switch. 
(1/2/3gang) https://www.ebay.com.au/itm/Smart-Home-WiFi-Touch-Light-Wall-Switch-Panel-For-Alexa-Google-APP-1-2-3-Gang/174338811133?ssPageName=STRK%3AMEBIDX%3AIT&var=473534553974&_trksid=p2057872.m2749.l2649
(4 gang) https://www.ebay.com.au/itm/Smart-WiFi-Touch-Switch-RF-Wall-Light-Panel-1-2-3-4-Gang-With-Alexa-Google-Home/363092177851?ssPageName=STRK%3AMEBIDX%3AIT&var=632304674396&_trksid=p2057872.m2749.l2649
I have all gang iterations (1,2,3,4) in the house that need to be flashed, but currently I'm flashing the 2-gang version. 

What I believe is happening, is that once the first smartconfig is sent out, the device exits pairing mode and thus the smartconfig packets are resent. A side note, the switches I tried this on no longer connect to tuya.

logs:
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/5646754/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/5646755/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/5646756/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/5646757/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/5646758/smarthack-wifi.log)

Thanks for your replies in advance.

**Comment by ortegafernando** [comment]
https://github.com/ct-Open-Source/tuya-convert/issues/483

**Comment by kueblc** [comment]
Indeed @ortegafernando is correct, this is the new patched firmware from Tuya, #483.
