### ISSUE TITLE
Device will not flash WS01

### ISSUE THREAD

**Issue by alexyao2015** [ct-Open-Source/tuya-convert#851]
I'm trying to flash an Esicoo WS01 device which I was able to successfully flash 1 month ago on a raspberry pi. This time, I'm trying to use a laptop with new plugs that I just purchased. The FCC ID is the same as the last one so I can only assume that it still uses an ESP.

From the logs, it seems like the device will not connect at all to the ap. Not sure if it is because the firmware is patched or if its because my setup on my laptop isn't correct.
My phone connects just fine to the ap.

[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/5662624/smarthack-mqtt.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/5662625/smarthack-wifi.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/5662626/smarthack-udp.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/5662627/smarthack-psk.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/5662628/smarthack-web.log)

**Comment by alexyao2015** [comment]
It appears that the device has been changed to no longer be Tuya, but instead uses the cloud intelligence app.

**Comment by kueblc** [comment]
> The FCC ID is the same as the last one so I can only assume that it still uses an ESP.

Unfortunately this is not a safe assumption. There have been many reported cases of willful FCC violations by these companies.

> It appears that the device has been changed to no longer be Tuya, but instead uses the cloud intelligence app.

Too bad, hopefully you can still find ESP based devices in your area. Best of luck.
