### ISSUE TITLE
Unable to flash lonsonho x801a-l

### ISSUE THREAD

**Issue by benlad** [ct-Open-Source/tuya-convert#860]
Unable to flash light switch: lonsonho x801a-l 
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/5683442/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/5683443/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/5683444/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/5683445/smarthack-wifi.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/5683446/smarthack-mqtt.log)
![lonsonho](https://user-images.githubusercontent.com/42491597/101989738-6f028b80-3c9a-11eb-9e3f-35afb312f13a.jpg)

Thanks in advance for any assistance!

**Comment by kueblc** [comment]
Unsupported firmware, see pinned issue #483 and the wiki for more information.

**Comment by benlad** [comment]
Thanks, I added this device to the _Known Affected Devices_ on the [wiki](https://github.com/ct-Open-Source/tuya-convert/wiki/Collaboration-document-for-PSK-Identity-02).
