### ISSUE TITLE
MOES DS-102 (TYWE3S) can not be flashed

### ISSUE THREAD

**Issue by 2greatsecret** [ct-Open-Source/tuya-convert#861]
As soon as the flash process starts, I can connect to the vtrust-flash on the smartphone. But when I press Enter to start the process then: 
Starting smart config pairing procedure
Waiting for the device to install the intermediate firmware
Put device in EZ config mode (blinking fast)
Sending SSID                  vtrust-flash
Sending wifiPassword          
Sending token                 00000000
Sending secret                0101
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets

appears after a few seconds, the flashing on the switch stops and the flash script keeps trying to restart the procedure until it notices at some point that there is no device for programming.
Also switching on the pairing process several times during the tuya-connect loop immediately stops blinking as soon as the script starts the next repetition.
I recently read that the DS-102 from MOES has received a software update in the new devices.

**Comment by ortegafernando** [comment]
https://github.com/ct-Open-Source/tuya-convert/issues/483
