### ISSUE TITLE
Costco/Feit Electric Bulbs with new hardware?

### ISSUE THREAD

**Issue by mew1033** [ct-Open-Source/tuya-convert#863]
I just got a few of the Feit Electric bulbs from Costco. Here's what they look like on the inside:
![PXL_20201214_231704088](https://user-images.githubusercontent.com/4435733/102147550-27aa0580-3e28-11eb-990f-03cf5fff9031.jpg)
![PXL_20201214_231649519](https://user-images.githubusercontent.com/4435733/102147551-28db3280-3e28-11eb-8503-66ee98b4dfa9.jpg)
![PXL_20201214_231616089](https://user-images.githubusercontent.com/4435733/102147552-2973c900-3e28-11eb-9daf-2569b576374b.jpg)

Any ideas what that board is and if/how to flash it? I tried tuya-convert and got the 

    smartconfig complete.
    resending smartconfig packets

message over and over before it failed.

**Comment by mew1033** [comment]
Ah, just found it. Looks like it's one of Tuya's proprietary chips. https://github.com/ct-Open-Source/tuya-convert/issues/484

**Comment by mew1033** [comment]
Looks almost exactly like this: https://github.com/ct-Open-Source/tuya-convert/issues/777

**Comment by mikesbytes** [comment]
> Ah, just found it. Looks like it's one of Tuya's proprietary chips. #484

Are you sure about this? I just got some of these bulbs and am having the same issue, but it looks like it should be reported if it's not actually using ESP. Could you share the exact model number and FCC ID off the side of the bulb? This could be #483 related maybe.

**Comment by deznamenosnove** [comment]
did you manage to flash that bulb with any firmware? the i2go brand in Brazil is selling one almost identical to yours and i'm trying to figure out what to do
