### ISSUE TITLE
AVATTO GU10 WiFi Smart Bulb, 5W RGB+WW+CW LED Lamp Cup with Dimmable Timer Function Magic Bulb

### ISSUE THREAD

**Issue by pesor** [ct-Open-Source/tuya-convert#864]
Tried to Tuya-Convert this, but got the message that it was probably not an ESP.... chicp.

I have taken the lid off, and the circuits are fully accessable.

Anyone know which chip is used, and if it can be serial converted?

Thanks in advance
![led](https://user-images.githubusercontent.com/3110308/102220907-bcbd0500-3ee1-11eb-87c4-88e4f41724a0.jpg)

**Comment by kueblc** [comment]
Unfortunately it is definitely not an ESP. Alternative firmware like Tasmota, Espurna, ESPHome, etc only work with the ESP82xx.

Closing as this is not an issue with tuya-convert. Try searching online for the chip, if you can read it, to see if you can find any mature alternative firmware and how you might go about flashing it.
