### ISSUE TITLE
Unable to revert back to original firmware using serial. tywe3l

### ISSUE THREAD

**Issue by nospam2k** [ct-Open-Source/tuya-convert#869]
I have a MUE Home bulb (tywe3l). I have successfully flashed to Tasmota but want to go back to the original as I'm not really happy with the bulb itself.

I've tried erasing and reflashing using:

esptool.py --port /dev/cu.usbserial-1420 --baud 115200 erase_flash
esptool.py --port /dev/cu.usbserial-1420 --baud 115200 write_flash 0x000000 ~/Desktop/firmware-dfcb07-12.bin

Both return successfully but the bulb will not go into pairing mode.

I have reflashed to Tasmota using serial to make sure the bulb is ok and it is.

**Comment by kueblc** [comment]
After reflashing the backup, your bulb will be running the tuya-convert intermediate firmware, ready to accept the next command (upload a firmware, download a backup, or return to stock).

You can access these options by having tuya-convert running while you connect the device to power. The interface should automatically advance to the option selector where you'll want to press `0` for stock firmware.

Alternatively, you can do this without tuya-convert running by connecting to the `vtrust-recovery` AP and browsing to http://10.42.42.42/undo
