### ISSUE TITLE
About tuya electricity meter

### ISSUE THREAD

**Issue by vvlang** [ct-Open-Source/tuya-convert#873]
### Before opening a new issue, please read the following

**Are you reporting a successful flash?**
_Please add it to the wiki instead!_

**Do you have a question about configuring your newly flashed device?**
_Please ask in your alternative firmware's support channel instead!_

**Did you have issues getting a device to flash?**
_Please be sure to include your device **name, model, and firmware version** as well as your **logs**!_

**Please remember to close your issue when the problem has been addressed!**
![1608452495358](https://user-images.githubusercontent.com/45045804/102708783-fa55cf80-42df-11eb-8105-b53e0bc01454.jpg)

**Comment by kueblc** [comment]
HI @vvlang, unfortunately this firmware is not supported. See #483 and the wiki for more details.
