### ISSUE TITLE
Successfully flashed Martin Jerry Dimmer

### ISSUE THREAD

**Issue by kxkayser** [ct-Open-Source/tuya-convert#88]
Used Digiblur's great fork: Sonoff-Tasmota - digiDIM Temporary Fork @ 6.3.0.16, and flashed the MJ Dimmer.  Works great.  Had trouble with the MJ switch:  Works fine in Tasmota but the physical switch doesn't work.  I probably fried it.

**Comment by Vendo232** [comment]
have you resolved the physical switch?

**Comment by kxkayser** [comment]
Yes, Travis was very prompt and helpful.  Just needed to load the appropriate rules in Tasmota.  Thanks.

**Comment by Vendo232** [comment]
would you post how you fixed the issue?

**Comment by kxkayser** [comment]
I followed the instructions that were in the comment section of Travis' original post on flashing the switch.  I had missed them at first.
