### ISSUE TITLE
Review request of failed convert

### ISSUE THREAD

**Issue by titiviking** [ct-Open-Source/tuya-convert#883]
Can someone please reveiw the logs attached and confirm me the issue?

According to some research I have different log entries in the web and psk files for the "non-ESP device". So I'm wondering if the error is legit.

[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/5729623/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/5729624/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/5729625/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/5729626/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/5729627/smarthack-wifi.log)

It's a smart plug I got from AliExpress, that is Tuya compatible.
https://www.aliexpress.com/item/4001011322955.html?spm=a2g0s.9042311.0.0.7bcf4c4drY5Waa

According to a disassebly video, it does look like an ESP8266 is on-board...
https://www.youtube.com/watch?v=mG4bAAHluMU

UPDATE:
I managed to open up the smart plug... It's an ESP8285 inside.
Any chance to make the Tuya Convert work on these chips?
![IMG_20201222_131012](https://user-images.githubusercontent.com/73351833/102887452-4c6d3100-4457-11eb-8f20-89d1fd557b1f.jpg)

**Comment by kueblc** [comment]
> I have different log entries in the web and psk files for the "non-ESP device"

I do not see this in your logs.

I did see you have a PSK ID beginning in 02, which unfortunately means you are running an unsupported firmware patched by Tuya. See pinned issue #483 and the wiki for more information.
