### ISSUE TITLE
Can't flash WiFi Smart LED Strip: Device did not appear with the intermediate firmware.

### ISSUE THREAD

**Issue by phyrz91** [ct-Open-Source/tuya-convert#888]
Hi, I can't upload the software, everything is ok, the smartphone connects to vtrust-flash SSID, the led strip is in pairing mode. Unfortunately, I get this message:

```
Device did not appear with the intermediate firmware
Check the *.log files in the scripts folder
Do you want to try flashing another device? [y/N] 
```
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/5755790/smarthack-wifi.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/5755791/smarthack-web.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/5755792/smarthack-udp.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/5755793/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/5755794/smarthack-psk.log)

I have tried several times but with no success.

Chipset: TYWE3S,  Led strip work with Tuya app.

Hope to avoid soldering.
thank you in advance.

**Comment by raman325** [comment]
You are likely running into https://github.com/ct-Open-Source/tuya-convert/issues/483

**Comment by kueblc** [comment]
This is indeed #483, a new firmware from Tuya which is not currently supported. See the wiki for more information.
