### ISSUE TITLE
Successfully Flashed Gosund WP3 However Wifi Loses Connection

### ISSUE THREAD

**Issue by Photo64** [ct-Open-Source/tuya-convert#89]
I was able to successfully flash 3 Gosund WP3 smart plugs however I now notice that the wifi loses connection for a split second and then reconnects. I am using all three in Home Assistant and have a desk lamp attached to one. Every few seconds the light flickers and I see in Home Assistant it goes to "unavailable" to "turned on". 
9:59 PM Gosund1 Smart Plug changed to unavailable
9:59 PM Gosund1 Smart Plug turned on

All three smart plugs are doing this. The disconnect must only be a split second but it is constant and is making the plugs unusable. I followed this setup -> https://github.com/ct-Open-Source/tuya-convert  and once in the web page I set the plug up with these parameters:
GPIO4: Switch1, GPIO12: LED2i, GPIO13: LED1i, GPIO14: Relay1 and also did a switchmode1 3 to correct the button on/off when pressed.

Is there something that can be done to correct this behavior or is it do to the Sonoff-Tasmota v6.4.1 being used?

**Comment by kueblc** [comment]
This is a Sonoff-Tasmota issue, happy to hear your flash was successful anyway! Hope that you can find a resolution for your firmware issue :smile:

**Comment by Photo64** [comment]
I did an OTA upgrade and tried both version 6.3.0 with core 2.3.0 and version 6.4.1.15(e18263d-sonoff) with core 2_5_0/3.0.0-dev(c0f7b44)  but both still have wifi disconnects causing the light to flicker. Does anyone know which version and core that will eliminate the wifi disconnects?

**Comment by LouiS22** [comment]
Check the logging menu entry and make sure serial logging is disabled.

**Comment by Photo64** [comment]
I set it to "None" but the light is still flickering
![image](https://user-images.githubusercontent.com/18359302/52535997-04d9d200-2d23-11e9-94ca-5a84e8dc8c39.png)

**Comment by onebyside** [comment]
Wouldn't this be better addressed in Tasmota chat

**Comment by Photo64** [comment]
Have a link to that chat or do you mean create an issue in the Tasmota github?

**Comment by onebyside** [comment]
I searched " Sonoff-Tasmota " repositories. Looks to be a few possibilities.

**Comment by kueblc** [comment]
As mentioned this is not the place for firmware issues as we do not develop Sonoff-Tasmota here. Since you have successfully flashed your device, you can close this issue and seek help for your firmware via the relevant channels ie [the Sonoff-Tasmota wiki](https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting). Thanks and good luck!

**Comment by Photo64** [comment]
I'll move this over to the tasmota channels, thanks for your help
