### ISSUE TITLE
Gosund SP1 dead after set up wifi SSID on device

### ISSUE THREAD

**Issue by torsten3009** [ct-Open-Source/tuya-convert#899]
Hi, I m struggling with my SP1.
followed: https://www.heise.de/ct/artikel/Tuya-Convert-IoT-Geraete-ohne-Loeten-vom-Cloud-Zwang-befreien-4283623.html
all fine. flash complete , SP1 comes up with own WIFI.
After changing the settings to my own wifi, SSID & password the device is rebooting and seems to be dead.
After connection with energy: LED blinks 1x and after some seconds 3x more
not connected to my Wifi, no Tasmoto wifi found.

Resetting: press button 4x or 6x or for more then 40seconds, -- no response
also no reaction on single press (on/off)

any ídeas

**Comment by kueblc** [comment]
Please see Tasmota for assistance troubleshooting Tasmota. This is the issue tracker for tuya-convert issues.
