### ISSUE TITLE
BW-SHP14 "Device did not appear with the intermediate firmware"

### ISSUE THREAD

**Issue by acmeGR** [ct-Open-Source/tuya-convert#902]
Hello. New to tuya-convert.
I just tried flashing a BW-SHP14 using a Raspberry Pi 3B+ running  Raspbian Stretch Lite. It didn't work. 
I couldnt find anyone that has already done it, but I thought to give it a try at my own risk.

I couldnt get it to pairing mode.
Tuya app cant see it anymore but I can add it there from the beggining.

Starting smart config pairing procedure
Waiting for the device to install the intermediate firmware
Put device in EZ config mode (blinking fast)
Sending SSID                  vtrust-flash
Sending wifiPassword
Sending token                 00000000
Sending secret                0101
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
............
Device did not appear with the intermediate firmware
Check the *.log files in the scripts folder
Do you want to try flashing another device? [y/N]

regarding log files, I would like someone to tell me where and how to get them... :( Sorry, for my newbeness!

Many thanks in advance!

**Comment by okh-mzny** [comment]
Heya, 

the log files can be found in the "scripts" directory.
It won't hurt to see all of them, but you're probably most interested in the "smarthack-psk.log", as I suspect the plug is too new, and is running patched firmware which can't be flashed by tuya-convert anymore. (https://github.com/ct-Open-Source/tuya-convert/issues/483)

The log file should show the bulb trying to connect to your Raspberry Pi. Look for its ID, if it starts with 02, you're out of luck and you'll probably have to take apart the socket, check for an ESP8266 and flash it trough Serial (https://tasmota.github.io/docs/Getting-Started/)

Remember to NEVER connect mains power while you're flashing or working on the plug. It could fry the plug, your computer, and even you.

If you need further help with getting Tasmota to run, hit me up! :)

**Comment by acmeGR** [comment]
tbh I cant find whre the log files are.
