### ISSUE TITLE
fail flash WiFi dimmer

### ISSUE THREAD

**Issue by phoenix-blue** [ct-Open-Source/tuya-convert#907]
Hello,

I have the past time use this script a lot of time for the powerplug without any problem.
But i'm now try to flash a external WiFi dimmer.

The wifi dimmer looks to connect to the "local" AP network because i see the RASPI, my own device and a ESP_8D98C5 so that must be the dimmer (LED is also going off blinking when it's connected).

But the tuya-convert is not flash the dimmer.
What can be the problem?

I have the next log files :

[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/5860278/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/5860279/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/5860280/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/5860281/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/5860282/smarthack-wifi.log)

thanks for the help already.

**Comment by jpwise9** [comment]
Psk ID 02 - see https://github.com/ct-Open-Source/tuya-convert/issues/483

**Comment by phoenix-blue** [comment]
Thanks.
