### ISSUE TITLE
Not possibile flash the device for new firmware tuya?

### ISSUE THREAD

**Issue by maury77** [ct-Open-Source/tuya-convert#928]
### Before opening a new issue, please read the following

**Are you reporting a successful flash?**
NO

**Do you have a question about configuring your newly flashed device?**
_Please ask in your alternative firmware's support channel instead!_

**Did you have issues getting a device to flash?**

the device is AISIRER plug

 This software comes with ABSOLUTELY NO WARRANTY.
Dnsmasq is free software, and you are welcome to redistribute it
under the terms of the GNU General Public License, version 2 or 3.
hostapd v2.8-devel
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Python 3.7.3
===========
Attempting to stop wpa_supplicant
Stopping NetworkManager...
Configuring AP interface...
RTNETLINK answers: File exists
Starting DNSMASQ server...
Starting AP on wlan0...
Configuration file: /dev/stdin
wlan0: Could not connect to kernel driver
Using interface wlan0 with hwaddr ca:ca:14:b9:a3:19 and ssid "vtrust-flash"
wlan0: interface state UNINITIALIZED->ENABLED
wlan0: AP-ENABLED
wlan0: AP-STA-CONNECTED ec:fa:bc:9e:73:91
wlan0: AP-STA-CONNECTED 6e:30:e1:9a:e9:38
wlan0: AP-STA-DISCONNECTED 6e:30:e1:9a:e9:38
wlan0: AP-STA-CONNECTED 6e:30:e1:9a:e9:38
wlan0: AP-STA-DISCONNECTED 6e:30:e1:9a:e9:38
wlan0: AP-STA-CONNECTED 6e:30:e1:9a:e9:38
wlan0: AP-STA-DISCONNECTED ec:fa:bc:9e:73:91
wlan0: AP-STA-CONNECTED ec:fa:bc:9e:73:91
wlan0: AP-STA-DISCONNECTED 6e:30:e1:9a:e9:38

Listening for encrypted Tuya broadcast on UDP 6667^M
192.168.0.68 {"ip":"192.168.0.68","gwId":"xxxxxxxxxx","active":2,"ablilty":0,"encrypt":true,"productKey":"xxxxxxxxx","version":"3.3"}^M
WARNING: it appears this device does not use an ESP82xx and therefore cannot install ESP based firmware^M

could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.33:1326

**Please remember to close your issue when the problem has been addressed!**

**Comment by kueblc** [comment]
Reason is printed in log:

> WARNING: it appears this device does not use an ESP82xx and therefore cannot install ESP based firmware

Sorry, but you won't be able to flash this device with any ESP firmware by any means.
