### ISSUE TITLE
Is there a way to tell if the device can be flashed before buying it?

### ISSUE THREAD

**Issue by left4taco** [ct-Open-Source/tuya-convert#929]
Sorry for this seemingly off-topic ticket. I'm aware of the fact that Tuya released a patch that prevent tuya-convert from working, and some devices are already shipped with the new firmware. Therefore, is there anyway to tell if the device could be flashed or not? Or, if it is using esp8266 or realtek chip?

Much obliged.

**Comment by kueblc** [comment]
Unfortunately not. At least not with perfect accuracy, as retailers don't advertise this and most wouldn't even know. You can check the community maintained wiki, but this information may not be up to date or reflect differences between batches.

**Comment by left4taco** [comment]
@kueblc OK I'll try to buy some and update the list if I found them now compatible. Thanks
