### ISSUE TITLE
device to add the the affected device list

### ISSUE THREAD

**Issue by stheno** [ct-Open-Source/tuya-convert#930]
BHT-6000 Room Thermostat Floor heat controller
Ordered March 2021 from a damaged/returned reseller. So likely a late last year model or beginning of 2021.

No viable logs or anything, the script just retried multiple times and failed out saying firmware is too new.

**Comment by kueblc** [comment]
Thanks for your report, @stheno, sorry it didn't work out. Feel free to update the wiki.

**Comment by TishSerg** [comment]
> the wiki

Where is that device list wiki??? Readme.md doesn't provide any link to that!
