### ISSUE TITLE
Problems with flashing Nedis WIFIP130FWT

### ISSUE THREAD

**Issue by MelvinRC** [ct-Open-Source/tuya-convert#938]
Problems with flashing Nedis WIFIP130FWT, 

======================================================
Starting smart config pairing procedure
Waiting for the device to install the intermediate firmware
Put device in EZ config mode (blinking fast)
Sending SSID                  vtrust-flash
Sending wifiPassword          
Sending token                 00000000
Sending secret                0101
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
............
Device did not appear with the intermediate firmware
Check the *.log files in the scripts folder
Do you want to try flashing another device? [y/N] n
======================================================

Does anyone have an idea what I missed here?

Br,
Melvin

[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/6335485/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/6335486/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/6335487/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/6335488/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/6335489/smarthack-wifi.log)

**Comment by kueblc** [comment]
Your device is running new, patched, unsupported firmware. See #483 and the wiki for more details.

Update your tuya-convert installation to automatically diagnosis issues like this.
