### ISSUE TITLE
HiHome Smart Wifi Plug (Internal board NAS-WR01W6-T V2) not flashing

### ISSUE THREAD

**Issue by svdstra** [ct-Open-Source/tuya-convert#939]
Hi,

I am having problems flashing my new HiHome Smart Wifi plug.
Type of board = NAS-WR01W6-T with date mark of 20200604. It gives below feedback during Flash process.

I was able to open the device and see if i can wire up the flash tool. I found 3.3V, GND, Rx and Tx but I have no clue how to put it into programming mode.

Other soldering pads I found are labelled:
CEM
TCK
TMS
TDI
TD0

Any idea how to put it in flash mode?
Any idea why Tuya-Convert does not work?

See also pictures:
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/6344118/smarthack-psk.log)
![20210419_113514](https://user-images.githubusercontent.com/33155650/115409184-d0f77280-a1f1-11eb-8326-73395b1a7999.jpg)
![20210419_163934](https://user-images.githubusercontent.com/33155650/115409208-d654bd00-a1f1-11eb-8ad0-92137af28966.jpg)

======================================================
Starting smart config pairing procedure
Waiting for the device to install the intermediate firmware
Put device in EZ config mode (blinking fast)
Sending SSID                  vtrust-flash
Sending wifiPassword          
Sending token                 00000000
Sending secret                0101
...................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
...................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
...
Timed out while waiting for the device to (re)connect
======================================================
Attempting to diagnose the issue...
Your device's firmware is too new.
Tuya patched the PSK vulnerability that we use to establish a connection.
You might still be able to flash this device over serial.
For more information and to follow progress on solving this issue see:
https://github.com/ct-Open-Source/tuya-convert/wiki/Collaboration-document-for-PSK-Identity-02

**Did you have issues getting a device to flash?**
_Please be sure to include your device **name, model, and firmware version** as well as your **logs**!_

**Please remember to close your issue when the problem has been addressed!**

**Comment by kueblc** [comment]
> Your device's firmware is too new.
> Tuya patched the PSK vulnerability that we use to establish a connection.
> You might still be able to flash this device over serial.
> For more information and to follow progress on solving this issue see:
> https://github.com/ct-Open-Source/tuya-convert/wiki/Collaboration-document-for-PSK-Identity-02
