### ISSUE TITLE
Nedis SmokeSensor WIFIDS10WT stops after applying TuyaMCU module 54 in Tasmota 9.4.0

### ISSUE THREAD

**Issue by sydspost** [ct-Open-Source/tuya-convert#941]
After succesfull flashing my Nedis SmokeSensor WIFIDS10WT with Tasmota lite 9.2.0 en upgrading it ota to Tasmota 9.4.0, i applied the template from Blakadder, https://templates.blakadder.com/nedis_WIFIDS10WT.html

After activating the template de Smokesensor restarts and after 1 or 2 seconds the device isn't accessable via de webinterface, and appear to stop working (no MQTT logging messages are send anymore). Configuring it back to Sonoff Basic (after pulling out batteries, en putting them back in) the Smokesensor works fine, but no TuyaMCU messages are received of course.

Configuration thru Console (according to Blakadder's website)
Rule1 ON TuyaReceived#data=55AA000000010101 DO POWER ON ENDON
Rule1 1
SetOption66 1

Logging with SonOff basic module type configured

stat/tasmota_5D076B/POWER OFF
stat/tasmota_5D076B/LOGGING 00:00:00.001 HDW: ESP8266EX
stat/tasmota_5D076B/LOGGING 00:00:00.050 CFG: Loaded from flash at F5, Count 39
stat/tasmota_5D076B/LOGGING 00:00:00.055 QPC: Count 1
stat/tasmota_5D076B/LOGGING 00:00:00.060 SRC: Restart
stat/tasmota_5D076B/LOGGING 00:00:00.062 Project tasmota Tasmota Version 9.4.0(tasmota)-2_7_4_9(2021-04-23T10:07:22)
stat/tasmota_5D076B/LOGGING 00:00:00.214 WIF: Checking connection...
stat/tasmota_5D076B/LOGGING 00:00:00.215 WIF: Attempting connection...
stat/tasmota_5D076B/LOGGING 00:00:00.552 WIF: Connecting to AP1 H369ABF8AF9 Channel 9 BSSId 20:E8:82:BF:8A:F9 in mode 11n as SmokeSensor_CV_Ruimte...
stat/tasmota_5D076B/LOGGING 00:00:01.752 WIF: Checking connection...
stat/tasmota_5D076B/LOGGING 00:00:01.753 WIF: Connected
stat/tasmota_5D076B/LOGGING 00:00:02.007 HTP: Web server active on SmokeSensor_CV_Ruimte with IP address 192.168.2.101
stat/tasmota_5D076B/LOGGING 00:00:02.460 RTC: UTC 2021-04-25T14:33:37, DST 2021-03-28T02:00:00, STD 2021-10-31T03:00:00
stat/tasmota_5D076B/LOGGING 15:33:38.013 MQT: Attempting connection...
stat/tasmota_5D076B/LOGGING 15:33:38.026 MQT: Connected
stat/tasmota_5D076B/LOGGING 15:33:38.029 MQT: tele/tasmota_5D076B/LWT = Online (retained)
stat/tasmota_5D076B/LOGGING 15:33:38.032 MQT: cmnd/tasmota_5D076B/POWER =
stat/tasmota_5D076B/LOGGING 15:33:38.034 MQT: Subscribe to cmnd/tasmota_5D076B/#
stat/tasmota_5D076B/LOGGING 15:33:38.037 MQT: Subscribe to cmnd/tasmotas/#
stat/tasmota_5D076B/LOGGING 15:33:38.040 MQT: Subscribe to cmnd/DVES_5D076B_fb/#
stat/tasmota_5D076B/LOGGING 15:33:38.043 MQT: Subscribe to domoticz/out/#
stat/tasmota_5D076B/LOGGING 15:33:38.047 MQT: Unsubscribe from homeassistant/status
stat/tasmota_5D076B/LOGGING 15:33:38.056 MQT: tele/tasmota_5D076B/INFO1 = {"Info1":{"Module":"Sonoff Basic","Version":"9.4.0(tasmota)","FallbackTopic":"cmnd/DVES_5D076B_fb/","GroupTopic":"cmnd/tasmotas/"}}
stat/tasmota_5D076B/LOGGING 15:33:38.074 MQT: tele/tasmota_5D076B/INFO2 = {"Info2":{"WebServerMode":"Admin","Hostname":"SmokeSensor_CV_Ruimte","IPAddress":"192.168.2.101"}}
stat/tasmota_5D076B/LOGGING 15:33:38.084 MQT: tele/tasmota_5D076B/INFO3 = {"Info3":{"RestartReason":"External System"}}
stat/tasmota_5D076B/LOGGING 15:33:38.091 MQT: stat/tasmota_5D076B/RESULT = {"POWER":"OFF"}
stat/tasmota_5D076B/LOGGING 15:33:38.094 MQT: stat/tasmota_5D076B/POWER = OFF
stat/tasmota_5D076B/LOGGING 15:33:39.413 MQT: domoticz/in = {"idx":213,"nvalue":0,"svalue":"","Battery":100,"RSSI":7}
stat/tasmota_5D076B/LOGGING 15:33:41.469 QPC: Reset
stat/tasmota_5D076B/LOGGING 15:33:42.387 MQT: tele/tasmota_5D076B/STATE = {"Time":"2021-04-25T15:33:42","Uptime":"0T00:00:09","UptimeSec":9,"Heap":28,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"H369ABF8AF9","BSSId":"20:E8:82:BF:8A:F9","Channel":9,"RSSI":76,"Signal":-62,"LinkCount":1,"Downtime":"0T00:00:03"}}
stat/tasmota_5D076B/LOGGING 15:33:43.381 APP: Boot Count 19
stat/tasmota_5D076B/LOGGING 15:33:43.611 CFG: Saved to flash at F4, Count 40, Bytes 4096
stat/tasmota_5D076B/LOGGING 15:33:47.395 MQT: tasmota/discovery/F4CFA25D076B/config = {"ip":"192.168.2.101","dn":"Tasmota","fn":["Tasmota",null,null,null,null,null,null,null],"hn":"SmokeSensor_CV_Ruimte","mac":"F4CFA25D076B","md":"Sonoff Basic","ty":0,"if":0,"ofln":"Offline","onln":"Online","state":["OFF","ON","TOGGLE","HOLD"],"sw":"9.4.0","t":"tasmota_5D076B","ft":"%prefix%/%topic%/","tp":["cmnd","stat","tele"],"rl":[1,0,0,0,0,0,0,0],"swc":[-1,-1,-1,-1,-1,-1,-1,-1],"swn":[null,null,null,null,null,null,null,null],"btn":[0,0,0,0,0,0,0,0],"so":{"4":0,"11":0,"13":0,"17":0,"20":0,"30":0,"68":0,"73":0,"82":0,"114":0,"117":0},"lk":1,"lt_st":0,"sho":[0,0,0,0],"ver":1} (retained)
stat/tasmota_5D076B/LOGGING 15:33:47.449 MQT: tasmota/discovery/F4CFA25D076B/sensors = {"sn":{"Time":"2021-04-25T15:33:47"},"ver":1} (retained)
stat/tasmota_5D076B/LOGGING 15:33:56.767 WIF: Checking connection...
stat/tasmota_5D076B/LOGGING 15:34:16.799 WIF: Checking connection...
stat/tasmota_5D076B/LOGGING 15:34:36.753 WIF: Checking connection...

Logging with Nedis Smoke configured

stat/tasmota_5D076B/LOGGING 00:00:00.001 HDW: ESP8266EX
stat/tasmota_5D076B/LOGGING 00:00:00.050 CFG: Loaded from flash at FA, Count 42
stat/tasmota_5D076B/LOGGING 00:00:00.055 QPC: Count 1
stat/tasmota_5D076B/LOGGING 00:00:00.060 SNS: Hardware Serial
stat/tasmota_5D076B/LOGGING 00:00:00.061 TYA: Request MCU configuration at 9600 bps
stat/tasmota_5D076B/LOGGING 00:00:00.061 SRC: Restart
stat/tasmota_5D076B/LOGGING 00:00:00.110 TYA: Send "55aa0006000501010001000d"
stat/tasmota_5D076B/LOGGING 00:00:00.131 Project tasmota Tasmota Version 9.4.0(tasmota)-2_7_4_9(2021-04-23T10:07:22)
stat/tasmota_5D076B/LOGGING 00:00:00.209 CFG: Saved to flash at F9, Count 43, Bytes 4096
stat/tasmota_5D076B/LOGGING 00:00:00.211 TYA: Set WiFi LED 2 (-1)
stat/tasmota_5D076B/LOGGING 00:00:00.220 TYA: Send "55aa000300010205"
stat/tasmota_5D076B/LOGGING 00:00:00.269 WIF: Checking connection...
stat/tasmota_5D076B/LOGGING 00:00:00.270 WIF: Attempting connection...
stat/tasmota_5D076B/LOGGING 00:00:00.607 WIF: Connecting to AP1 H369ABF8AF9 Channel 9 BSSId 20:E8:82:BF:8A:F9 in mode 11n as SmokeSensor_CV_Ruimte...
stat/tasmota_5D076B/LOGGING 00:00:01.804 WIF: Checking connection...
stat/tasmota_5D076B/LOGGING 00:00:01.805 WIF: Connected
stat/tasmota_5D076B/LOGGING 00:00:02.056 HTP: Web server active on SmokeSensor_CV_Ruimte with IP address 192.168.2.101
stat/tasmota_5D076B/LOGGING 00:00:02.440 RTC: UTC 2021-04-25T14:35:50, DST 2021-03-28T02:00:00, STD 2021-10-31T03:00:00
stat/tasmota_5D076B/LOGGING 15:35:50.001 TYA: Set WiFi LED 3 (0)
stat/tasmota_5D076B/LOGGING 15:35:50.010 TYA: Send "55aa000300010306"
stat/tasmota_5D076B/LOGGING 15:35:51.054 MQT: Attempting connection...
stat/tasmota_5D076B/LOGGING 15:35:51.067 MQT: Connected
stat/tasmota_5D076B/LOGGING 15:35:51.070 MQT: tele/tasmota_5D076B/LWT = Online (retained)
stat/tasmota_5D076B/LOGGING 15:35:51.073 MQT: cmnd/tasmota_5D076B/POWER =
stat/tasmota_5D076B/LOGGING 15:35:51.075 MQT: Subscribe to cmnd/tasmota_5D076B/#
stat/tasmota_5D076B/LOGGING 15:35:51.078 MQT: Subscribe to cmnd/tasmotas/#
stat/tasmota_5D076B/LOGGING 15:35:51.081 MQT: Subscribe to cmnd/DVES_5D076B_fb/#
stat/tasmota_5D076B/LOGGING 15:35:51.083 MQT: Subscribe to domoticz/out/#
stat/tasmota_5D076B/LOGGING 15:35:51.085 MQT: Unsubscribe from homeassistant/status
stat/tasmota_5D076B/LOGGING 15:35:51.092 MQT: tele/tasmota_5D076B/INFO1 = {"Info1":{"Module":"Nedis Smoke","Version":"9.4.0(tasmota)","FallbackTopic":"cmnd/DVES_5D076B_fb/","GroupTopic":"cmnd/tasmotas/"}}
stat/tasmota_5D076B/LOGGING 15:35:51.101 MQT: tele/tasmota_5D076B/INFO2 = {"Info2":{"WebServerMode":"Admin","Hostname":"SmokeSensor_CV_Ruimte","IPAddress":"192.168.2.101"}}
stat/tasmota_5D076B/LOGGING 15:35:51.109 MQT: tele/tasmota_5D076B/INFO3 = {"Info3":{"RestartReason":"Software/System restart"}}
stat/tasmota_5D076B/LOGGING 15:35:51.116 MQT: stat/tasmota_5D076B/RESULT = {"POWER":"OFF"}
stat/tasmota_5D076B/LOGGING 15:35:51.118 MQT: stat/tasmota_5D076B/POWER = OFF
stat/tasmota_5D076B/LOGGING 15:35:51.127 TYA: Send "55aa0001000000"
stat/tasmota_5D076B/RESULT {"WifiConfig":{"2":"WifiManager"}}

Anyone an idea what's causing the module to stop working after the last TYA: Send "55aa0001000000" ?

**Comment by kueblc** [comment]
Sorry, this is the issue tracker for tuya-convert, not Tasmota. You can find excellent community support for Tasmota through their Discord. See their github page for more information. https://github.com/arendst/Tasmota
