### ISSUE TITLE
Successfully flashed ANIKUV YM-WS-1

### ISSUE THREAD

**Issue by tkotz8105** [ct-Open-Source/tuya-convert#95]
Flashed ANIKUV YM-WS-1 Smart Outlet .... Available from Amazon (US): https://www.amazon.com/Wifi-Smart-Plug-ANIKUV-Outlet/dp/B075FVRSW6

Tasmota Generic
GPIO12: LED1i
GPIO13: Button1
GPIO15: Relay1

Added to compatible devices list

**Comment by ctandi** [comment]
Thank you for your contribution!
