### ISSUE TITLE
Connect SmartHome Smart White LED Bulb

### ISSUE THREAD

**Issue by wdwithmp** [ct-Open-Source/tuya-convert#955]
Hi 

I looked blakadder for a template, as I found one for the above model CSH-B22WW10W I got a couple fo bulbs thinking I could flash Tasmota. The entire setup process all works great, I get the bulb into pairing mode as well, but it just goes back to solid state and after multiple tries I get the below message in terminal

Timed out while waiting for the device to (re)connect
======================================================
Attempting to diagnose the issue...
Your device does not use an ESP82xx.
This means you cannot flash custom ESP firmware even over serial.
======================================================
Do you want to try flashing another device? [y/N] N
======================================================

if the bulb does not use the ESP chip, would I be correct to think there couldn't then be a template available? or has the manufacturer changed the chips they now use?

btw not an expert in anyway, only just starting out with tasmota

**Comment by kueblc** [comment]
Hi @wdwithmp,

Manufacturers have been moving away from the ESP for some time now. This is true even for models which previously used the ESP. Unfortunately this means that even though this model was previously compatible, you received a version which is not.

Hope you find better luck next time!
