### ISSUE TITLE
Wifi plug with MAC address from Shenzhen RF Technology Co., Ltd and custom RF chips.

### ISSUE THREAD

**Issue by TotalCoolness** [ct-Open-Source/tuya-convert#985]
I have a device and the MAC address lookup says its by  Shenzhen RF Technology Co., Ltd. So I had a look at their website and they make their own RF modules http://www.rf-link.com/en/rfmodule.html . 

So it seems it  wont have a ESP8266/85. Is this correct ? Can anyone confirm  Shenzhen RF Technology Co., Ltd. use their own custom RF chips.

**Comment by kueblc** [comment]
Hi @TotalCoolness 

Unfortunately you are correct. This is not an ESP. All ESP82xx have a MAC OUI of Espressif, Inc.
