### ISSUE TITLE
Wipro smart bulb ported to arduino

### ISSUE THREAD

**Issue by ajaybnl** [ct-Open-Source/tuya-convert#995]
Wipro Smart RGB White and Yellow Light Bulb ported to arduino.

It contains esp8285 with 1mb flash.
I am now using it with my smqtt connection.

The chip has all leds set to high on.
You can dim them with analogwrite function.

The esp module used and pin config  is shown in images.

Now i can use it as a night alert device / slow fading rgb.
![IMG_20211012_220905](https://user-images.githubusercontent.com/30887303/136995994-8ef58b92-76d6-4c1a-80ed-57d79541a21e.jpg)

![images](https://user-images.githubusercontent.com/30887303/136995282-c17bc700-a211-4689-ae92-57c87c93399c.png)

![IMG_20211012_215730](https://user-images.githubusercontent.com/30887303/136994414-fc3eb79f-d170-41ce-8561-4cf4073db4cb.jpg)
![IMG_20211012_215740](https://user-images.githubusercontent.com/30887303/136994423-8539d151-f433-472b-8c46-acb870163ae5.jpg)

![images (1)](https://user-images.githubusercontent.com/30887303/136995255-b9c429c4-d774-4a01-aa3b-136216298015.png)

**Comment by rpavlik** [comment]
That's pretty cool. However, this isn't the right repo to contribute this, this repo is just for the tools that let you load custom firmware on some (primarily older) Tuya devices over-the-air. Perhaps the tasmota templates repo would be interested in having this data added?
